// Code generated by MockGen. DO NOT EDIT.
// Source: hospital-backend/internal/rolepermissions (interfaces: RolePermissionRepo)
//
// Generated by this command:
//
//	mockgen -destination=internal/rolepermissions/mocks/mock_role_permission_repository.go -package=mocks hospital-backend/internal/rolepermissions RolePermissionRepo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	rolepermissions "hospital-backend/internal/rolepermissions"
	dto "hospital-backend/internal/rolepermissions/dto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	zap "go.uber.org/zap"
	gorm "gorm.io/gorm"
)

// MockRolePermissionRepo is a mock of RolePermissionRepo interface.
type MockRolePermissionRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRolePermissionRepoMockRecorder
	isgomock struct{}
}

// MockRolePermissionRepoMockRecorder is the mock recorder for MockRolePermissionRepo.
type MockRolePermissionRepoMockRecorder struct {
	mock *MockRolePermissionRepo
}

// NewMockRolePermissionRepo creates a new mock instance.
func NewMockRolePermissionRepo(ctrl *gomock.Controller) *MockRolePermissionRepo {
	mock := &MockRolePermissionRepo{ctrl: ctrl}
	mock.recorder = &MockRolePermissionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRolePermissionRepo) EXPECT() *MockRolePermissionRepoMockRecorder {
	return m.recorder
}

// BatchCreate mocks base method.
func (m *MockRolePermissionRepo) BatchCreate(log *zap.Logger, tx *gorm.DB, rolePermissions []rolepermissions.RolePermission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreate", log, tx, rolePermissions)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchCreate indicates an expected call of BatchCreate.
func (mr *MockRolePermissionRepoMockRecorder) BatchCreate(log, tx, rolePermissions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreate", reflect.TypeOf((*MockRolePermissionRepo)(nil).BatchCreate), log, tx, rolePermissions)
}

// Create mocks base method.
func (m *MockRolePermissionRepo) Create(log *zap.Logger, rolePermission *rolepermissions.RolePermission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", log, rolePermission)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRolePermissionRepoMockRecorder) Create(log, rolePermission any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRolePermissionRepo)(nil).Create), log, rolePermission)
}

// FindById mocks base method.
func (m *MockRolePermissionRepo) FindById(log *zap.Logger, id string) (*rolepermissions.RolePermission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", log, id)
	ret0, _ := ret[0].(*rolepermissions.RolePermission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockRolePermissionRepoMockRecorder) FindById(log, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockRolePermissionRepo)(nil).FindById), log, id)
}

// FindModulePermissionsByRoleID mocks base method.
func (m *MockRolePermissionRepo) FindModulePermissionsByRoleID(log *zap.Logger, roleID string) ([]dto.ModulePermissionRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindModulePermissionsByRoleID", log, roleID)
	ret0, _ := ret[0].([]dto.ModulePermissionRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindModulePermissionsByRoleID indicates an expected call of FindModulePermissionsByRoleID.
func (mr *MockRolePermissionRepoMockRecorder) FindModulePermissionsByRoleID(log, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindModulePermissionsByRoleID", reflect.TypeOf((*MockRolePermissionRepo)(nil).FindModulePermissionsByRoleID), log, roleID)
}

// IsAdminRole mocks base method.
func (m *MockRolePermissionRepo) IsAdminRole(log *zap.Logger, roleID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAdminRole", log, roleID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAdminRole indicates an expected call of IsAdminRole.
func (mr *MockRolePermissionRepoMockRecorder) IsAdminRole(log, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAdminRole", reflect.TypeOf((*MockRolePermissionRepo)(nil).IsAdminRole), log, roleID)
}
