// Code generated by MockGen. DO NOT EDIT.
// Source: hospital-backend/internal/jwt (interfaces: RefreshtokenRepo)
//
// Generated by this command:
//
//	mockgen -destination=internal/jwt/mocks/mock_refresh_token_repository.go -package=mocks hospital-backend/internal/jwt RefreshtokenRepo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	jwt "hospital-backend/internal/jwt"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockRefreshtokenRepo is a mock of RefreshtokenRepo interface.
type MockRefreshtokenRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshtokenRepoMockRecorder
	isgomock struct{}
}

// MockRefreshtokenRepoMockRecorder is the mock recorder for MockRefreshtokenRepo.
type MockRefreshtokenRepoMockRecorder struct {
	mock *MockRefreshtokenRepo
}

// NewMockRefreshtokenRepo creates a new mock instance.
func NewMockRefreshtokenRepo(ctrl *gomock.Controller) *MockRefreshtokenRepo {
	mock := &MockRefreshtokenRepo{ctrl: ctrl}
	mock.recorder = &MockRefreshtokenRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshtokenRepo) EXPECT() *MockRefreshtokenRepoMockRecorder {
	return m.recorder
}

// CheckIfExist mocks base method.
func (m *MockRefreshtokenRepo) CheckIfExist(ID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckIfExist", ID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckIfExist indicates an expected call of CheckIfExist.
func (mr *MockRefreshtokenRepoMockRecorder) CheckIfExist(ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckIfExist", reflect.TypeOf((*MockRefreshtokenRepo)(nil).CheckIfExist), ID)
}

// DeleteByID mocks base method.
func (m *MockRefreshtokenRepo) DeleteByID(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockRefreshtokenRepoMockRecorder) DeleteByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockRefreshtokenRepo)(nil).DeleteByID), id)
}

// DeleteByUserID mocks base method.
func (m *MockRefreshtokenRepo) DeleteByUserID(userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserID", userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUserID indicates an expected call of DeleteByUserID.
func (mr *MockRefreshtokenRepoMockRecorder) DeleteByUserID(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserID", reflect.TypeOf((*MockRefreshtokenRepo)(nil).DeleteByUserID), userID)
}

// FindByID mocks base method.
func (m *MockRefreshtokenRepo) FindByID(ID string) (*jwt.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ID)
	ret0, _ := ret[0].(*jwt.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRefreshtokenRepoMockRecorder) FindByID(ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRefreshtokenRepo)(nil).FindByID), ID)
}

// FindIDByUserID mocks base method.
func (m *MockRefreshtokenRepo) FindIDByUserID(userID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindIDByUserID", userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindIDByUserID indicates an expected call of FindIDByUserID.
func (mr *MockRefreshtokenRepoMockRecorder) FindIDByUserID(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindIDByUserID", reflect.TypeOf((*MockRefreshtokenRepo)(nil).FindIDByUserID), userID)
}

// Insert mocks base method.
func (m *MockRefreshtokenRepo) Insert(refreshToken *jwt.RefreshToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", refreshToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockRefreshtokenRepoMockRecorder) Insert(refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockRefreshtokenRepo)(nil).Insert), refreshToken)
}

// Update mocks base method.
func (m *MockRefreshtokenRepo) Update(refreshToken string, expiresAt time.Time, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", refreshToken, expiresAt, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRefreshtokenRepoMockRecorder) Update(refreshToken, expiresAt, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRefreshtokenRepo)(nil).Update), refreshToken, expiresAt, id)
}
