// Code generated by MockGen. DO NOT EDIT.
// Source: hospital-backend/internal/roles (interfaces: RoleRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/roles/mocks/mock_role_repository.go -package=mocks hospital-backend/internal/roles RoleRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	roles "hospital-backend/internal/roles"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockRoleRepository is a mock of RoleRepository interface.
type MockRoleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRoleRepositoryMockRecorder
	isgomock struct{}
}

// MockRoleRepositoryMockRecorder is the mock recorder for MockRoleRepository.
type MockRoleRepositoryMockRecorder struct {
	mock *MockRoleRepository
}

// NewMockRoleRepository creates a new mock instance.
func NewMockRoleRepository(ctrl *gomock.Controller) *MockRoleRepository {
	mock := &MockRoleRepository{ctrl: ctrl}
	mock.recorder = &MockRoleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleRepository) EXPECT() *MockRoleRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockRoleRepository) Count(organisationID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", organisationID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockRoleRepositoryMockRecorder) Count(organisationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockRoleRepository)(nil).Count), organisationID)
}

// Create mocks base method.
func (m *MockRoleRepository) Create(tx *gorm.DB, role *roles.Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", tx, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRoleRepositoryMockRecorder) Create(tx, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRoleRepository)(nil).Create), tx, role)
}

// FindByID mocks base method.
func (m *MockRoleRepository) FindByID(id string) (roles.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(roles.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRoleRepositoryMockRecorder) FindByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRoleRepository)(nil).FindByID), id)
}

// FindMany mocks base method.
func (m *MockRoleRepository) FindMany(organisationID string, limit, offset int) ([]roles.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMany", organisationID, limit, offset)
	ret0, _ := ret[0].([]roles.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMany indicates an expected call of FindMany.
func (mr *MockRoleRepositoryMockRecorder) FindMany(organisationID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMany", reflect.TypeOf((*MockRoleRepository)(nil).FindMany), organisationID, limit, offset)
}

// FindRoleByNames mocks base method.
func (m *MockRoleRepository) FindRoleByNames(organisationID, name string) (roles.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRoleByNames", organisationID, name)
	ret0, _ := ret[0].(roles.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRoleByNames indicates an expected call of FindRoleByNames.
func (mr *MockRoleRepositoryMockRecorder) FindRoleByNames(organisationID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRoleByNames", reflect.TypeOf((*MockRoleRepository)(nil).FindRoleByNames), organisationID, name)
}

// FindRoleByOrgID mocks base method.
func (m *MockRoleRepository) FindRoleByOrgID(organisationID string) ([]roles.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRoleByOrgID", organisationID)
	ret0, _ := ret[0].([]roles.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRoleByOrgID indicates an expected call of FindRoleByOrgID.
func (mr *MockRoleRepositoryMockRecorder) FindRoleByOrgID(organisationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRoleByOrgID", reflect.TypeOf((*MockRoleRepository)(nil).FindRoleByOrgID), organisationID)
}

// InsertMany mocks base method.
func (m *MockRoleRepository) InsertMany(tx *gorm.DB, role []roles.Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertMany", tx, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertMany indicates an expected call of InsertMany.
func (mr *MockRoleRepositoryMockRecorder) InsertMany(tx, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertMany", reflect.TypeOf((*MockRoleRepository)(nil).InsertMany), tx, role)
}
