// Code generated by MockGen. DO NOT EDIT.
// Source: hospital-backend/internal/roles (interfaces: RoleServicer)
//
// Generated by this command:
//
//	mockgen -destination=internal/roles/mocks/mock_role_servicer.go -package=mocks hospital-backend/internal/roles RoleServicer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	dto "hospital-backend/internal/roles/dto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRoleServicer is a mock of RoleServicer interface.
type MockRoleServicer struct {
	ctrl     *gomock.Controller
	recorder *MockRoleServicerMockRecorder
	isgomock struct{}
}

// MockRoleServicerMockRecorder is the mock recorder for MockRoleServicer.
type MockRoleServicerMockRecorder struct {
	mock *MockRoleServicer
}

// NewMockRoleServicer creates a new mock instance.
func NewMockRoleServicer(ctrl *gomock.Controller) *MockRoleServicer {
	mock := &MockRoleServicer{ctrl: ctrl}
	mock.recorder = &MockRoleServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleServicer) EXPECT() *MockRoleServicerMockRecorder {
	return m.recorder
}

// FindMany mocks base method.
func (m *MockRoleServicer) FindMany(organisationID string, limit, offset int) ([]dto.RoleResponse, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMany", organisationID, limit, offset)
	ret0, _ := ret[0].([]dto.RoleResponse)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindMany indicates an expected call of FindMany.
func (mr *MockRoleServicerMockRecorder) FindMany(organisationID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMany", reflect.TypeOf((*MockRoleServicer)(nil).FindMany), organisationID, limit, offset)
}
