// Code generated by MockGen. DO NOT EDIT.
// Source: hospital-backend/internal/dashboard (interfaces: DashboardServicer)
//
// Generated by this command:
//
//	mockgen -destination=internal/dashboard/mocks/mock_dashboard_servicer.go -package=mocks hospital-backend/internal/dashboard DashboardServicer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	dto "hospital-backend/internal/appointments/dto"
	dto0 "hospital-backend/internal/billing/dto"
	dto1 "hospital-backend/internal/employee/dto"
	dto2 "hospital-backend/internal/prescription/dto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	zap "go.uber.org/zap"
)

// MockDashboardServicer is a mock of DashboardServicer interface.
type MockDashboardServicer struct {
	ctrl     *gomock.Controller
	recorder *MockDashboardServicerMockRecorder
	isgomock struct{}
}

// MockDashboardServicerMockRecorder is the mock recorder for MockDashboardServicer.
type MockDashboardServicerMockRecorder struct {
	mock *MockDashboardServicer
}

// NewMockDashboardServicer creates a new mock instance.
func NewMockDashboardServicer(ctrl *gomock.Controller) *MockDashboardServicer {
	mock := &MockDashboardServicer{ctrl: ctrl}
	mock.recorder = &MockDashboardServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDashboardServicer) EXPECT() *MockDashboardServicerMockRecorder {
	return m.recorder
}

// GetAppointmentsGroupedByStatus mocks base method.
func (m *MockDashboardServicer) GetAppointmentsGroupedByStatus(log *zap.Logger, organisationID string) (dto.AppointmentStatusCounts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppointmentsGroupedByStatus", log, organisationID)
	ret0, _ := ret[0].(dto.AppointmentStatusCounts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppointmentsGroupedByStatus indicates an expected call of GetAppointmentsGroupedByStatus.
func (mr *MockDashboardServicerMockRecorder) GetAppointmentsGroupedByStatus(log, organisationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppointmentsGroupedByStatus", reflect.TypeOf((*MockDashboardServicer)(nil).GetAppointmentsGroupedByStatus), log, organisationID)
}

// GetEmployeeStatusCounts mocks base method.
func (m *MockDashboardServicer) GetEmployeeStatusCounts(log *zap.Logger, organisationID string) (dto1.EmployeeStatusCounts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeeStatusCounts", log, organisationID)
	ret0, _ := ret[0].(dto1.EmployeeStatusCounts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeeStatusCounts indicates an expected call of GetEmployeeStatusCounts.
func (mr *MockDashboardServicerMockRecorder) GetEmployeeStatusCounts(log, organisationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeeStatusCounts", reflect.TypeOf((*MockDashboardServicer)(nil).GetEmployeeStatusCounts), log, organisationID)
}

// GetTodayCompletedInvoiceSummary mocks base method.
func (m *MockDashboardServicer) GetTodayCompletedInvoiceSummary(log *zap.Logger, organisationID string) (dto0.TodayInvoiceCollectionSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTodayCompletedInvoiceSummary", log, organisationID)
	ret0, _ := ret[0].(dto0.TodayInvoiceCollectionSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTodayCompletedInvoiceSummary indicates an expected call of GetTodayCompletedInvoiceSummary.
func (mr *MockDashboardServicerMockRecorder) GetTodayCompletedInvoiceSummary(log, organisationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTodayCompletedInvoiceSummary", reflect.TypeOf((*MockDashboardServicer)(nil).GetTodayCompletedInvoiceSummary), log, organisationID)
}

// GetTodayLatestAppointments mocks base method.
func (m *MockDashboardServicer) GetTodayLatestAppointments(log *zap.Logger, organisationID string) ([]dto.AppointmentList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTodayLatestAppointments", log, organisationID)
	ret0, _ := ret[0].([]dto.AppointmentList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTodayLatestAppointments indicates an expected call of GetTodayLatestAppointments.
func (mr *MockDashboardServicerMockRecorder) GetTodayLatestAppointments(log, organisationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTodayLatestAppointments", reflect.TypeOf((*MockDashboardServicer)(nil).GetTodayLatestAppointments), log, organisationID)
}

// GetTodayPrescriptions mocks base method.
func (m *MockDashboardServicer) GetTodayPrescriptions(log *zap.Logger, organisationID string) (dto2.TodayPrescriptionsSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTodayPrescriptions", log, organisationID)
	ret0, _ := ret[0].(dto2.TodayPrescriptionsSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTodayPrescriptions indicates an expected call of GetTodayPrescriptions.
func (mr *MockDashboardServicerMockRecorder) GetTodayPrescriptions(log, organisationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTodayPrescriptions", reflect.TypeOf((*MockDashboardServicer)(nil).GetTodayPrescriptions), log, organisationID)
}
