// Code generated by MockGen. DO NOT EDIT.
// Source: hospital-backend/internal/dashboard (interfaces: PrescriptionDashboardReader)
//
// Generated by this command:
//
//	mockgen -destination=internal/dashboard/mocks/mock_prescription_dashboard_reader.go -package=mocks hospital-backend/internal/dashboard PrescriptionDashboardReader
//

// Package mocks is a generated GoMock package.
package mocks

import (
	dto "hospital-backend/internal/prescription/dto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	zap "go.uber.org/zap"
)

// MockPrescriptionDashboardReader is a mock of PrescriptionDashboardReader interface.
type MockPrescriptionDashboardReader struct {
	ctrl     *gomock.Controller
	recorder *MockPrescriptionDashboardReaderMockRecorder
	isgomock struct{}
}

// MockPrescriptionDashboardReaderMockRecorder is the mock recorder for MockPrescriptionDashboardReader.
type MockPrescriptionDashboardReaderMockRecorder struct {
	mock *MockPrescriptionDashboardReader
}

// NewMockPrescriptionDashboardReader creates a new mock instance.
func NewMockPrescriptionDashboardReader(ctrl *gomock.Controller) *MockPrescriptionDashboardReader {
	mock := &MockPrescriptionDashboardReader{ctrl: ctrl}
	mock.recorder = &MockPrescriptionDashboardReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrescriptionDashboardReader) EXPECT() *MockPrescriptionDashboardReaderMockRecorder {
	return m.recorder
}

// GetTodayPrescriptions mocks base method.
func (m *MockPrescriptionDashboardReader) GetTodayPrescriptions(log *zap.Logger, organisationID string) (dto.TodayPrescriptionsSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTodayPrescriptions", log, organisationID)
	ret0, _ := ret[0].(dto.TodayPrescriptionsSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTodayPrescriptions indicates an expected call of GetTodayPrescriptions.
func (mr *MockPrescriptionDashboardReaderMockRecorder) GetTodayPrescriptions(log, organisationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTodayPrescriptions", reflect.TypeOf((*MockPrescriptionDashboardReader)(nil).GetTodayPrescriptions), log, organisationID)
}
