// Code generated by MockGen. DO NOT EDIT.
// Source: hospital-backend/internal/dashboard (interfaces: AppointmentDashboardReader)
//
// Generated by this command:
//
//	mockgen -destination=internal/dashboard/mocks/mock_appointment_dashboard_reader.go -package=mocks hospital-backend/internal/dashboard AppointmentDashboardReader
//

// Package mocks is a generated GoMock package.
package mocks

import (
	dto "hospital-backend/internal/appointments/dto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	zap "go.uber.org/zap"
)

// MockAppointmentDashboardReader is a mock of AppointmentDashboardReader interface.
type MockAppointmentDashboardReader struct {
	ctrl     *gomock.Controller
	recorder *MockAppointmentDashboardReaderMockRecorder
	isgomock struct{}
}

// MockAppointmentDashboardReaderMockRecorder is the mock recorder for MockAppointmentDashboardReader.
type MockAppointmentDashboardReaderMockRecorder struct {
	mock *MockAppointmentDashboardReader
}

// NewMockAppointmentDashboardReader creates a new mock instance.
func NewMockAppointmentDashboardReader(ctrl *gomock.Controller) *MockAppointmentDashboardReader {
	mock := &MockAppointmentDashboardReader{ctrl: ctrl}
	mock.recorder = &MockAppointmentDashboardReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppointmentDashboardReader) EXPECT() *MockAppointmentDashboardReaderMockRecorder {
	return m.recorder
}

// GetAppointmentsGroupedByStatus mocks base method.
func (m *MockAppointmentDashboardReader) GetAppointmentsGroupedByStatus(log *zap.Logger, organisationID string) (dto.AppointmentStatusCounts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppointmentsGroupedByStatus", log, organisationID)
	ret0, _ := ret[0].(dto.AppointmentStatusCounts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppointmentsGroupedByStatus indicates an expected call of GetAppointmentsGroupedByStatus.
func (mr *MockAppointmentDashboardReaderMockRecorder) GetAppointmentsGroupedByStatus(log, organisationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppointmentsGroupedByStatus", reflect.TypeOf((*MockAppointmentDashboardReader)(nil).GetAppointmentsGroupedByStatus), log, organisationID)
}

// GetTodayLatestAppointments mocks base method.
func (m *MockAppointmentDashboardReader) GetTodayLatestAppointments(log *zap.Logger, organisationID string) ([]dto.AppointmentList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTodayLatestAppointments", log, organisationID)
	ret0, _ := ret[0].([]dto.AppointmentList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTodayLatestAppointments indicates an expected call of GetTodayLatestAppointments.
func (mr *MockAppointmentDashboardReaderMockRecorder) GetTodayLatestAppointments(log, organisationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTodayLatestAppointments", reflect.TypeOf((*MockAppointmentDashboardReader)(nil).GetTodayLatestAppointments), log, organisationID)
}
