// Code generated by MockGen. DO NOT EDIT.
// Source: hospital-backend/internal/dashboard (interfaces: EmployeeDashboardReader)
//
// Generated by this command:
//
//	mockgen -destination=internal/dashboard/mocks/mock_employee_dashboard_reader.go -package=mocks hospital-backend/internal/dashboard EmployeeDashboardReader
//

// Package mocks is a generated GoMock package.
package mocks

import (
	dto "hospital-backend/internal/employee/dto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	zap "go.uber.org/zap"
)

// MockEmployeeDashboardReader is a mock of EmployeeDashboardReader interface.
type MockEmployeeDashboardReader struct {
	ctrl     *gomock.Controller
	recorder *MockEmployeeDashboardReaderMockRecorder
	isgomock struct{}
}

// MockEmployeeDashboardReaderMockRecorder is the mock recorder for MockEmployeeDashboardReader.
type MockEmployeeDashboardReaderMockRecorder struct {
	mock *MockEmployeeDashboardReader
}

// NewMockEmployeeDashboardReader creates a new mock instance.
func NewMockEmployeeDashboardReader(ctrl *gomock.Controller) *MockEmployeeDashboardReader {
	mock := &MockEmployeeDashboardReader{ctrl: ctrl}
	mock.recorder = &MockEmployeeDashboardReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmployeeDashboardReader) EXPECT() *MockEmployeeDashboardReaderMockRecorder {
	return m.recorder
}

// GetEmployeeStatusCounts mocks base method.
func (m *MockEmployeeDashboardReader) GetEmployeeStatusCounts(log *zap.Logger, organisationID string) (dto.EmployeeStatusCounts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeeStatusCounts", log, organisationID)
	ret0, _ := ret[0].(dto.EmployeeStatusCounts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeeStatusCounts indicates an expected call of GetEmployeeStatusCounts.
func (mr *MockEmployeeDashboardReaderMockRecorder) GetEmployeeStatusCounts(log, organisationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeeStatusCounts", reflect.TypeOf((*MockEmployeeDashboardReader)(nil).GetEmployeeStatusCounts), log, organisationID)
}
