// Code generated by MockGen. DO NOT EDIT.
// Source: hospital-backend/internal/dashboard (interfaces: BillingDashboardReader)
//
// Generated by this command:
//
//	mockgen -destination=internal/dashboard/mocks/mock_billing_dashboard_reader.go -package=mocks hospital-backend/internal/dashboard BillingDashboardReader
//

// Package mocks is a generated GoMock package.
package mocks

import (
	dto "hospital-backend/internal/billing/dto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	zap "go.uber.org/zap"
)

// MockBillingDashboardReader is a mock of BillingDashboardReader interface.
type MockBillingDashboardReader struct {
	ctrl     *gomock.Controller
	recorder *MockBillingDashboardReaderMockRecorder
	isgomock struct{}
}

// MockBillingDashboardReaderMockRecorder is the mock recorder for MockBillingDashboardReader.
type MockBillingDashboardReaderMockRecorder struct {
	mock *MockBillingDashboardReader
}

// NewMockBillingDashboardReader creates a new mock instance.
func NewMockBillingDashboardReader(ctrl *gomock.Controller) *MockBillingDashboardReader {
	mock := &MockBillingDashboardReader{ctrl: ctrl}
	mock.recorder = &MockBillingDashboardReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBillingDashboardReader) EXPECT() *MockBillingDashboardReaderMockRecorder {
	return m.recorder
}

// GetTodayCompletedInvoiceSummary mocks base method.
func (m *MockBillingDashboardReader) GetTodayCompletedInvoiceSummary(log *zap.Logger, organisationID string) (dto.TodayInvoiceCollectionSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTodayCompletedInvoiceSummary", log, organisationID)
	ret0, _ := ret[0].(dto.TodayInvoiceCollectionSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTodayCompletedInvoiceSummary indicates an expected call of GetTodayCompletedInvoiceSummary.
func (mr *MockBillingDashboardReaderMockRecorder) GetTodayCompletedInvoiceSummary(log, organisationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTodayCompletedInvoiceSummary", reflect.TypeOf((*MockBillingDashboardReader)(nil).GetTodayCompletedInvoiceSummary), log, organisationID)
}
