// Code generated by MockGen. DO NOT EDIT.
// Source: hospital-backend/internal/patient (interfaces: PatientServicer)
//
// Generated by this command:
//
//	mockgen -destination=internal/patient/mocks/mock_patient_servicer.go -package=mocks hospital-backend/internal/patient PatientServicer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	dto "hospital-backend/internal/patient/dto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	zap "go.uber.org/zap"
)

// MockPatientServicer is a mock of PatientServicer interface.
type MockPatientServicer struct {
	ctrl     *gomock.Controller
	recorder *MockPatientServicerMockRecorder
	isgomock struct{}
}

// MockPatientServicerMockRecorder is the mock recorder for MockPatientServicer.
type MockPatientServicerMockRecorder struct {
	mock *MockPatientServicer
}

// NewMockPatientServicer creates a new mock instance.
func NewMockPatientServicer(ctrl *gomock.Controller) *MockPatientServicer {
	mock := &MockPatientServicer{ctrl: ctrl}
	mock.recorder = &MockPatientServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPatientServicer) EXPECT() *MockPatientServicerMockRecorder {
	return m.recorder
}

// CreatePatientSrv mocks base method.
func (m *MockPatientServicer) CreatePatientSrv(log *zap.Logger, payload dto.PatientInfo) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePatientSrv", log, payload)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePatientSrv indicates an expected call of CreatePatientSrv.
func (mr *MockPatientServicerMockRecorder) CreatePatientSrv(log, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePatientSrv", reflect.TypeOf((*MockPatientServicer)(nil).CreatePatientSrv), log, payload)
}

// FindMany mocks base method.
func (m *MockPatientServicer) FindMany(log *zap.Logger, req dto.PatientListReq) ([]dto.PatientResponse, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMany", log, req)
	ret0, _ := ret[0].([]dto.PatientResponse)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindMany indicates an expected call of FindMany.
func (mr *MockPatientServicerMockRecorder) FindMany(log, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMany", reflect.TypeOf((*MockPatientServicer)(nil).FindMany), log, req)
}

// FindOne mocks base method.
func (m *MockPatientServicer) FindOne(log *zap.Logger, id string) (dto.PatientResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", log, id)
	ret0, _ := ret[0].(dto.PatientResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockPatientServicerMockRecorder) FindOne(log, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockPatientServicer)(nil).FindOne), log, id)
}
