// Code generated by MockGen. DO NOT EDIT.
// Source: hospital-backend/internal/patient (interfaces: PatientRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/patient/mocks/mock_patient_repository.go -package=mocks hospital-backend/internal/patient PatientRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	patient "hospital-backend/internal/patient"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	zap "go.uber.org/zap"
)

// MockPatientRepository is a mock of PatientRepository interface.
type MockPatientRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPatientRepositoryMockRecorder
	isgomock struct{}
}

// MockPatientRepositoryMockRecorder is the mock recorder for MockPatientRepository.
type MockPatientRepositoryMockRecorder struct {
	mock *MockPatientRepository
}

// NewMockPatientRepository creates a new mock instance.
func NewMockPatientRepository(ctrl *gomock.Controller) *MockPatientRepository {
	mock := &MockPatientRepository{ctrl: ctrl}
	mock.recorder = &MockPatientRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPatientRepository) EXPECT() *MockPatientRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockPatientRepository) Count(log *zap.Logger, query string, args ...any) (int64, error) {
	m.ctrl.T.Helper()
	varargs := []any{log, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Count", varargs...)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockPatientRepositoryMockRecorder) Count(log, query any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{log, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockPatientRepository)(nil).Count), varargs...)
}

// Create mocks base method.
func (m *MockPatientRepository) Create(log *zap.Logger, record *patient.Patient) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", log, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPatientRepositoryMockRecorder) Create(log, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPatientRepository)(nil).Create), log, record)
}

// ReadMany mocks base method.
func (m *MockPatientRepository) ReadMany(log *zap.Logger, query string, args ...any) ([]patient.Patient, error) {
	m.ctrl.T.Helper()
	varargs := []any{log, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ReadMany", varargs...)
	ret0, _ := ret[0].([]patient.Patient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadMany indicates an expected call of ReadMany.
func (mr *MockPatientRepositoryMockRecorder) ReadMany(log, query any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{log, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadMany", reflect.TypeOf((*MockPatientRepository)(nil).ReadMany), varargs...)
}

// ReadOne mocks base method.
func (m *MockPatientRepository) ReadOne(log *zap.Logger, patientID string) (patient.Patient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadOne", log, patientID)
	ret0, _ := ret[0].(patient.Patient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadOne indicates an expected call of ReadOne.
func (mr *MockPatientRepositoryMockRecorder) ReadOne(log, patientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadOne", reflect.TypeOf((*MockPatientRepository)(nil).ReadOne), log, patientID)
}

// ReadOneWithOrganisationID mocks base method.
func (m *MockPatientRepository) ReadOneWithOrganisationID(log *zap.Logger, query string, args ...any) (map[string]any, error) {
	m.ctrl.T.Helper()
	varargs := []any{log, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ReadOneWithOrganisationID", varargs...)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadOneWithOrganisationID indicates an expected call of ReadOneWithOrganisationID.
func (mr *MockPatientRepositoryMockRecorder) ReadOneWithOrganisationID(log, query any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{log, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadOneWithOrganisationID", reflect.TypeOf((*MockPatientRepository)(nil).ReadOneWithOrganisationID), varargs...)
}
