// Code generated by MockGen. DO NOT EDIT.
// Source: hospital-backend/internal/bedmanagement/repository (interfaces: BedRepository,BedAllotmentRepository,RoomRepository,RoomTypeRepository,RoomSummaryRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/bedmanagement/mocks/mock_bedmanagement_repository.go -package=mocks hospital-backend/internal/bedmanagement/repository BedRepository,BedAllotmentRepository,RoomRepository,RoomTypeRepository,RoomSummaryRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "hospital-backend/internal/bedmanagement/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockBedRepository is a mock of BedRepository interface.
type MockBedRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBedRepositoryMockRecorder
	isgomock struct{}
}

// MockBedRepositoryMockRecorder is the mock recorder for MockBedRepository.
type MockBedRepositoryMockRecorder struct {
	mock *MockBedRepository
}

// NewMockBedRepository creates a new mock instance.
func NewMockBedRepository(ctrl *gomock.Controller) *MockBedRepository {
	mock := &MockBedRepository{ctrl: ctrl}
	mock.recorder = &MockBedRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBedRepository) EXPECT() *MockBedRepositoryMockRecorder {
	return m.recorder
}

// CreateBatch mocks base method.
func (m *MockBedRepository) CreateBatch(db *gorm.DB, bed *models.Bed) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatch", db, bed)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBatch indicates an expected call of CreateBatch.
func (mr *MockBedRepositoryMockRecorder) CreateBatch(db, bed any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatch", reflect.TypeOf((*MockBedRepository)(nil).CreateBatch), db, bed)
}

// FindAllAvailableBeds mocks base method.
func (m *MockBedRepository) FindAllAvailableBeds(organisationID string, limit, offset int) ([]models.Bed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllAvailableBeds", organisationID, limit, offset)
	ret0, _ := ret[0].([]models.Bed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllAvailableBeds indicates an expected call of FindAllAvailableBeds.
func (mr *MockBedRepositoryMockRecorder) FindAllAvailableBeds(organisationID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllAvailableBeds", reflect.TypeOf((*MockBedRepository)(nil).FindAllAvailableBeds), organisationID, limit, offset)
}

// MockBedAllotmentRepository is a mock of BedAllotmentRepository interface.
type MockBedAllotmentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBedAllotmentRepositoryMockRecorder
	isgomock struct{}
}

// MockBedAllotmentRepositoryMockRecorder is the mock recorder for MockBedAllotmentRepository.
type MockBedAllotmentRepositoryMockRecorder struct {
	mock *MockBedAllotmentRepository
}

// NewMockBedAllotmentRepository creates a new mock instance.
func NewMockBedAllotmentRepository(ctrl *gomock.Controller) *MockBedAllotmentRepository {
	mock := &MockBedAllotmentRepository{ctrl: ctrl}
	mock.recorder = &MockBedAllotmentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBedAllotmentRepository) EXPECT() *MockBedAllotmentRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBedAllotmentRepository) Create(bedAllotment *models.BedAllotment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", bedAllotment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBedAllotmentRepositoryMockRecorder) Create(bedAllotment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBedAllotmentRepository)(nil).Create), bedAllotment)
}

// MockRoomRepository is a mock of RoomRepository interface.
type MockRoomRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRoomRepositoryMockRecorder
	isgomock struct{}
}

// MockRoomRepositoryMockRecorder is the mock recorder for MockRoomRepository.
type MockRoomRepositoryMockRecorder struct {
	mock *MockRoomRepository
}

// NewMockRoomRepository creates a new mock instance.
func NewMockRoomRepository(ctrl *gomock.Controller) *MockRoomRepository {
	mock := &MockRoomRepository{ctrl: ctrl}
	mock.recorder = &MockRoomRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomRepository) EXPECT() *MockRoomRepositoryMockRecorder {
	return m.recorder
}

// CreateBatch mocks base method.
func (m *MockRoomRepository) CreateBatch(tx *gorm.DB, room *[]models.Room) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatch", tx, room)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBatch indicates an expected call of CreateBatch.
func (mr *MockRoomRepositoryMockRecorder) CreateBatch(tx, room any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatch", reflect.TypeOf((*MockRoomRepository)(nil).CreateBatch), tx, room)
}

// FindAllAvailableRooms mocks base method.
func (m *MockRoomRepository) FindAllAvailableRooms(organisationID string, limit, offset int) ([]models.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllAvailableRooms", organisationID, limit, offset)
	ret0, _ := ret[0].([]models.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllAvailableRooms indicates an expected call of FindAllAvailableRooms.
func (mr *MockRoomRepositoryMockRecorder) FindAllAvailableRooms(organisationID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllAvailableRooms", reflect.TypeOf((*MockRoomRepository)(nil).FindAllAvailableRooms), organisationID, limit, offset)
}

// GetRoomByID mocks base method.
func (m *MockRoomRepository) GetRoomByID(roomID string) (*models.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoomByID", roomID)
	ret0, _ := ret[0].(*models.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoomByID indicates an expected call of GetRoomByID.
func (mr *MockRoomRepositoryMockRecorder) GetRoomByID(roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoomByID", reflect.TypeOf((*MockRoomRepository)(nil).GetRoomByID), roomID)
}

// MockRoomTypeRepository is a mock of RoomTypeRepository interface.
type MockRoomTypeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRoomTypeRepositoryMockRecorder
	isgomock struct{}
}

// MockRoomTypeRepositoryMockRecorder is the mock recorder for MockRoomTypeRepository.
type MockRoomTypeRepositoryMockRecorder struct {
	mock *MockRoomTypeRepository
}

// NewMockRoomTypeRepository creates a new mock instance.
func NewMockRoomTypeRepository(ctrl *gomock.Controller) *MockRoomTypeRepository {
	mock := &MockRoomTypeRepository{ctrl: ctrl}
	mock.recorder = &MockRoomTypeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomTypeRepository) EXPECT() *MockRoomTypeRepositoryMockRecorder {
	return m.recorder
}

// CheckRoomType mocks base method.
func (m *MockRoomTypeRepository) CheckRoomType(roomType *models.RoomType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckRoomType", roomType)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckRoomType indicates an expected call of CheckRoomType.
func (mr *MockRoomTypeRepositoryMockRecorder) CheckRoomType(roomType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckRoomType", reflect.TypeOf((*MockRoomTypeRepository)(nil).CheckRoomType), roomType)
}

// Create mocks base method.
func (m *MockRoomTypeRepository) Create(roomType *models.RoomType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", roomType)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRoomTypeRepositoryMockRecorder) Create(roomType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRoomTypeRepository)(nil).Create), roomType)
}

// FindAllRoomTypes mocks base method.
func (m *MockRoomTypeRepository) FindAllRoomTypes(organisationID string) ([]models.RoomType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllRoomTypes", organisationID)
	ret0, _ := ret[0].([]models.RoomType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllRoomTypes indicates an expected call of FindAllRoomTypes.
func (mr *MockRoomTypeRepositoryMockRecorder) FindAllRoomTypes(organisationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllRoomTypes", reflect.TypeOf((*MockRoomTypeRepository)(nil).FindAllRoomTypes), organisationID)
}

// GetRoomTypeData mocks base method.
func (m *MockRoomTypeRepository) GetRoomTypeData(roomTypeId string) (models.RoomType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoomTypeData", roomTypeId)
	ret0, _ := ret[0].(models.RoomType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoomTypeData indicates an expected call of GetRoomTypeData.
func (mr *MockRoomTypeRepositoryMockRecorder) GetRoomTypeData(roomTypeId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoomTypeData", reflect.TypeOf((*MockRoomTypeRepository)(nil).GetRoomTypeData), roomTypeId)
}

// MockRoomSummaryRepository is a mock of RoomSummaryRepository interface.
type MockRoomSummaryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRoomSummaryRepositoryMockRecorder
	isgomock struct{}
}

// MockRoomSummaryRepositoryMockRecorder is the mock recorder for MockRoomSummaryRepository.
type MockRoomSummaryRepositoryMockRecorder struct {
	mock *MockRoomSummaryRepository
}

// NewMockRoomSummaryRepository creates a new mock instance.
func NewMockRoomSummaryRepository(ctrl *gomock.Controller) *MockRoomSummaryRepository {
	mock := &MockRoomSummaryRepository{ctrl: ctrl}
	mock.recorder = &MockRoomSummaryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomSummaryRepository) EXPECT() *MockRoomSummaryRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRoomSummaryRepository) Create(roomSummary *models.RoomSummary) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", roomSummary)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRoomSummaryRepositoryMockRecorder) Create(roomSummary any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRoomSummaryRepository)(nil).Create), roomSummary)
}

// GetRoomSummaryByRoomType mocks base method.
func (m *MockRoomSummaryRepository) GetRoomSummaryByRoomType(roomTypeID string) (*models.RoomSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoomSummaryByRoomType", roomTypeID)
	ret0, _ := ret[0].(*models.RoomSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoomSummaryByRoomType indicates an expected call of GetRoomSummaryByRoomType.
func (mr *MockRoomSummaryRepositoryMockRecorder) GetRoomSummaryByRoomType(roomTypeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoomSummaryByRoomType", reflect.TypeOf((*MockRoomSummaryRepository)(nil).GetRoomSummaryByRoomType), roomTypeID)
}

// Update mocks base method.
func (m *MockRoomSummaryRepository) Update(roomSummary *models.RoomSummary) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", roomSummary)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRoomSummaryRepositoryMockRecorder) Update(roomSummary any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRoomSummaryRepository)(nil).Update), roomSummary)
}
