// Code generated by MockGen. DO NOT EDIT.
// Source: hospital-backend/internal/department (interfaces: DepartmentServicer)
//
// Generated by this command:
//
//	mockgen -destination=internal/department/mocks/mock_department_servicer.go -package=mocks hospital-backend/internal/department DepartmentServicer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	department "hospital-backend/internal/department"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDepartmentServicer is a mock of DepartmentServicer interface.
type MockDepartmentServicer struct {
	ctrl     *gomock.Controller
	recorder *MockDepartmentServicerMockRecorder
	isgomock struct{}
}

// MockDepartmentServicerMockRecorder is the mock recorder for MockDepartmentServicer.
type MockDepartmentServicerMockRecorder struct {
	mock *MockDepartmentServicer
}

// NewMockDepartmentServicer creates a new mock instance.
func NewMockDepartmentServicer(ctrl *gomock.Controller) *MockDepartmentServicer {
	mock := &MockDepartmentServicer{ctrl: ctrl}
	mock.recorder = &MockDepartmentServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDepartmentServicer) EXPECT() *MockDepartmentServicerMockRecorder {
	return m.recorder
}

// FindMany mocks base method.
func (m *MockDepartmentServicer) FindMany(organisationID string, limit, skip int) ([]department.Department, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMany", organisationID, limit, skip)
	ret0, _ := ret[0].([]department.Department)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindMany indicates an expected call of FindMany.
func (mr *MockDepartmentServicerMockRecorder) FindMany(organisationID, limit, skip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMany", reflect.TypeOf((*MockDepartmentServicer)(nil).FindMany), organisationID, limit, skip)
}
