// Code generated by MockGen. DO NOT EDIT.
// Source: hospital-backend/internal/employee (interfaces: EmployeeServicer)
//
// Generated by this command:
//
//	mockgen -destination=internal/employee/mocks/mock_employee_servicer.go -package=mocks hospital-backend/internal/employee EmployeeServicer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	dto "hospital-backend/internal/employee/dto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	zap "go.uber.org/zap"
)

// MockEmployeeServicer is a mock of EmployeeServicer interface.
type MockEmployeeServicer struct {
	ctrl     *gomock.Controller
	recorder *MockEmployeeServicerMockRecorder
	isgomock struct{}
}

// MockEmployeeServicerMockRecorder is the mock recorder for MockEmployeeServicer.
type MockEmployeeServicerMockRecorder struct {
	mock *MockEmployeeServicer
}

// NewMockEmployeeServicer creates a new mock instance.
func NewMockEmployeeServicer(ctrl *gomock.Controller) *MockEmployeeServicer {
	mock := &MockEmployeeServicer{ctrl: ctrl}
	mock.recorder = &MockEmployeeServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmployeeServicer) EXPECT() *MockEmployeeServicerMockRecorder {
	return m.recorder
}

// CreateAdminProf mocks base method.
func (m *MockEmployeeServicer) CreateAdminProf(log *zap.Logger, payload dto.EmpRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAdminProf", log, payload)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAdminProf indicates an expected call of CreateAdminProf.
func (mr *MockEmployeeServicerMockRecorder) CreateAdminProf(log, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAdminProf", reflect.TypeOf((*MockEmployeeServicer)(nil).CreateAdminProf), log, payload)
}

// CreateEmployee mocks base method.
func (m *MockEmployeeServicer) CreateEmployee(log *zap.Logger, payload dto.EmpRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEmployee", log, payload)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEmployee indicates an expected call of CreateEmployee.
func (mr *MockEmployeeServicerMockRecorder) CreateEmployee(log, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEmployee", reflect.TypeOf((*MockEmployeeServicer)(nil).CreateEmployee), log, payload)
}

// DeleteEmployee mocks base method.
func (m *MockEmployeeServicer) DeleteEmployee(log *zap.Logger, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEmployee", log, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEmployee indicates an expected call of DeleteEmployee.
func (mr *MockEmployeeServicerMockRecorder) DeleteEmployee(log, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEmployee", reflect.TypeOf((*MockEmployeeServicer)(nil).DeleteEmployee), log, userID)
}

// FindDoctors mocks base method.
func (m *MockEmployeeServicer) FindDoctors(log *zap.Logger, search, organisationID string) ([]dto.Doctor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDoctors", log, search, organisationID)
	ret0, _ := ret[0].([]dto.Doctor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDoctors indicates an expected call of FindDoctors.
func (mr *MockEmployeeServicerMockRecorder) FindDoctors(log, search, organisationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDoctors", reflect.TypeOf((*MockEmployeeServicer)(nil).FindDoctors), log, search, organisationID)
}

// FindMany mocks base method.
func (m *MockEmployeeServicer) FindMany(log *zap.Logger, req dto.FindManyRequest) ([]dto.EmployeeResponse, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMany", log, req)
	ret0, _ := ret[0].([]dto.EmployeeResponse)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindMany indicates an expected call of FindMany.
func (mr *MockEmployeeServicerMockRecorder) FindMany(log, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMany", reflect.TypeOf((*MockEmployeeServicer)(nil).FindMany), log, req)
}

// FindOne mocks base method.
func (m *MockEmployeeServicer) FindOne(log *zap.Logger, id string) (dto.EmployeeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", log, id)
	ret0, _ := ret[0].(dto.EmployeeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockEmployeeServicerMockRecorder) FindOne(log, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockEmployeeServicer)(nil).FindOne), log, id)
}

// UpdateAdminProf mocks base method.
func (m *MockEmployeeServicer) UpdateAdminProf(log *zap.Logger, payload dto.UpdateRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAdminProf", log, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAdminProf indicates an expected call of UpdateAdminProf.
func (mr *MockEmployeeServicerMockRecorder) UpdateAdminProf(log, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAdminProf", reflect.TypeOf((*MockEmployeeServicer)(nil).UpdateAdminProf), log, payload)
}
