// Code generated by MockGen. DO NOT EDIT.
// Source: hospital-backend/internal/employee (interfaces: EmployeeRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/employee/mocks/mock_employee_repository.go -package=mocks hospital-backend/internal/employee EmployeeRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	employee "hospital-backend/internal/employee"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEmployeeRepository is a mock of EmployeeRepository interface.
type MockEmployeeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEmployeeRepositoryMockRecorder
	isgomock struct{}
}

// MockEmployeeRepositoryMockRecorder is the mock recorder for MockEmployeeRepository.
type MockEmployeeRepositoryMockRecorder struct {
	mock *MockEmployeeRepository
}

// NewMockEmployeeRepository creates a new mock instance.
func NewMockEmployeeRepository(ctrl *gomock.Controller) *MockEmployeeRepository {
	mock := &MockEmployeeRepository{ctrl: ctrl}
	mock.recorder = &MockEmployeeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmployeeRepository) EXPECT() *MockEmployeeRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockEmployeeRepository) Count(organisationID, search string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", organisationID, search)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockEmployeeRepositoryMockRecorder) Count(organisationID, search any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockEmployeeRepository)(nil).Count), organisationID, search)
}

// CountByActiveStatus mocks base method.
func (m *MockEmployeeRepository) CountByActiveStatus(organisationID string) (employee.EmployeeStatusCountRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByActiveStatus", organisationID)
	ret0, _ := ret[0].(employee.EmployeeStatusCountRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByActiveStatus indicates an expected call of CountByActiveStatus.
func (mr *MockEmployeeRepositoryMockRecorder) CountByActiveStatus(organisationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByActiveStatus", reflect.TypeOf((*MockEmployeeRepository)(nil).CountByActiveStatus), organisationID)
}

// CountByCodePrefix mocks base method.
func (m *MockEmployeeRepository) CountByCodePrefix(organisationID, prefix string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByCodePrefix", organisationID, prefix)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByCodePrefix indicates an expected call of CountByCodePrefix.
func (mr *MockEmployeeRepositoryMockRecorder) CountByCodePrefix(organisationID, prefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByCodePrefix", reflect.TypeOf((*MockEmployeeRepository)(nil).CountByCodePrefix), organisationID, prefix)
}

// Create mocks base method.
func (m *MockEmployeeRepository) Create(arg0 *employee.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockEmployeeRepositoryMockRecorder) Create(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEmployeeRepository)(nil).Create), arg0)
}

// DeleteOne mocks base method.
func (m *MockEmployeeRepository) DeleteOne(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOne", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOne indicates an expected call of DeleteOne.
func (mr *MockEmployeeRepositoryMockRecorder) DeleteOne(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOne", reflect.TypeOf((*MockEmployeeRepository)(nil).DeleteOne), arg0)
}

// FindRoleIDByUserID mocks base method.
func (m *MockEmployeeRepository) FindRoleIDByUserID(userID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRoleIDByUserID", userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRoleIDByUserID indicates an expected call of FindRoleIDByUserID.
func (mr *MockEmployeeRepositoryMockRecorder) FindRoleIDByUserID(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRoleIDByUserID", reflect.TypeOf((*MockEmployeeRepository)(nil).FindRoleIDByUserID), userID)
}

// ReadDoctors mocks base method.
func (m *MockEmployeeRepository) ReadDoctors(query string, args ...any) ([]employee.User, error) {
	m.ctrl.T.Helper()
	varargs := []any{query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ReadDoctors", varargs...)
	ret0, _ := ret[0].([]employee.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadDoctors indicates an expected call of ReadDoctors.
func (mr *MockEmployeeRepositoryMockRecorder) ReadDoctors(query any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadDoctors", reflect.TypeOf((*MockEmployeeRepository)(nil).ReadDoctors), varargs...)
}

// ReadMany mocks base method.
func (m *MockEmployeeRepository) ReadMany(limit, skip int, organisationID, search string) ([]employee.EmployeeListRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadMany", limit, skip, organisationID, search)
	ret0, _ := ret[0].([]employee.EmployeeListRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadMany indicates an expected call of ReadMany.
func (mr *MockEmployeeRepositoryMockRecorder) ReadMany(limit, skip, organisationID, search any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadMany", reflect.TypeOf((*MockEmployeeRepository)(nil).ReadMany), limit, skip, organisationID, search)
}

// ReadOne mocks base method.
func (m *MockEmployeeRepository) ReadOne(id string) (*employee.EmployeeListRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadOne", id)
	ret0, _ := ret[0].(*employee.EmployeeListRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadOne indicates an expected call of ReadOne.
func (mr *MockEmployeeRepositoryMockRecorder) ReadOne(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadOne", reflect.TypeOf((*MockEmployeeRepository)(nil).ReadOne), id)
}

// Update mocks base method.
func (m *MockEmployeeRepository) Update(arg0 string, arg1 map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockEmployeeRepositoryMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockEmployeeRepository)(nil).Update), arg0, arg1)
}
