// Code generated by MockGen. DO NOT EDIT.
// Source: hospital-backend/internal/authentication (interfaces: RolePermissionServicer)
//
// Generated by this command:
//
//	mockgen -destination=internal/authentication/mocks/mock_role_permission_servicer.go -package=mocks hospital-backend/internal/authentication RolePermissionServicer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	dto "hospital-backend/internal/rolepermissions/dto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRolePermissionServicer is a mock of RolePermissionServicer interface.
type MockRolePermissionServicer struct {
	ctrl     *gomock.Controller
	recorder *MockRolePermissionServicerMockRecorder
	isgomock struct{}
}

// MockRolePermissionServicerMockRecorder is the mock recorder for MockRolePermissionServicer.
type MockRolePermissionServicerMockRecorder struct {
	mock *MockRolePermissionServicer
}

// NewMockRolePermissionServicer creates a new mock instance.
func NewMockRolePermissionServicer(ctrl *gomock.Controller) *MockRolePermissionServicer {
	mock := &MockRolePermissionServicer{ctrl: ctrl}
	mock.recorder = &MockRolePermissionServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRolePermissionServicer) EXPECT() *MockRolePermissionServicerMockRecorder {
	return m.recorder
}

// FindModulesByRoleID mocks base method.
func (m *MockRolePermissionServicer) FindModulesByRoleID(roleID string) (dto.RoleAccess, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindModulesByRoleID", roleID)
	ret0, _ := ret[0].(dto.RoleAccess)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindModulesByRoleID indicates an expected call of FindModulesByRoleID.
func (mr *MockRolePermissionServicerMockRecorder) FindModulesByRoleID(roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindModulesByRoleID", reflect.TypeOf((*MockRolePermissionServicer)(nil).FindModulesByRoleID), roleID)
}
