// Code generated by MockGen. DO NOT EDIT.
// Source: hospital-backend/internal/authentication (interfaces: NotificationEnqueuer)
//
// Generated by this command:
//
//	mockgen -destination=internal/authentication/mocks/mock_notification_enqueuer.go -package=mocks hospital-backend/internal/authentication NotificationEnqueuer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	dto "hospital-backend/internal/notifications/dto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockNotificationEnqueuer is a mock of NotificationEnqueuer interface.
type MockNotificationEnqueuer struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationEnqueuerMockRecorder
	isgomock struct{}
}

// MockNotificationEnqueuerMockRecorder is the mock recorder for MockNotificationEnqueuer.
type MockNotificationEnqueuerMockRecorder struct {
	mock *MockNotificationEnqueuer
}

// NewMockNotificationEnqueuer creates a new mock instance.
func NewMockNotificationEnqueuer(ctrl *gomock.Controller) *MockNotificationEnqueuer {
	mock := &MockNotificationEnqueuer{ctrl: ctrl}
	mock.recorder = &MockNotificationEnqueuerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationEnqueuer) EXPECT() *MockNotificationEnqueuerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockNotificationEnqueuer) Create(ctx context.Context, data dto.CreateRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockNotificationEnqueuerMockRecorder) Create(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNotificationEnqueuer)(nil).Create), ctx, data)
}
