// Code generated by MockGen. DO NOT EDIT.
// Source: hospital-backend/internal/authentication (interfaces: JwtServicer)
//
// Generated by this command:
//
//	mockgen -destination=internal/authentication/mocks/mock_jwt_servicer.go -package=mocks hospital-backend/internal/authentication JwtServicer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	jwt "hospital-backend/internal/jwt"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
	zap "go.uber.org/zap"
)

// MockJwtServicer is a mock of JwtServicer interface.
type MockJwtServicer struct {
	ctrl     *gomock.Controller
	recorder *MockJwtServicerMockRecorder
	isgomock struct{}
}

// MockJwtServicerMockRecorder is the mock recorder for MockJwtServicer.
type MockJwtServicerMockRecorder struct {
	mock *MockJwtServicer
}

// NewMockJwtServicer creates a new mock instance.
func NewMockJwtServicer(ctrl *gomock.Controller) *MockJwtServicer {
	mock := &MockJwtServicer{ctrl: ctrl}
	mock.recorder = &MockJwtServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJwtServicer) EXPECT() *MockJwtServicerMockRecorder {
	return m.recorder
}

// AccessToken mocks base method.
func (m *MockJwtServicer) AccessToken(userID, organisationID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccessToken", userID, organisationID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AccessToken indicates an expected call of AccessToken.
func (mr *MockJwtServicerMockRecorder) AccessToken(userID, organisationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccessToken", reflect.TypeOf((*MockJwtServicer)(nil).AccessToken), userID, organisationID)
}

// FindIDByUserID mocks base method.
func (m *MockJwtServicer) FindIDByUserID(userID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindIDByUserID", userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindIDByUserID indicates an expected call of FindIDByUserID.
func (mr *MockJwtServicerMockRecorder) FindIDByUserID(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindIDByUserID", reflect.TypeOf((*MockJwtServicer)(nil).FindIDByUserID), userID)
}

// InsertRefreshToken mocks base method.
func (m *MockJwtServicer) InsertRefreshToken(token string, expiry time.Time, userID, refreshID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertRefreshToken", token, expiry, userID, refreshID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertRefreshToken indicates an expected call of InsertRefreshToken.
func (mr *MockJwtServicerMockRecorder) InsertRefreshToken(token, expiry, userID, refreshID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertRefreshToken", reflect.TypeOf((*MockJwtServicer)(nil).InsertRefreshToken), token, expiry, userID, refreshID)
}

// LogoutRefreshToken mocks base method.
func (m *MockJwtServicer) LogoutRefreshToken(log *zap.Logger, refreshToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogoutRefreshToken", log, refreshToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogoutRefreshToken indicates an expected call of LogoutRefreshToken.
func (mr *MockJwtServicerMockRecorder) LogoutRefreshToken(log, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogoutRefreshToken", reflect.TypeOf((*MockJwtServicer)(nil).LogoutRefreshToken), log, refreshToken)
}

// RefreshToken mocks base method.
func (m *MockJwtServicer) RefreshToken(organisationID, userID, refreshID string) (jwt.Claims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", organisationID, userID, refreshID)
	ret0, _ := ret[0].(jwt.Claims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockJwtServicerMockRecorder) RefreshToken(organisationID, userID, refreshID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockJwtServicer)(nil).RefreshToken), organisationID, userID, refreshID)
}

// UpdateRefreshToken mocks base method.
func (m *MockJwtServicer) UpdateRefreshToken(refreshID, userID, organisationID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRefreshToken", refreshID, userID, organisationID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRefreshToken indicates an expected call of UpdateRefreshToken.
func (mr *MockJwtServicerMockRecorder) UpdateRefreshToken(refreshID, userID, organisationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRefreshToken", reflect.TypeOf((*MockJwtServicer)(nil).UpdateRefreshToken), refreshID, userID, organisationID)
}

// ValidateRefreshToken mocks base method.
func (m *MockJwtServicer) ValidateRefreshToken(log *zap.Logger, token string) (jwt.TokenResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateRefreshToken", log, token)
	ret0, _ := ret[0].(jwt.TokenResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateRefreshToken indicates an expected call of ValidateRefreshToken.
func (mr *MockJwtServicerMockRecorder) ValidateRefreshToken(log, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateRefreshToken", reflect.TypeOf((*MockJwtServicer)(nil).ValidateRefreshToken), log, token)
}
