// Code generated by MockGen. DO NOT EDIT.
// Source: hospital-backend/internal/authentication (interfaces: AuthServicer)
//
// Generated by this command:
//
//	mockgen -destination=internal/authentication/mocks/mock_auth_servicer.go -package=mocks hospital-backend/internal/authentication AuthServicer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	dto "hospital-backend/internal/authentication/dto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	zap "go.uber.org/zap"
)

// MockAuthServicer is a mock of AuthServicer interface.
type MockAuthServicer struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServicerMockRecorder
	isgomock struct{}
}

// MockAuthServicerMockRecorder is the mock recorder for MockAuthServicer.
type MockAuthServicerMockRecorder struct {
	mock *MockAuthServicer
}

// NewMockAuthServicer creates a new mock instance.
func NewMockAuthServicer(ctrl *gomock.Controller) *MockAuthServicer {
	mock := &MockAuthServicer{ctrl: ctrl}
	mock.recorder = &MockAuthServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthServicer) EXPECT() *MockAuthServicerMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockAuthServicer) Login(log *zap.Logger, req dto.LoginUser) (dto.LoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", log, req)
	ret0, _ := ret[0].(dto.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAuthServicerMockRecorder) Login(log, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthServicer)(nil).Login), log, req)
}

// Logout mocks base method.
func (m *MockAuthServicer) Logout(log *zap.Logger, refreshToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", log, refreshToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthServicerMockRecorder) Logout(log, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthServicer)(nil).Logout), log, refreshToken)
}

// RefreshToken mocks base method.
func (m *MockAuthServicer) RefreshToken(log *zap.Logger, refreshToken string) (dto.LoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", log, refreshToken)
	ret0, _ := ret[0].(dto.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockAuthServicerMockRecorder) RefreshToken(log, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockAuthServicer)(nil).RefreshToken), log, refreshToken)
}

// RequestPasswordReset mocks base method.
func (m *MockAuthServicer) RequestPasswordReset(log *zap.Logger, emailID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestPasswordReset", log, emailID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequestPasswordReset indicates an expected call of RequestPasswordReset.
func (mr *MockAuthServicerMockRecorder) RequestPasswordReset(log, emailID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestPasswordReset", reflect.TypeOf((*MockAuthServicer)(nil).RequestPasswordReset), log, emailID)
}

// UpdatePassword mocks base method.
func (m *MockAuthServicer) UpdatePassword(log *zap.Logger, req dto.UpdatePasswordRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", log, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockAuthServicerMockRecorder) UpdatePassword(log, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockAuthServicer)(nil).UpdatePassword), log, req)
}

// UpdatePasswordFirstLogin mocks base method.
func (m *MockAuthServicer) UpdatePasswordFirstLogin(log *zap.Logger, userID string, req dto.FirstLoginPasswordRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePasswordFirstLogin", log, userID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePasswordFirstLogin indicates an expected call of UpdatePasswordFirstLogin.
func (mr *MockAuthServicerMockRecorder) UpdatePasswordFirstLogin(log, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePasswordFirstLogin", reflect.TypeOf((*MockAuthServicer)(nil).UpdatePasswordFirstLogin), log, userID, req)
}
