// Code generated by MockGen. DO NOT EDIT.
// Source: hospital-backend/internal/authentication (interfaces: UserRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/authentication/mocks/mock_user_repository.go -package=mocks hospital-backend/internal/authentication UserRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	employee "hospital-backend/internal/employee"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	zap "go.uber.org/zap"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// ClearTempPassword mocks base method.
func (m *MockUserRepository) ClearTempPassword(log *zap.Logger, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearTempPassword", log, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearTempPassword indicates an expected call of ClearTempPassword.
func (mr *MockUserRepositoryMockRecorder) ClearTempPassword(log, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearTempPassword", reflect.TypeOf((*MockUserRepository)(nil).ClearTempPassword), log, userID)
}

// GetUserID mocks base method.
func (m *MockUserRepository) GetUserID(log *zap.Logger, username string) (*employee.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserID", log, username)
	ret0, _ := ret[0].(*employee.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserID indicates an expected call of GetUserID.
func (mr *MockUserRepositoryMockRecorder) GetUserID(log, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserID", reflect.TypeOf((*MockUserRepository)(nil).GetUserID), log, username)
}

// UpdateLastLoginAttempt mocks base method.
func (m *MockUserRepository) UpdateLastLoginAttempt(log *zap.Logger, userID string, lastLoginAttempt int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastLoginAttempt", log, userID, lastLoginAttempt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastLoginAttempt indicates an expected call of UpdateLastLoginAttempt.
func (mr *MockUserRepositoryMockRecorder) UpdateLastLoginAttempt(log, userID, lastLoginAttempt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastLoginAttempt", reflect.TypeOf((*MockUserRepository)(nil).UpdateLastLoginAttempt), log, userID, lastLoginAttempt)
}

// UpdatePassword mocks base method.
func (m *MockUserRepository) UpdatePassword(log *zap.Logger, userID, passwordHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", log, userID, passwordHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockUserRepositoryMockRecorder) UpdatePassword(log, userID, passwordHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockUserRepository)(nil).UpdatePassword), log, userID, passwordHash)
}
