// Code generated by MockGen. DO NOT EDIT.
// Source: hospital-backend/internal/modules (interfaces: ModuleRepo)
//
// Generated by this command:
//
//	mockgen -destination=internal/modules/mocks/mock_module_repository.go -package=mocks hospital-backend/internal/modules ModuleRepo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	modules "hospital-backend/internal/modules"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockModuleRepo is a mock of ModuleRepo interface.
type MockModuleRepo struct {
	ctrl     *gomock.Controller
	recorder *MockModuleRepoMockRecorder
	isgomock struct{}
}

// MockModuleRepoMockRecorder is the mock recorder for MockModuleRepo.
type MockModuleRepoMockRecorder struct {
	mock *MockModuleRepo
}

// NewMockModuleRepo creates a new mock instance.
func NewMockModuleRepo(ctrl *gomock.Controller) *MockModuleRepo {
	mock := &MockModuleRepo{ctrl: ctrl}
	mock.recorder = &MockModuleRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModuleRepo) EXPECT() *MockModuleRepoMockRecorder {
	return m.recorder
}

// BatchInsert mocks base method.
func (m *MockModuleRepo) BatchInsert(arg0 []modules.Modules, arg1 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchInsert", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchInsert indicates an expected call of BatchInsert.
func (mr *MockModuleRepoMockRecorder) BatchInsert(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchInsert", reflect.TypeOf((*MockModuleRepo)(nil).BatchInsert), arg0, arg1)
}

// FindMany mocks base method.
func (m *MockModuleRepo) FindMany() ([]modules.Modules, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMany")
	ret0, _ := ret[0].([]modules.Modules)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMany indicates an expected call of FindMany.
func (mr *MockModuleRepoMockRecorder) FindMany() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMany", reflect.TypeOf((*MockModuleRepo)(nil).FindMany))
}
