// Code generated by MockGen. DO NOT EDIT.
// Source: hospital-backend/internal/payments (interfaces: PaymentServicer,WebhookServicer)
//
// Generated by this command:
//
//	mockgen -destination=internal/payments/mocks/mock_payment_servicer.go -package=mocks hospital-backend/internal/payments PaymentServicer,WebhookServicer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	zap "go.uber.org/zap"
)

// MockPaymentServicer is a mock of PaymentServicer interface.
type MockPaymentServicer struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentServicerMockRecorder
	isgomock struct{}
}

// MockPaymentServicerMockRecorder is the mock recorder for MockPaymentServicer.
type MockPaymentServicerMockRecorder struct {
	mock *MockPaymentServicer
}

// NewMockPaymentServicer creates a new mock instance.
func NewMockPaymentServicer(ctrl *gomock.Controller) *MockPaymentServicer {
	mock := &MockPaymentServicer{ctrl: ctrl}
	mock.recorder = &MockPaymentServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentServicer) EXPECT() *MockPaymentServicerMockRecorder {
	return m.recorder
}

// ConfirmManualPayment mocks base method.
func (m *MockPaymentServicer) ConfirmManualPayment(log *zap.Logger, invoiceID, organisationID, paymentMode, txnRef string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmManualPayment", log, invoiceID, organisationID, paymentMode, txnRef)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfirmManualPayment indicates an expected call of ConfirmManualPayment.
func (mr *MockPaymentServicerMockRecorder) ConfirmManualPayment(log, invoiceID, organisationID, paymentMode, txnRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmManualPayment", reflect.TypeOf((*MockPaymentServicer)(nil).ConfirmManualPayment), log, invoiceID, organisationID, paymentMode, txnRef)
}

// MockWebhookServicer is a mock of WebhookServicer interface.
type MockWebhookServicer struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookServicerMockRecorder
	isgomock struct{}
}

// MockWebhookServicerMockRecorder is the mock recorder for MockWebhookServicer.
type MockWebhookServicerMockRecorder struct {
	mock *MockWebhookServicer
}

// NewMockWebhookServicer creates a new mock instance.
func NewMockWebhookServicer(ctrl *gomock.Controller) *MockWebhookServicer {
	mock := &MockWebhookServicer{ctrl: ctrl}
	mock.recorder = &MockWebhookServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookServicer) EXPECT() *MockWebhookServicerMockRecorder {
	return m.recorder
}

// ProcessWebhook mocks base method.
func (m *MockWebhookServicer) ProcessWebhook(log *zap.Logger, payload []byte, signature, provider string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessWebhook", log, payload, signature, provider)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessWebhook indicates an expected call of ProcessWebhook.
func (mr *MockWebhookServicerMockRecorder) ProcessWebhook(log, payload, signature, provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessWebhook", reflect.TypeOf((*MockWebhookServicer)(nil).ProcessWebhook), log, payload, signature, provider)
}
