// Code generated by MockGen. DO NOT EDIT.
// Source: hospital-backend/internal/payments (interfaces: IPaymentsRepository,IWebhookRepository,IPaymentAttempts)
//
// Generated by this command:
//
//	mockgen -destination=internal/payments/mocks/mock_payments_repository.go -package=mocks hospital-backend/internal/payments IPaymentsRepository,IWebhookRepository,IPaymentAttempts
//

// Package mocks is a generated GoMock package.
package mocks

import (
	payments "hospital-backend/internal/payments"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	zap "go.uber.org/zap"
	gorm "gorm.io/gorm"
)

// MockIPaymentsRepository is a mock of IPaymentsRepository interface.
type MockIPaymentsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIPaymentsRepositoryMockRecorder
	isgomock struct{}
}

// MockIPaymentsRepositoryMockRecorder is the mock recorder for MockIPaymentsRepository.
type MockIPaymentsRepositoryMockRecorder struct {
	mock *MockIPaymentsRepository
}

// NewMockIPaymentsRepository creates a new mock instance.
func NewMockIPaymentsRepository(ctrl *gomock.Controller) *MockIPaymentsRepository {
	mock := &MockIPaymentsRepository{ctrl: ctrl}
	mock.recorder = &MockIPaymentsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPaymentsRepository) EXPECT() *MockIPaymentsRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIPaymentsRepository) Create(log *zap.Logger, db *gorm.DB, payment payments.Payments) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", log, db, payment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIPaymentsRepositoryMockRecorder) Create(log, db, payment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIPaymentsRepository)(nil).Create), log, db, payment)
}

// FindByIdempotencyKey mocks base method.
func (m *MockIPaymentsRepository) FindByIdempotencyKey(log *zap.Logger, idempotencyKey string) (payments.Payments, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIdempotencyKey", log, idempotencyKey)
	ret0, _ := ret[0].(payments.Payments)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIdempotencyKey indicates an expected call of FindByIdempotencyKey.
func (mr *MockIPaymentsRepositoryMockRecorder) FindByIdempotencyKey(log, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIdempotencyKey", reflect.TypeOf((*MockIPaymentsRepository)(nil).FindByIdempotencyKey), log, idempotencyKey)
}

// FindByInvoiceID mocks base method.
func (m *MockIPaymentsRepository) FindByInvoiceID(log *zap.Logger, invoiceID string) (payments.Payments, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByInvoiceID", log, invoiceID)
	ret0, _ := ret[0].(payments.Payments)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByInvoiceID indicates an expected call of FindByInvoiceID.
func (mr *MockIPaymentsRepositoryMockRecorder) FindByInvoiceID(log, invoiceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByInvoiceID", reflect.TypeOf((*MockIPaymentsRepository)(nil).FindByInvoiceID), log, invoiceID)
}

// FindInvoiceByPaymentAttempt mocks base method.
func (m *MockIPaymentsRepository) FindInvoiceByPaymentAttempt(log *zap.Logger, query string, args ...any) (payments.Payments, error) {
	m.ctrl.T.Helper()
	varargs := []any{log, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindInvoiceByPaymentAttempt", varargs...)
	ret0, _ := ret[0].(payments.Payments)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindInvoiceByPaymentAttempt indicates an expected call of FindInvoiceByPaymentAttempt.
func (mr *MockIPaymentsRepositoryMockRecorder) FindInvoiceByPaymentAttempt(log, query any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{log, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindInvoiceByPaymentAttempt", reflect.TypeOf((*MockIPaymentsRepository)(nil).FindInvoiceByPaymentAttempt), varargs...)
}

// UpdateSource mocks base method.
func (m *MockIPaymentsRepository) UpdateSource(log *zap.Logger, tx *gorm.DB, paymentID, source, channel string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSource", log, tx, paymentID, source, channel)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSource indicates an expected call of UpdateSource.
func (mr *MockIPaymentsRepositoryMockRecorder) UpdateSource(log, tx, paymentID, source, channel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSource", reflect.TypeOf((*MockIPaymentsRepository)(nil).UpdateSource), log, tx, paymentID, source, channel)
}

// MockIWebhookRepository is a mock of IWebhookRepository interface.
type MockIWebhookRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIWebhookRepositoryMockRecorder
	isgomock struct{}
}

// MockIWebhookRepositoryMockRecorder is the mock recorder for MockIWebhookRepository.
type MockIWebhookRepositoryMockRecorder struct {
	mock *MockIWebhookRepository
}

// NewMockIWebhookRepository creates a new mock instance.
func NewMockIWebhookRepository(ctrl *gomock.Controller) *MockIWebhookRepository {
	mock := &MockIWebhookRepository{ctrl: ctrl}
	mock.recorder = &MockIWebhookRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIWebhookRepository) EXPECT() *MockIWebhookRepositoryMockRecorder {
	return m.recorder
}

// CreateWebhookEvent mocks base method.
func (m *MockIWebhookRepository) CreateWebhookEvent(log *zap.Logger, webhook payments.WebhookEvents) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWebhookEvent", log, webhook)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWebhookEvent indicates an expected call of CreateWebhookEvent.
func (mr *MockIWebhookRepositoryMockRecorder) CreateWebhookEvent(log, webhook any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWebhookEvent", reflect.TypeOf((*MockIWebhookRepository)(nil).CreateWebhookEvent), log, webhook)
}

// MockIPaymentAttempts is a mock of IPaymentAttempts interface.
type MockIPaymentAttempts struct {
	ctrl     *gomock.Controller
	recorder *MockIPaymentAttemptsMockRecorder
	isgomock struct{}
}

// MockIPaymentAttemptsMockRecorder is the mock recorder for MockIPaymentAttempts.
type MockIPaymentAttemptsMockRecorder struct {
	mock *MockIPaymentAttempts
}

// NewMockIPaymentAttempts creates a new mock instance.
func NewMockIPaymentAttempts(ctrl *gomock.Controller) *MockIPaymentAttempts {
	mock := &MockIPaymentAttempts{ctrl: ctrl}
	mock.recorder = &MockIPaymentAttemptsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPaymentAttempts) EXPECT() *MockIPaymentAttemptsMockRecorder {
	return m.recorder
}

// ClaimForProcessing mocks base method.
func (m *MockIPaymentAttempts) ClaimForProcessing(log *zap.Logger, providerLinkID string) (payments.PaymentAttempts, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimForProcessing", log, providerLinkID)
	ret0, _ := ret[0].(payments.PaymentAttempts)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ClaimForProcessing indicates an expected call of ClaimForProcessing.
func (mr *MockIPaymentAttemptsMockRecorder) ClaimForProcessing(log, providerLinkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimForProcessing", reflect.TypeOf((*MockIPaymentAttempts)(nil).ClaimForProcessing), log, providerLinkID)
}

// CountByPaymentID mocks base method.
func (m *MockIPaymentAttempts) CountByPaymentID(log *zap.Logger, paymentID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByPaymentID", log, paymentID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByPaymentID indicates an expected call of CountByPaymentID.
func (mr *MockIPaymentAttemptsMockRecorder) CountByPaymentID(log, paymentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByPaymentID", reflect.TypeOf((*MockIPaymentAttempts)(nil).CountByPaymentID), log, paymentID)
}

// CreatePaymentAttempts mocks base method.
func (m *MockIPaymentAttempts) CreatePaymentAttempts(log *zap.Logger, tx *gorm.DB, PAttempts payments.PaymentAttempts) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePaymentAttempts", log, tx, PAttempts)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePaymentAttempts indicates an expected call of CreatePaymentAttempts.
func (mr *MockIPaymentAttemptsMockRecorder) CreatePaymentAttempts(log, tx, PAttempts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePaymentAttempts", reflect.TypeOf((*MockIPaymentAttempts)(nil).CreatePaymentAttempts), log, tx, PAttempts)
}

// FindByClientIdempotencyKey mocks base method.
func (m *MockIPaymentAttempts) FindByClientIdempotencyKey(log *zap.Logger, key string) (payments.PaymentAttempts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByClientIdempotencyKey", log, key)
	ret0, _ := ret[0].(payments.PaymentAttempts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByClientIdempotencyKey indicates an expected call of FindByClientIdempotencyKey.
func (mr *MockIPaymentAttemptsMockRecorder) FindByClientIdempotencyKey(log, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByClientIdempotencyKey", reflect.TypeOf((*MockIPaymentAttempts)(nil).FindByClientIdempotencyKey), log, key)
}

// FindByPaymentID mocks base method.
func (m *MockIPaymentAttempts) FindByPaymentID(log *zap.Logger, paymentID string) (payments.PaymentAttempts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByPaymentID", log, paymentID)
	ret0, _ := ret[0].(payments.PaymentAttempts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByPaymentID indicates an expected call of FindByPaymentID.
func (mr *MockIPaymentAttemptsMockRecorder) FindByPaymentID(log, paymentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByPaymentID", reflect.TypeOf((*MockIPaymentAttempts)(nil).FindByPaymentID), log, paymentID)
}

// FindByProviderLinkID mocks base method.
func (m *MockIPaymentAttempts) FindByProviderLinkID(log *zap.Logger, providerLinkID string) (payments.PaymentAttempts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByProviderLinkID", log, providerLinkID)
	ret0, _ := ret[0].(payments.PaymentAttempts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByProviderLinkID indicates an expected call of FindByProviderLinkID.
func (mr *MockIPaymentAttemptsMockRecorder) FindByProviderLinkID(log, providerLinkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByProviderLinkID", reflect.TypeOf((*MockIPaymentAttempts)(nil).FindByProviderLinkID), log, providerLinkID)
}

// UpdatePaymentAttempt mocks base method.
func (m *MockIPaymentAttempts) UpdatePaymentAttempt(log *zap.Logger, tx *gorm.DB, paymentAttempt payments.PaymentAttempts) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePaymentAttempt", log, tx, paymentAttempt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePaymentAttempt indicates an expected call of UpdatePaymentAttempt.
func (mr *MockIPaymentAttemptsMockRecorder) UpdatePaymentAttempt(log, tx, paymentAttempt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePaymentAttempt", reflect.TypeOf((*MockIPaymentAttempts)(nil).UpdatePaymentAttempt), log, tx, paymentAttempt)
}

// UpdatePaymentAttemptStatus mocks base method.
func (m *MockIPaymentAttempts) UpdatePaymentAttemptStatus(log *zap.Logger, tx *gorm.DB, PaymentAttempt payments.PaymentAttempts) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePaymentAttemptStatus", log, tx, PaymentAttempt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePaymentAttemptStatus indicates an expected call of UpdatePaymentAttemptStatus.
func (mr *MockIPaymentAttemptsMockRecorder) UpdatePaymentAttemptStatus(log, tx, PaymentAttempt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePaymentAttemptStatus", reflect.TypeOf((*MockIPaymentAttempts)(nil).UpdatePaymentAttemptStatus), log, tx, PaymentAttempt)
}
