// Code generated by MockGen. DO NOT EDIT.
// Source: hospital-backend/internal/payments (interfaces: IPaymentFulfillment,PaymentAttemptServicer,FulfillmentServicer,PaymentInvoiceLookup,PrescriptionStatusUpdater)
//
// Generated by this command:
//
//	mockgen -destination=internal/payments/mocks/mock_payment_fulfillment.go -package=mocks hospital-backend/internal/payments IPaymentFulfillment,PaymentAttemptServicer,FulfillmentServicer,PaymentInvoiceLookup,PrescriptionStatusUpdater
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	dto "hospital-backend/internal/billing/dto"
	dto0 "hospital-backend/internal/notifications/dto"
	payments "hospital-backend/internal/payments"
	dto1 "hospital-backend/internal/payments/dto"
	types "hospital-backend/pkg/types"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
	zap "go.uber.org/zap"
	gorm "gorm.io/gorm"
)

// MockIPaymentFulfillment is a mock of IPaymentFulfillment interface.
type MockIPaymentFulfillment struct {
	ctrl     *gomock.Controller
	recorder *MockIPaymentFulfillmentMockRecorder
	isgomock struct{}
}

// MockIPaymentFulfillmentMockRecorder is the mock recorder for MockIPaymentFulfillment.
type MockIPaymentFulfillmentMockRecorder struct {
	mock *MockIPaymentFulfillment
}

// NewMockIPaymentFulfillment creates a new mock instance.
func NewMockIPaymentFulfillment(ctrl *gomock.Controller) *MockIPaymentFulfillment {
	mock := &MockIPaymentFulfillment{ctrl: ctrl}
	mock.recorder = &MockIPaymentFulfillmentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPaymentFulfillment) EXPECT() *MockIPaymentFulfillmentMockRecorder {
	return m.recorder
}

// CreateMedicineMvmt mocks base method.
func (m *MockIPaymentFulfillment) CreateMedicineMvmt(tx *gorm.DB, medicineMvmt []types.MedicineStockMovements) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMedicineMvmt", tx, medicineMvmt)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMedicineMvmt indicates an expected call of CreateMedicineMvmt.
func (mr *MockIPaymentFulfillmentMockRecorder) CreateMedicineMvmt(tx, medicineMvmt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMedicineMvmt", reflect.TypeOf((*MockIPaymentFulfillment)(nil).CreateMedicineMvmt), tx, medicineMvmt)
}

// CreateNotification mocks base method.
func (m *MockIPaymentFulfillment) CreateNotification(ctx context.Context, notification dto0.CreateRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNotification", ctx, notification)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateNotification indicates an expected call of CreateNotification.
func (mr *MockIPaymentFulfillmentMockRecorder) CreateNotification(ctx, notification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNotification", reflect.TypeOf((*MockIPaymentFulfillment)(nil).CreateNotification), ctx, notification)
}

// GetMedicineInventoryDetByInvoiceID mocks base method.
func (m *MockIPaymentFulfillment) GetMedicineInventoryDetByInvoiceID(invoiceID string) ([]dto.MedInvoiceItemResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMedicineInventoryDetByInvoiceID", invoiceID)
	ret0, _ := ret[0].([]dto.MedInvoiceItemResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMedicineInventoryDetByInvoiceID indicates an expected call of GetMedicineInventoryDetByInvoiceID.
func (mr *MockIPaymentFulfillmentMockRecorder) GetMedicineInventoryDetByInvoiceID(invoiceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMedicineInventoryDetByInvoiceID", reflect.TypeOf((*MockIPaymentFulfillment)(nil).GetMedicineInventoryDetByInvoiceID), invoiceID)
}

// GetNotificationPatientByID mocks base method.
func (m *MockIPaymentFulfillment) GetNotificationPatientByID(patientID string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotificationPatientByID", patientID)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotificationPatientByID indicates an expected call of GetNotificationPatientByID.
func (mr *MockIPaymentFulfillmentMockRecorder) GetNotificationPatientByID(patientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotificationPatientByID", reflect.TypeOf((*MockIPaymentFulfillment)(nil).GetNotificationPatientByID), patientID)
}

// ResolveAndUpdateParentPrescriptionStatus mocks base method.
func (m *MockIPaymentFulfillment) ResolveAndUpdateParentPrescriptionStatus(tx *gorm.DB, prescriptionID string, medicineInventoryDet []dto.MedInvoiceItemResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveAndUpdateParentPrescriptionStatus", tx, prescriptionID, medicineInventoryDet)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResolveAndUpdateParentPrescriptionStatus indicates an expected call of ResolveAndUpdateParentPrescriptionStatus.
func (mr *MockIPaymentFulfillmentMockRecorder) ResolveAndUpdateParentPrescriptionStatus(tx, prescriptionID, medicineInventoryDet any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveAndUpdateParentPrescriptionStatus", reflect.TypeOf((*MockIPaymentFulfillment)(nil).ResolveAndUpdateParentPrescriptionStatus), tx, prescriptionID, medicineInventoryDet)
}

// UpdateDispenseItemQty mocks base method.
func (m *MockIPaymentFulfillment) UpdateDispenseItemQty(tx *gorm.DB, prescriptionItemID string, dispensedQty int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDispenseItemQty", tx, prescriptionItemID, dispensedQty)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDispenseItemQty indicates an expected call of UpdateDispenseItemQty.
func (mr *MockIPaymentFulfillmentMockRecorder) UpdateDispenseItemQty(tx, prescriptionItemID, dispensedQty any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDispenseItemQty", reflect.TypeOf((*MockIPaymentFulfillment)(nil).UpdateDispenseItemQty), tx, prescriptionItemID, dispensedQty)
}

// UpdateExtPrescriptionStatus mocks base method.
func (m *MockIPaymentFulfillment) UpdateExtPrescriptionStatus(tx *gorm.DB, prescriptionID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateExtPrescriptionStatus", tx, prescriptionID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateExtPrescriptionStatus indicates an expected call of UpdateExtPrescriptionStatus.
func (mr *MockIPaymentFulfillmentMockRecorder) UpdateExtPrescriptionStatus(tx, prescriptionID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateExtPrescriptionStatus", reflect.TypeOf((*MockIPaymentFulfillment)(nil).UpdateExtPrescriptionStatus), tx, prescriptionID, status)
}

// UpdateIPrescriptionStatus mocks base method.
func (m *MockIPaymentFulfillment) UpdateIPrescriptionStatus(tx *gorm.DB, prescriptionItemID, status string, outOfStock bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIPrescriptionStatus", tx, prescriptionItemID, status, outOfStock)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateIPrescriptionStatus indicates an expected call of UpdateIPrescriptionStatus.
func (mr *MockIPaymentFulfillmentMockRecorder) UpdateIPrescriptionStatus(tx, prescriptionItemID, status, outOfStock any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIPrescriptionStatus", reflect.TypeOf((*MockIPaymentFulfillment)(nil).UpdateIPrescriptionStatus), tx, prescriptionItemID, status, outOfStock)
}

// UpdateInvoiceStatus mocks base method.
func (m *MockIPaymentFulfillment) UpdateInvoiceStatus(tx *gorm.DB, invoiceID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInvoiceStatus", tx, invoiceID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateInvoiceStatus indicates an expected call of UpdateInvoiceStatus.
func (mr *MockIPaymentFulfillmentMockRecorder) UpdateInvoiceStatus(tx, invoiceID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInvoiceStatus", reflect.TypeOf((*MockIPaymentFulfillment)(nil).UpdateInvoiceStatus), tx, invoiceID, status)
}

// UpdateMedInventoryStock mocks base method.
func (m *MockIPaymentFulfillment) UpdateMedInventoryStock(tx *gorm.DB, medicineInventoryID string, dispensedQty int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMedInventoryStock", tx, medicineInventoryID, dispensedQty)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMedInventoryStock indicates an expected call of UpdateMedInventoryStock.
func (mr *MockIPaymentFulfillmentMockRecorder) UpdateMedInventoryStock(tx, medicineInventoryID, dispensedQty any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMedInventoryStock", reflect.TypeOf((*MockIPaymentFulfillment)(nil).UpdateMedInventoryStock), tx, medicineInventoryID, dispensedQty)
}

// MockPaymentAttemptServicer is a mock of PaymentAttemptServicer interface.
type MockPaymentAttemptServicer struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentAttemptServicerMockRecorder
	isgomock struct{}
}

// MockPaymentAttemptServicerMockRecorder is the mock recorder for MockPaymentAttemptServicer.
type MockPaymentAttemptServicerMockRecorder struct {
	mock *MockPaymentAttemptServicer
}

// NewMockPaymentAttemptServicer creates a new mock instance.
func NewMockPaymentAttemptServicer(ctrl *gomock.Controller) *MockPaymentAttemptServicer {
	mock := &MockPaymentAttemptServicer{ctrl: ctrl}
	mock.recorder = &MockPaymentAttemptServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentAttemptServicer) EXPECT() *MockPaymentAttemptServicerMockRecorder {
	return m.recorder
}

// ClaimForProcessing mocks base method.
func (m *MockPaymentAttemptServicer) ClaimForProcessing(log *zap.Logger, providerLinkID string) (payments.PaymentAttempts, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimForProcessing", log, providerLinkID)
	ret0, _ := ret[0].(payments.PaymentAttempts)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ClaimForProcessing indicates an expected call of ClaimForProcessing.
func (mr *MockPaymentAttemptServicerMockRecorder) ClaimForProcessing(log, providerLinkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimForProcessing", reflect.TypeOf((*MockPaymentAttemptServicer)(nil).ClaimForProcessing), log, providerLinkID)
}

// CreateAttempt mocks base method.
func (m *MockPaymentAttemptServicer) CreateAttempt(log *zap.Logger, tx *gorm.DB, internalPaymentID string, paymentResponse dto1.CreatePaymentResponse, providerName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAttempt", log, tx, internalPaymentID, paymentResponse, providerName)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAttempt indicates an expected call of CreateAttempt.
func (mr *MockPaymentAttemptServicerMockRecorder) CreateAttempt(log, tx, internalPaymentID, paymentResponse, providerName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAttempt", reflect.TypeOf((*MockPaymentAttemptServicer)(nil).CreateAttempt), log, tx, internalPaymentID, paymentResponse, providerName)
}

// CreateAttemptWithIdempotency mocks base method.
func (m *MockPaymentAttemptServicer) CreateAttemptWithIdempotency(log *zap.Logger, tx *gorm.DB, internalPaymentID string, paymentResponse dto1.CreatePaymentResponse, providerName, clientIdempotencyKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAttemptWithIdempotency", log, tx, internalPaymentID, paymentResponse, providerName, clientIdempotencyKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAttemptWithIdempotency indicates an expected call of CreateAttemptWithIdempotency.
func (mr *MockPaymentAttemptServicerMockRecorder) CreateAttemptWithIdempotency(log, tx, internalPaymentID, paymentResponse, providerName, clientIdempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAttemptWithIdempotency", reflect.TypeOf((*MockPaymentAttemptServicer)(nil).CreateAttemptWithIdempotency), log, tx, internalPaymentID, paymentResponse, providerName, clientIdempotencyKey)
}

// FindByClientIdempotencyKey mocks base method.
func (m *MockPaymentAttemptServicer) FindByClientIdempotencyKey(log *zap.Logger, key string) (payments.PaymentAttempts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByClientIdempotencyKey", log, key)
	ret0, _ := ret[0].(payments.PaymentAttempts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByClientIdempotencyKey indicates an expected call of FindByClientIdempotencyKey.
func (mr *MockPaymentAttemptServicerMockRecorder) FindByClientIdempotencyKey(log, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByClientIdempotencyKey", reflect.TypeOf((*MockPaymentAttemptServicer)(nil).FindByClientIdempotencyKey), log, key)
}

// FindByPaymentID mocks base method.
func (m *MockPaymentAttemptServicer) FindByPaymentID(log *zap.Logger, paymentID string) (payments.PaymentAttempts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByPaymentID", log, paymentID)
	ret0, _ := ret[0].(payments.PaymentAttempts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByPaymentID indicates an expected call of FindByPaymentID.
func (mr *MockPaymentAttemptServicerMockRecorder) FindByPaymentID(log, paymentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByPaymentID", reflect.TypeOf((*MockPaymentAttemptServicer)(nil).FindByPaymentID), log, paymentID)
}

// FindByProviderLinkID mocks base method.
func (m *MockPaymentAttemptServicer) FindByProviderLinkID(log *zap.Logger, providerLinkID string) (payments.PaymentAttempts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByProviderLinkID", log, providerLinkID)
	ret0, _ := ret[0].(payments.PaymentAttempts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByProviderLinkID indicates an expected call of FindByProviderLinkID.
func (mr *MockPaymentAttemptServicerMockRecorder) FindByProviderLinkID(log, providerLinkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByProviderLinkID", reflect.TypeOf((*MockPaymentAttemptServicer)(nil).FindByProviderLinkID), log, providerLinkID)
}

// UpdatePaymentAttempt mocks base method.
func (m *MockPaymentAttemptServicer) UpdatePaymentAttempt(log *zap.Logger, tx *gorm.DB, paymentAttempt payments.PaymentAttempts) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePaymentAttempt", log, tx, paymentAttempt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePaymentAttempt indicates an expected call of UpdatePaymentAttempt.
func (mr *MockPaymentAttemptServicerMockRecorder) UpdatePaymentAttempt(log, tx, paymentAttempt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePaymentAttempt", reflect.TypeOf((*MockPaymentAttemptServicer)(nil).UpdatePaymentAttempt), log, tx, paymentAttempt)
}

// UpdatePaymentAttemptStatus mocks base method.
func (m *MockPaymentAttemptServicer) UpdatePaymentAttemptStatus(log *zap.Logger, tx *gorm.DB, paymentAttempt payments.PaymentAttempts) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePaymentAttemptStatus", log, tx, paymentAttempt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePaymentAttemptStatus indicates an expected call of UpdatePaymentAttemptStatus.
func (mr *MockPaymentAttemptServicerMockRecorder) UpdatePaymentAttemptStatus(log, tx, paymentAttempt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePaymentAttemptStatus", reflect.TypeOf((*MockPaymentAttemptServicer)(nil).UpdatePaymentAttemptStatus), log, tx, paymentAttempt)
}

// MockFulfillmentServicer is a mock of FulfillmentServicer interface.
type MockFulfillmentServicer struct {
	ctrl     *gomock.Controller
	recorder *MockFulfillmentServicerMockRecorder
	isgomock struct{}
}

// MockFulfillmentServicerMockRecorder is the mock recorder for MockFulfillmentServicer.
type MockFulfillmentServicerMockRecorder struct {
	mock *MockFulfillmentServicer
}

// NewMockFulfillmentServicer creates a new mock instance.
func NewMockFulfillmentServicer(ctrl *gomock.Controller) *MockFulfillmentServicer {
	mock := &MockFulfillmentServicer{ctrl: ctrl}
	mock.recorder = &MockFulfillmentServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFulfillmentServicer) EXPECT() *MockFulfillmentServicerMockRecorder {
	return m.recorder
}

// FulfillPaidInvoice mocks base method.
func (m *MockFulfillmentServicer) FulfillPaidInvoice(log *zap.Logger, tx *gorm.DB, invoiceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FulfillPaidInvoice", log, tx, invoiceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// FulfillPaidInvoice indicates an expected call of FulfillPaidInvoice.
func (mr *MockFulfillmentServicerMockRecorder) FulfillPaidInvoice(log, tx, invoiceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FulfillPaidInvoice", reflect.TypeOf((*MockFulfillmentServicer)(nil).FulfillPaidInvoice), log, tx, invoiceID)
}

// NotifyPaymentReceived mocks base method.
func (m *MockFulfillmentServicer) NotifyPaymentReceived(log *zap.Logger, payment payments.Payments, paidAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyPaymentReceived", log, payment, paidAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyPaymentReceived indicates an expected call of NotifyPaymentReceived.
func (mr *MockFulfillmentServicerMockRecorder) NotifyPaymentReceived(log, payment, paidAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyPaymentReceived", reflect.TypeOf((*MockFulfillmentServicer)(nil).NotifyPaymentReceived), log, payment, paidAt)
}

// MockPaymentInvoiceLookup is a mock of PaymentInvoiceLookup interface.
type MockPaymentInvoiceLookup struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentInvoiceLookupMockRecorder
	isgomock struct{}
}

// MockPaymentInvoiceLookupMockRecorder is the mock recorder for MockPaymentInvoiceLookup.
type MockPaymentInvoiceLookupMockRecorder struct {
	mock *MockPaymentInvoiceLookup
}

// NewMockPaymentInvoiceLookup creates a new mock instance.
func NewMockPaymentInvoiceLookup(ctrl *gomock.Controller) *MockPaymentInvoiceLookup {
	mock := &MockPaymentInvoiceLookup{ctrl: ctrl}
	mock.recorder = &MockPaymentInvoiceLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentInvoiceLookup) EXPECT() *MockPaymentInvoiceLookupMockRecorder {
	return m.recorder
}

// FindInvoiceByPaymentAttempt mocks base method.
func (m *MockPaymentInvoiceLookup) FindInvoiceByPaymentAttempt(log *zap.Logger, query string, args ...any) (payments.Payments, error) {
	m.ctrl.T.Helper()
	varargs := []any{log, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindInvoiceByPaymentAttempt", varargs...)
	ret0, _ := ret[0].(payments.Payments)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindInvoiceByPaymentAttempt indicates an expected call of FindInvoiceByPaymentAttempt.
func (mr *MockPaymentInvoiceLookupMockRecorder) FindInvoiceByPaymentAttempt(log, query any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{log, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindInvoiceByPaymentAttempt", reflect.TypeOf((*MockPaymentInvoiceLookup)(nil).FindInvoiceByPaymentAttempt), varargs...)
}

// MockPrescriptionStatusUpdater is a mock of PrescriptionStatusUpdater interface.
type MockPrescriptionStatusUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockPrescriptionStatusUpdaterMockRecorder
	isgomock struct{}
}

// MockPrescriptionStatusUpdaterMockRecorder is the mock recorder for MockPrescriptionStatusUpdater.
type MockPrescriptionStatusUpdaterMockRecorder struct {
	mock *MockPrescriptionStatusUpdater
}

// NewMockPrescriptionStatusUpdater creates a new mock instance.
func NewMockPrescriptionStatusUpdater(ctrl *gomock.Controller) *MockPrescriptionStatusUpdater {
	mock := &MockPrescriptionStatusUpdater{ctrl: ctrl}
	mock.recorder = &MockPrescriptionStatusUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrescriptionStatusUpdater) EXPECT() *MockPrescriptionStatusUpdaterMockRecorder {
	return m.recorder
}

// UpdateExtPrescriptionStatus mocks base method.
func (m *MockPrescriptionStatusUpdater) UpdateExtPrescriptionStatus(tx *gorm.DB, prescriptionID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateExtPrescriptionStatus", tx, prescriptionID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateExtPrescriptionStatus indicates an expected call of UpdateExtPrescriptionStatus.
func (mr *MockPrescriptionStatusUpdaterMockRecorder) UpdateExtPrescriptionStatus(tx, prescriptionID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateExtPrescriptionStatus", reflect.TypeOf((*MockPrescriptionStatusUpdater)(nil).UpdateExtPrescriptionStatus), tx, prescriptionID, status)
}
