// Code generated by MockGen. DO NOT EDIT.
// Source: hospital-backend/central/organisations (interfaces: OrganisationServicer)
//
// Generated by this command:
//
//	mockgen -destination=central/organisations/mocks/mock_organisation_servicer.go -package=mocks hospital-backend/central/organisations OrganisationServicer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	organisations "hospital-backend/central/organisations"
	dto "hospital-backend/central/organisations/dto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	zap "go.uber.org/zap"
)

// MockOrganisationServicer is a mock of OrganisationServicer interface.
type MockOrganisationServicer struct {
	ctrl     *gomock.Controller
	recorder *MockOrganisationServicerMockRecorder
	isgomock struct{}
}

// MockOrganisationServicerMockRecorder is the mock recorder for MockOrganisationServicer.
type MockOrganisationServicerMockRecorder struct {
	mock *MockOrganisationServicer
}

// NewMockOrganisationServicer creates a new mock instance.
func NewMockOrganisationServicer(ctrl *gomock.Controller) *MockOrganisationServicer {
	mock := &MockOrganisationServicer{ctrl: ctrl}
	mock.recorder = &MockOrganisationServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrganisationServicer) EXPECT() *MockOrganisationServicerMockRecorder {
	return m.recorder
}

// AddOrganisation mocks base method.
func (m *MockOrganisationServicer) AddOrganisation(log *zap.Logger, payload dto.OrganisationPayload) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddOrganisation", log, payload)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddOrganisation indicates an expected call of AddOrganisation.
func (mr *MockOrganisationServicerMockRecorder) AddOrganisation(log, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOrganisation", reflect.TypeOf((*MockOrganisationServicer)(nil).AddOrganisation), log, payload)
}

// GetOrgByID mocks base method.
func (m *MockOrganisationServicer) GetOrgByID(log *zap.Logger, organisationID string) (organisations.Organisation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrgByID", log, organisationID)
	ret0, _ := ret[0].(organisations.Organisation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrgByID indicates an expected call of GetOrgByID.
func (mr *MockOrganisationServicerMockRecorder) GetOrgByID(log, organisationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrgByID", reflect.TypeOf((*MockOrganisationServicer)(nil).GetOrgByID), log, organisationID)
}

// ListByTenantID mocks base method.
func (m *MockOrganisationServicer) ListByTenantID(log *zap.Logger, tenantID string) ([]organisations.Organisation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByTenantID", log, tenantID)
	ret0, _ := ret[0].([]organisations.Organisation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByTenantID indicates an expected call of ListByTenantID.
func (mr *MockOrganisationServicerMockRecorder) ListByTenantID(log, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByTenantID", reflect.TypeOf((*MockOrganisationServicer)(nil).ListByTenantID), log, tenantID)
}

// Update mocks base method.
func (m *MockOrganisationServicer) Update(log *zap.Logger, organisationID string, payload dto.OrganisationPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", log, organisationID, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockOrganisationServicerMockRecorder) Update(log, organisationID, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockOrganisationServicer)(nil).Update), log, organisationID, payload)
}

// UpdateAddress mocks base method.
func (m *MockOrganisationServicer) UpdateAddress(log *zap.Logger, payload dto.OrganisationPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAddress", log, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAddress indicates an expected call of UpdateAddress.
func (mr *MockOrganisationServicerMockRecorder) UpdateAddress(log, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAddress", reflect.TypeOf((*MockOrganisationServicer)(nil).UpdateAddress), log, payload)
}
