// Code generated by MockGen. DO NOT EDIT.
// Source: hospital-backend/central/organisations (interfaces: OrganisationRepo)
//
// Generated by this command:
//
//	mockgen -destination=central/organisations/mocks/mock_organisation_repository.go -package=mocks hospital-backend/central/organisations OrganisationRepo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	organisations "hospital-backend/central/organisations"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	zap "go.uber.org/zap"
	gorm "gorm.io/gorm"
)

// MockOrganisationRepo is a mock of OrganisationRepo interface.
type MockOrganisationRepo struct {
	ctrl     *gomock.Controller
	recorder *MockOrganisationRepoMockRecorder
	isgomock struct{}
}

// MockOrganisationRepoMockRecorder is the mock recorder for MockOrganisationRepo.
type MockOrganisationRepoMockRecorder struct {
	mock *MockOrganisationRepo
}

// NewMockOrganisationRepo creates a new mock instance.
func NewMockOrganisationRepo(ctrl *gomock.Controller) *MockOrganisationRepo {
	mock := &MockOrganisationRepo{ctrl: ctrl}
	mock.recorder = &MockOrganisationRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrganisationRepo) EXPECT() *MockOrganisationRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOrganisationRepo) Create(log *zap.Logger, tx *gorm.DB, organisation organisations.Organisation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", log, tx, organisation)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOrganisationRepoMockRecorder) Create(log, tx, organisation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrganisationRepo)(nil).Create), log, tx, organisation)
}

// GetByID mocks base method.
func (m *MockOrganisationRepo) GetByID(log *zap.Logger, query string, cond ...any) (organisations.Organisation, error) {
	m.ctrl.T.Helper()
	varargs := []any{log, query}
	for _, a := range cond {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetByID", varargs...)
	ret0, _ := ret[0].(organisations.Organisation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockOrganisationRepoMockRecorder) GetByID(log, query any, cond ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{log, query}, cond...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockOrganisationRepo)(nil).GetByID), varargs...)
}

// ListByTenantID mocks base method.
func (m *MockOrganisationRepo) ListByTenantID(log *zap.Logger, query string, cond ...any) ([]organisations.Organisation, error) {
	m.ctrl.T.Helper()
	varargs := []any{log, query}
	for _, a := range cond {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListByTenantID", varargs...)
	ret0, _ := ret[0].([]organisations.Organisation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByTenantID indicates an expected call of ListByTenantID.
func (mr *MockOrganisationRepoMockRecorder) ListByTenantID(log, query any, cond ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{log, query}, cond...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByTenantID", reflect.TypeOf((*MockOrganisationRepo)(nil).ListByTenantID), varargs...)
}

// Update mocks base method.
func (m *MockOrganisationRepo) Update(log *zap.Logger, query string, cond ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{log, query}
	for _, a := range cond {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockOrganisationRepoMockRecorder) Update(log, query any, cond ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{log, query}, cond...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockOrganisationRepo)(nil).Update), varargs...)
}

// UpdateAddressByID mocks base method.
func (m *MockOrganisationRepo) UpdateAddressByID(log *zap.Logger, query string, cond ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{log, query}
	for _, a := range cond {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateAddressByID", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAddressByID indicates an expected call of UpdateAddressByID.
func (mr *MockOrganisationRepoMockRecorder) UpdateAddressByID(log, query any, cond ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{log, query}, cond...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAddressByID", reflect.TypeOf((*MockOrganisationRepo)(nil).UpdateAddressByID), varargs...)
}
