// Code generated by MockGen. DO NOT EDIT.
// Source: hospital-backend/internal/medicine (interfaces: MedicineRepository,ISupplier,RMedicineInventory,RPurchaseEntry,RMedicineMvmt)
//
// Generated by this command:
//
//	mockgen -destination=internal/medicine/mocks/mock_medicine_repository.go -package=mocks hospital-backend/internal/medicine MedicineRepository,ISupplier,RMedicineInventory,RPurchaseEntry,RMedicineMvmt
//

// Package mocks is a generated GoMock package.
package mocks

import (
	medicine "hospital-backend/internal/medicine"
	dto "hospital-backend/internal/medicine/dto"
	types "hospital-backend/pkg/types"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	zap "go.uber.org/zap"
	gorm "gorm.io/gorm"
)

// MockMedicineRepository is a mock of MedicineRepository interface.
type MockMedicineRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMedicineRepositoryMockRecorder
	isgomock struct{}
}

// MockMedicineRepositoryMockRecorder is the mock recorder for MockMedicineRepository.
type MockMedicineRepositoryMockRecorder struct {
	mock *MockMedicineRepository
}

// NewMockMedicineRepository creates a new mock instance.
func NewMockMedicineRepository(ctrl *gomock.Controller) *MockMedicineRepository {
	mock := &MockMedicineRepository{ctrl: ctrl}
	mock.recorder = &MockMedicineRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMedicineRepository) EXPECT() *MockMedicineRepositoryMockRecorder {
	return m.recorder
}

// CreateInBatches mocks base method.
func (m *MockMedicineRepository) CreateInBatches(log *zap.Logger, db *gorm.DB, M []medicine.Medicine) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInBatches", log, db, M)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateInBatches indicates an expected call of CreateInBatches.
func (mr *MockMedicineRepositoryMockRecorder) CreateInBatches(log, db, M any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInBatches", reflect.TypeOf((*MockMedicineRepository)(nil).CreateInBatches), log, db, M)
}

// FindMany mocks base method.
func (m *MockMedicineRepository) FindMany(log *zap.Logger, query string, args ...any) ([]medicine.Medicine, error) {
	m.ctrl.T.Helper()
	varargs := []any{log, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindMany", varargs...)
	ret0, _ := ret[0].([]medicine.Medicine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMany indicates an expected call of FindMany.
func (mr *MockMedicineRepositoryMockRecorder) FindMany(log, query any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{log, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMany", reflect.TypeOf((*MockMedicineRepository)(nil).FindMany), varargs...)
}

// FindNamesByIds mocks base method.
func (m *MockMedicineRepository) FindNamesByIds(log *zap.Logger, ids []string) ([]medicine.Medicine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindNamesByIds", log, ids)
	ret0, _ := ret[0].([]medicine.Medicine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindNamesByIds indicates an expected call of FindNamesByIds.
func (mr *MockMedicineRepositoryMockRecorder) FindNamesByIds(log, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindNamesByIds", reflect.TypeOf((*MockMedicineRepository)(nil).FindNamesByIds), log, ids)
}

// FindOne mocks base method.
func (m *MockMedicineRepository) FindOne(log *zap.Logger, id string) (*medicine.Medicine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", log, id)
	ret0, _ := ret[0].(*medicine.Medicine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockMedicineRepositoryMockRecorder) FindOne(log, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockMedicineRepository)(nil).FindOne), log, id)
}

// GetMedicineByID mocks base method.
func (m *MockMedicineRepository) GetMedicineByID(log *zap.Logger, medicineID string) (medicine.Medicine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMedicineByID", log, medicineID)
	ret0, _ := ret[0].(medicine.Medicine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMedicineByID indicates an expected call of GetMedicineByID.
func (mr *MockMedicineRepositoryMockRecorder) GetMedicineByID(log, medicineID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMedicineByID", reflect.TypeOf((*MockMedicineRepository)(nil).GetMedicineByID), log, medicineID)
}

// SearchMedicine mocks base method.
func (m *MockMedicineRepository) SearchMedicine(log *zap.Logger, name, pattern, organisationID string) ([]dto.SearchMedicineItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchMedicine", log, name, pattern, organisationID)
	ret0, _ := ret[0].([]dto.SearchMedicineItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchMedicine indicates an expected call of SearchMedicine.
func (mr *MockMedicineRepositoryMockRecorder) SearchMedicine(log, name, pattern, organisationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchMedicine", reflect.TypeOf((*MockMedicineRepository)(nil).SearchMedicine), log, name, pattern, organisationID)
}

// Update mocks base method.
func (m *MockMedicineRepository) Update(log *zap.Logger, id string, update map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", log, id, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMedicineRepositoryMockRecorder) Update(log, id, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMedicineRepository)(nil).Update), log, id, update)
}

// MockISupplier is a mock of ISupplier interface.
type MockISupplier struct {
	ctrl     *gomock.Controller
	recorder *MockISupplierMockRecorder
	isgomock struct{}
}

// MockISupplierMockRecorder is the mock recorder for MockISupplier.
type MockISupplierMockRecorder struct {
	mock *MockISupplier
}

// NewMockISupplier creates a new mock instance.
func NewMockISupplier(ctrl *gomock.Controller) *MockISupplier {
	mock := &MockISupplier{ctrl: ctrl}
	mock.recorder = &MockISupplierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISupplier) EXPECT() *MockISupplierMockRecorder {
	return m.recorder
}

// CountSupplierByOrgID mocks base method.
func (m *MockISupplier) CountSupplierByOrgID(log *zap.Logger, query string, args ...any) (int64, error) {
	m.ctrl.T.Helper()
	varargs := []any{log, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CountSupplierByOrgID", varargs...)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountSupplierByOrgID indicates an expected call of CountSupplierByOrgID.
func (mr *MockISupplierMockRecorder) CountSupplierByOrgID(log, query any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{log, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountSupplierByOrgID", reflect.TypeOf((*MockISupplier)(nil).CountSupplierByOrgID), varargs...)
}

// CretateSupplier mocks base method.
func (m *MockISupplier) CretateSupplier(log *zap.Logger, supplier *medicine.Supplier) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CretateSupplier", log, supplier)
	ret0, _ := ret[0].(error)
	return ret0
}

// CretateSupplier indicates an expected call of CretateSupplier.
func (mr *MockISupplierMockRecorder) CretateSupplier(log, supplier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CretateSupplier", reflect.TypeOf((*MockISupplier)(nil).CretateSupplier), log, supplier)
}

// GetSupplierByID mocks base method.
func (m *MockISupplier) GetSupplierByID(log *zap.Logger, supplierID string) (medicine.Supplier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSupplierByID", log, supplierID)
	ret0, _ := ret[0].(medicine.Supplier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSupplierByID indicates an expected call of GetSupplierByID.
func (mr *MockISupplierMockRecorder) GetSupplierByID(log, supplierID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupplierByID", reflect.TypeOf((*MockISupplier)(nil).GetSupplierByID), log, supplierID)
}

// GetSupplierByOrgID mocks base method.
func (m *MockISupplier) GetSupplierByOrgID(log *zap.Logger, query string, args ...any) ([]medicine.Supplier, error) {
	m.ctrl.T.Helper()
	varargs := []any{log, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetSupplierByOrgID", varargs...)
	ret0, _ := ret[0].([]medicine.Supplier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSupplierByOrgID indicates an expected call of GetSupplierByOrgID.
func (mr *MockISupplierMockRecorder) GetSupplierByOrgID(log, query any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{log, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupplierByOrgID", reflect.TypeOf((*MockISupplier)(nil).GetSupplierByOrgID), varargs...)
}

// MockRMedicineInventory is a mock of RMedicineInventory interface.
type MockRMedicineInventory struct {
	ctrl     *gomock.Controller
	recorder *MockRMedicineInventoryMockRecorder
	isgomock struct{}
}

// MockRMedicineInventoryMockRecorder is the mock recorder for MockRMedicineInventory.
type MockRMedicineInventoryMockRecorder struct {
	mock *MockRMedicineInventory
}

// NewMockRMedicineInventory creates a new mock instance.
func NewMockRMedicineInventory(ctrl *gomock.Controller) *MockRMedicineInventory {
	mock := &MockRMedicineInventory{ctrl: ctrl}
	mock.recorder = &MockRMedicineInventoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRMedicineInventory) EXPECT() *MockRMedicineInventoryMockRecorder {
	return m.recorder
}

// CreateInventoryInBatch mocks base method.
func (m *MockRMedicineInventory) CreateInventoryInBatch(log *zap.Logger, db *gorm.DB, medicineInventory []medicine.MedicineInventory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInventoryInBatch", log, db, medicineInventory)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateInventoryInBatch indicates an expected call of CreateInventoryInBatch.
func (mr *MockRMedicineInventoryMockRecorder) CreateInventoryInBatch(log, db, medicineInventory any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInventoryInBatch", reflect.TypeOf((*MockRMedicineInventory)(nil).CreateInventoryInBatch), log, db, medicineInventory)
}

// GetMedByBatchNo mocks base method.
func (m *MockRMedicineInventory) GetMedByBatchNo(log *zap.Logger, query string, args ...any) (medicine.MedicineInventory, error) {
	m.ctrl.T.Helper()
	varargs := []any{log, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetMedByBatchNo", varargs...)
	ret0, _ := ret[0].(medicine.MedicineInventory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMedByBatchNo indicates an expected call of GetMedByBatchNo.
func (mr *MockRMedicineInventoryMockRecorder) GetMedByBatchNo(log, query any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{log, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMedByBatchNo", reflect.TypeOf((*MockRMedicineInventory)(nil).GetMedByBatchNo), varargs...)
}

// UpdateMedInventoryStock mocks base method.
func (m *MockRMedicineInventory) UpdateMedInventoryStock(log *zap.Logger, tx *gorm.DB, medicineInventoryID string, dispensedQty int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMedInventoryStock", log, tx, medicineInventoryID, dispensedQty)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMedInventoryStock indicates an expected call of UpdateMedInventoryStock.
func (mr *MockRMedicineInventoryMockRecorder) UpdateMedInventoryStock(log, tx, medicineInventoryID, dispensedQty any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMedInventoryStock", reflect.TypeOf((*MockRMedicineInventory)(nil).UpdateMedInventoryStock), log, tx, medicineInventoryID, dispensedQty)
}

// MockRPurchaseEntry is a mock of RPurchaseEntry interface.
type MockRPurchaseEntry struct {
	ctrl     *gomock.Controller
	recorder *MockRPurchaseEntryMockRecorder
	isgomock struct{}
}

// MockRPurchaseEntryMockRecorder is the mock recorder for MockRPurchaseEntry.
type MockRPurchaseEntryMockRecorder struct {
	mock *MockRPurchaseEntry
}

// NewMockRPurchaseEntry creates a new mock instance.
func NewMockRPurchaseEntry(ctrl *gomock.Controller) *MockRPurchaseEntry {
	mock := &MockRPurchaseEntry{ctrl: ctrl}
	mock.recorder = &MockRPurchaseEntryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRPurchaseEntry) EXPECT() *MockRPurchaseEntryMockRecorder {
	return m.recorder
}

// CreatePurchaseEntry mocks base method.
func (m *MockRPurchaseEntry) CreatePurchaseEntry(log *zap.Logger, db *gorm.DB, purchaseEntry *medicine.MPurchaseEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePurchaseEntry", log, db, purchaseEntry)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePurchaseEntry indicates an expected call of CreatePurchaseEntry.
func (mr *MockRPurchaseEntryMockRecorder) CreatePurchaseEntry(log, db, purchaseEntry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePurchaseEntry", reflect.TypeOf((*MockRPurchaseEntry)(nil).CreatePurchaseEntry), log, db, purchaseEntry)
}

// MockRMedicineMvmt is a mock of RMedicineMvmt interface.
type MockRMedicineMvmt struct {
	ctrl     *gomock.Controller
	recorder *MockRMedicineMvmtMockRecorder
	isgomock struct{}
}

// MockRMedicineMvmtMockRecorder is the mock recorder for MockRMedicineMvmt.
type MockRMedicineMvmtMockRecorder struct {
	mock *MockRMedicineMvmt
}

// NewMockRMedicineMvmt creates a new mock instance.
func NewMockRMedicineMvmt(ctrl *gomock.Controller) *MockRMedicineMvmt {
	mock := &MockRMedicineMvmt{ctrl: ctrl}
	mock.recorder = &MockRMedicineMvmtMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRMedicineMvmt) EXPECT() *MockRMedicineMvmtMockRecorder {
	return m.recorder
}

// CreateMedicineMvmtInBatch mocks base method.
func (m *MockRMedicineMvmt) CreateMedicineMvmtInBatch(log *zap.Logger, db *gorm.DB, medicineMvmt []types.MedicineStockMovements) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMedicineMvmtInBatch", log, db, medicineMvmt)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMedicineMvmtInBatch indicates an expected call of CreateMedicineMvmtInBatch.
func (mr *MockRMedicineMvmtMockRecorder) CreateMedicineMvmtInBatch(log, db, medicineMvmt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMedicineMvmtInBatch", reflect.TypeOf((*MockRMedicineMvmt)(nil).CreateMedicineMvmtInBatch), log, db, medicineMvmt)
}
