// Code generated by MockGen. DO NOT EDIT.
// Source: hospital-backend/internal/medicine (interfaces: MedicineServicer,SupplierServicer)
//
// Generated by this command:
//
//	mockgen -destination=internal/medicine/mocks/mock_medicine_servicer.go -package=mocks hospital-backend/internal/medicine MedicineServicer,SupplierServicer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	medicine "hospital-backend/internal/medicine"
	dto "hospital-backend/internal/medicine/dto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	zap "go.uber.org/zap"
)

// MockMedicineServicer is a mock of MedicineServicer interface.
type MockMedicineServicer struct {
	ctrl     *gomock.Controller
	recorder *MockMedicineServicerMockRecorder
	isgomock struct{}
}

// MockMedicineServicerMockRecorder is the mock recorder for MockMedicineServicer.
type MockMedicineServicerMockRecorder struct {
	mock *MockMedicineServicer
}

// NewMockMedicineServicer creates a new mock instance.
func NewMockMedicineServicer(ctrl *gomock.Controller) *MockMedicineServicer {
	mock := &MockMedicineServicer{ctrl: ctrl}
	mock.recorder = &MockMedicineServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMedicineServicer) EXPECT() *MockMedicineServicerMockRecorder {
	return m.recorder
}

// CreateMedicine mocks base method.
func (m *MockMedicineServicer) CreateMedicine(log *zap.Logger, MedicinePayload dto.RequestPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMedicine", log, MedicinePayload)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMedicine indicates an expected call of CreateMedicine.
func (mr *MockMedicineServicerMockRecorder) CreateMedicine(log, MedicinePayload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMedicine", reflect.TypeOf((*MockMedicineServicer)(nil).CreateMedicine), log, MedicinePayload)
}

// SearchMedicine mocks base method.
func (m *MockMedicineServicer) SearchMedicine(log *zap.Logger, name, organisationID string) ([]dto.SearchMedicineItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchMedicine", log, name, organisationID)
	ret0, _ := ret[0].([]dto.SearchMedicineItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchMedicine indicates an expected call of SearchMedicine.
func (mr *MockMedicineServicerMockRecorder) SearchMedicine(log, name, organisationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchMedicine", reflect.TypeOf((*MockMedicineServicer)(nil).SearchMedicine), log, name, organisationID)
}

// MockSupplierServicer is a mock of SupplierServicer interface.
type MockSupplierServicer struct {
	ctrl     *gomock.Controller
	recorder *MockSupplierServicerMockRecorder
	isgomock struct{}
}

// MockSupplierServicerMockRecorder is the mock recorder for MockSupplierServicer.
type MockSupplierServicerMockRecorder struct {
	mock *MockSupplierServicer
}

// NewMockSupplierServicer creates a new mock instance.
func NewMockSupplierServicer(ctrl *gomock.Controller) *MockSupplierServicer {
	mock := &MockSupplierServicer{ctrl: ctrl}
	mock.recorder = &MockSupplierServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSupplierServicer) EXPECT() *MockSupplierServicerMockRecorder {
	return m.recorder
}

// CretateSupplier mocks base method.
func (m *MockSupplierServicer) CretateSupplier(log *zap.Logger, supplier dto.Supplier) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CretateSupplier", log, supplier)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CretateSupplier indicates an expected call of CretateSupplier.
func (mr *MockSupplierServicerMockRecorder) CretateSupplier(log, supplier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CretateSupplier", reflect.TypeOf((*MockSupplierServicer)(nil).CretateSupplier), log, supplier)
}

// GetSupplierByID mocks base method.
func (m *MockSupplierServicer) GetSupplierByID(log *zap.Logger, supplierID string) (medicine.Supplier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSupplierByID", log, supplierID)
	ret0, _ := ret[0].(medicine.Supplier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSupplierByID indicates an expected call of GetSupplierByID.
func (mr *MockSupplierServicerMockRecorder) GetSupplierByID(log, supplierID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupplierByID", reflect.TypeOf((*MockSupplierServicer)(nil).GetSupplierByID), log, supplierID)
}

// GetSupplierByOrgID mocks base method.
func (m *MockSupplierServicer) GetSupplierByOrgID(log *zap.Logger, req dto.SupplierListReq) ([]dto.SupplierListItem, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSupplierByOrgID", log, req)
	ret0, _ := ret[0].([]dto.SupplierListItem)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSupplierByOrgID indicates an expected call of GetSupplierByOrgID.
func (mr *MockSupplierServicerMockRecorder) GetSupplierByOrgID(log, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupplierByOrgID", reflect.TypeOf((*MockSupplierServicer)(nil).GetSupplierByOrgID), log, req)
}

// GetTotalCount mocks base method.
func (m *MockSupplierServicer) GetTotalCount(log *zap.Logger, organisationID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalCount", log, organisationID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalCount indicates an expected call of GetTotalCount.
func (mr *MockSupplierServicerMockRecorder) GetTotalCount(log, organisationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalCount", reflect.TypeOf((*MockSupplierServicer)(nil).GetTotalCount), log, organisationID)
}
