// Code generated by MockGen. DO NOT EDIT.
// Source: hospital-backend/internal/billing (interfaces: InvoiceServicer)
//
// Generated by this command:
//
//	mockgen -destination=internal/billing/mocks/mock_invoice_servicer.go -package=mocks hospital-backend/internal/billing InvoiceServicer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	dto "hospital-backend/internal/billing/dto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	zap "go.uber.org/zap"
)

// MockInvoiceServicer is a mock of InvoiceServicer interface.
type MockInvoiceServicer struct {
	ctrl     *gomock.Controller
	recorder *MockInvoiceServicerMockRecorder
	isgomock struct{}
}

// MockInvoiceServicerMockRecorder is the mock recorder for MockInvoiceServicer.
type MockInvoiceServicerMockRecorder struct {
	mock *MockInvoiceServicer
}

// NewMockInvoiceServicer creates a new mock instance.
func NewMockInvoiceServicer(ctrl *gomock.Controller) *MockInvoiceServicer {
	mock := &MockInvoiceServicer{ctrl: ctrl}
	mock.recorder = &MockInvoiceServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInvoiceServicer) EXPECT() *MockInvoiceServicerMockRecorder {
	return m.recorder
}

// CreateInvoice mocks base method.
func (m *MockInvoiceServicer) CreateInvoice(log *zap.Logger, reqPayload dto.CheckoutReq) (dto.InvoiceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInvoice", log, reqPayload)
	ret0, _ := ret[0].(dto.InvoiceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInvoice indicates an expected call of CreateInvoice.
func (mr *MockInvoiceServicerMockRecorder) CreateInvoice(log, reqPayload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvoice", reflect.TypeOf((*MockInvoiceServicer)(nil).CreateInvoice), log, reqPayload)
}

// GetBillDetailsByPrescriptionID mocks base method.
func (m *MockInvoiceServicer) GetBillDetailsByPrescriptionID(log *zap.Logger, prescriptionID string) (dto.BillDetailsByPrescriptionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBillDetailsByPrescriptionID", log, prescriptionID)
	ret0, _ := ret[0].(dto.BillDetailsByPrescriptionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBillDetailsByPrescriptionID indicates an expected call of GetBillDetailsByPrescriptionID.
func (mr *MockInvoiceServicerMockRecorder) GetBillDetailsByPrescriptionID(log, prescriptionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBillDetailsByPrescriptionID", reflect.TypeOf((*MockInvoiceServicer)(nil).GetBillDetailsByPrescriptionID), log, prescriptionID)
}

// GetInvoiceByAppointmentID mocks base method.
func (m *MockInvoiceServicer) GetInvoiceByAppointmentID(log *zap.Logger, appointmentID string) (dto.InvoiceByPrescriptionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInvoiceByAppointmentID", log, appointmentID)
	ret0, _ := ret[0].(dto.InvoiceByPrescriptionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInvoiceByAppointmentID indicates an expected call of GetInvoiceByAppointmentID.
func (mr *MockInvoiceServicerMockRecorder) GetInvoiceByAppointmentID(log, appointmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvoiceByAppointmentID", reflect.TypeOf((*MockInvoiceServicer)(nil).GetInvoiceByAppointmentID), log, appointmentID)
}

// GetInvoiceByPrescriptionID mocks base method.
func (m *MockInvoiceServicer) GetInvoiceByPrescriptionID(log *zap.Logger, prescriptionID string) (dto.InvoiceByPrescriptionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInvoiceByPrescriptionID", log, prescriptionID)
	ret0, _ := ret[0].(dto.InvoiceByPrescriptionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInvoiceByPrescriptionID indicates an expected call of GetInvoiceByPrescriptionID.
func (mr *MockInvoiceServicerMockRecorder) GetInvoiceByPrescriptionID(log, prescriptionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvoiceByPrescriptionID", reflect.TypeOf((*MockInvoiceServicer)(nil).GetInvoiceByPrescriptionID), log, prescriptionID)
}

// RetryPaymentLink mocks base method.
func (m *MockInvoiceServicer) RetryPaymentLink(log *zap.Logger, invoiceID, idempotencyKey string) (dto.InvoiceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetryPaymentLink", log, invoiceID, idempotencyKey)
	ret0, _ := ret[0].(dto.InvoiceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RetryPaymentLink indicates an expected call of RetryPaymentLink.
func (mr *MockInvoiceServicerMockRecorder) RetryPaymentLink(log, invoiceID, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetryPaymentLink", reflect.TypeOf((*MockInvoiceServicer)(nil).RetryPaymentLink), log, invoiceID, idempotencyKey)
}
