// Code generated by MockGen. DO NOT EDIT.
// Source: hospital-backend/internal/billing (interfaces: InvoiceRepo,InvoiceItemRepo)
//
// Generated by this command:
//
//	mockgen -destination=internal/billing/mocks/mock_invoice_repository.go -package=mocks hospital-backend/internal/billing InvoiceRepo,InvoiceItemRepo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	billing "hospital-backend/internal/billing"
	dto "hospital-backend/internal/billing/dto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	zap "go.uber.org/zap"
	gorm "gorm.io/gorm"
)

// MockInvoiceRepo is a mock of InvoiceRepo interface.
type MockInvoiceRepo struct {
	ctrl     *gomock.Controller
	recorder *MockInvoiceRepoMockRecorder
	isgomock struct{}
}

// MockInvoiceRepoMockRecorder is the mock recorder for MockInvoiceRepo.
type MockInvoiceRepoMockRecorder struct {
	mock *MockInvoiceRepo
}

// NewMockInvoiceRepo creates a new mock instance.
func NewMockInvoiceRepo(ctrl *gomock.Controller) *MockInvoiceRepo {
	mock := &MockInvoiceRepo{ctrl: ctrl}
	mock.recorder = &MockInvoiceRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInvoiceRepo) EXPECT() *MockInvoiceRepoMockRecorder {
	return m.recorder
}

// CreateInvoice mocks base method.
func (m *MockInvoiceRepo) CreateInvoice(log *zap.Logger, tx *gorm.DB, Inv billing.Invoice) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInvoice", log, tx, Inv)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateInvoice indicates an expected call of CreateInvoice.
func (mr *MockInvoiceRepoMockRecorder) CreateInvoice(log, tx, Inv any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvoice", reflect.TypeOf((*MockInvoiceRepo)(nil).CreateInvoice), log, tx, Inv)
}

// GetBillDetailsByPrescriptionID mocks base method.
func (m *MockInvoiceRepo) GetBillDetailsByPrescriptionID(log *zap.Logger, query string, args ...any) (billing.BillDetailsRow, error) {
	m.ctrl.T.Helper()
	varargs := []any{log, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetBillDetailsByPrescriptionID", varargs...)
	ret0, _ := ret[0].(billing.BillDetailsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBillDetailsByPrescriptionID indicates an expected call of GetBillDetailsByPrescriptionID.
func (mr *MockInvoiceRepoMockRecorder) GetBillDetailsByPrescriptionID(log, query any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{log, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBillDetailsByPrescriptionID", reflect.TypeOf((*MockInvoiceRepo)(nil).GetBillDetailsByPrescriptionID), varargs...)
}

// GetInvoiceByAppointmentID mocks base method.
func (m *MockInvoiceRepo) GetInvoiceByAppointmentID(log *zap.Logger, query string, args ...any) (billing.InvoiceWithPayment, error) {
	m.ctrl.T.Helper()
	varargs := []any{log, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetInvoiceByAppointmentID", varargs...)
	ret0, _ := ret[0].(billing.InvoiceWithPayment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInvoiceByAppointmentID indicates an expected call of GetInvoiceByAppointmentID.
func (mr *MockInvoiceRepoMockRecorder) GetInvoiceByAppointmentID(log, query any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{log, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvoiceByAppointmentID", reflect.TypeOf((*MockInvoiceRepo)(nil).GetInvoiceByAppointmentID), varargs...)
}

// GetInvoiceByID mocks base method.
func (m *MockInvoiceRepo) GetInvoiceByID(log *zap.Logger, invoiceID string) (billing.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInvoiceByID", log, invoiceID)
	ret0, _ := ret[0].(billing.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInvoiceByID indicates an expected call of GetInvoiceByID.
func (mr *MockInvoiceRepoMockRecorder) GetInvoiceByID(log, invoiceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvoiceByID", reflect.TypeOf((*MockInvoiceRepo)(nil).GetInvoiceByID), log, invoiceID)
}

// GetInvoiceByPrescriptionID mocks base method.
func (m *MockInvoiceRepo) GetInvoiceByPrescriptionID(log *zap.Logger, query string, args ...any) (billing.InvoiceWithPayment, error) {
	m.ctrl.T.Helper()
	varargs := []any{log, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetInvoiceByPrescriptionID", varargs...)
	ret0, _ := ret[0].(billing.InvoiceWithPayment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInvoiceByPrescriptionID indicates an expected call of GetInvoiceByPrescriptionID.
func (mr *MockInvoiceRepoMockRecorder) GetInvoiceByPrescriptionID(log, query any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{log, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvoiceByPrescriptionID", reflect.TypeOf((*MockInvoiceRepo)(nil).GetInvoiceByPrescriptionID), varargs...)
}

// UpdateInvoiceStatus mocks base method.
func (m *MockInvoiceRepo) UpdateInvoiceStatus(log *zap.Logger, tx *gorm.DB, invoiceID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInvoiceStatus", log, tx, invoiceID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateInvoiceStatus indicates an expected call of UpdateInvoiceStatus.
func (mr *MockInvoiceRepoMockRecorder) UpdateInvoiceStatus(log, tx, invoiceID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInvoiceStatus", reflect.TypeOf((*MockInvoiceRepo)(nil).UpdateInvoiceStatus), log, tx, invoiceID, status)
}

// MockInvoiceItemRepo is a mock of InvoiceItemRepo interface.
type MockInvoiceItemRepo struct {
	ctrl     *gomock.Controller
	recorder *MockInvoiceItemRepoMockRecorder
	isgomock struct{}
}

// MockInvoiceItemRepoMockRecorder is the mock recorder for MockInvoiceItemRepo.
type MockInvoiceItemRepoMockRecorder struct {
	mock *MockInvoiceItemRepo
}

// NewMockInvoiceItemRepo creates a new mock instance.
func NewMockInvoiceItemRepo(ctrl *gomock.Controller) *MockInvoiceItemRepo {
	mock := &MockInvoiceItemRepo{ctrl: ctrl}
	mock.recorder = &MockInvoiceItemRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInvoiceItemRepo) EXPECT() *MockInvoiceItemRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockInvoiceItemRepo) Create(log *zap.Logger, tx *gorm.DB, InvItem []billing.InvoiceItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", log, tx, InvItem)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockInvoiceItemRepoMockRecorder) Create(log, tx, InvItem any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockInvoiceItemRepo)(nil).Create), log, tx, InvItem)
}

// GetInvoiceItemsByInvoiceID mocks base method.
func (m *MockInvoiceItemRepo) GetInvoiceItemsByInvoiceID(log *zap.Logger, query string, args ...any) ([]dto.MedInvoiceItemResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{log, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetInvoiceItemsByInvoiceID", varargs...)
	ret0, _ := ret[0].([]dto.MedInvoiceItemResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInvoiceItemsByInvoiceID indicates an expected call of GetInvoiceItemsByInvoiceID.
func (mr *MockInvoiceItemRepoMockRecorder) GetInvoiceItemsByInvoiceID(log, query any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{log, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvoiceItemsByInvoiceID", reflect.TypeOf((*MockInvoiceItemRepo)(nil).GetInvoiceItemsByInvoiceID), varargs...)
}
