// Code generated by MockGen. DO NOT EDIT.
// Source: hospital-backend/internal/appointments (interfaces: AppointmentServicer)
//
// Generated by this command:
//
//	mockgen -destination=internal/appointments/mocks/mock_appointment_servicer.go -package=mocks hospital-backend/internal/appointments AppointmentServicer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	dto "hospital-backend/internal/appointments/dto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	zap "go.uber.org/zap"
)

// MockAppointmentServicer is a mock of AppointmentServicer interface.
type MockAppointmentServicer struct {
	ctrl     *gomock.Controller
	recorder *MockAppointmentServicerMockRecorder
	isgomock struct{}
}

// MockAppointmentServicerMockRecorder is the mock recorder for MockAppointmentServicer.
type MockAppointmentServicerMockRecorder struct {
	mock *MockAppointmentServicer
}

// NewMockAppointmentServicer creates a new mock instance.
func NewMockAppointmentServicer(ctrl *gomock.Controller) *MockAppointmentServicer {
	mock := &MockAppointmentServicer{ctrl: ctrl}
	mock.recorder = &MockAppointmentServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppointmentServicer) EXPECT() *MockAppointmentServicerMockRecorder {
	return m.recorder
}

// CreateApptmnt mocks base method.
func (m *MockAppointmentServicer) CreateApptmnt(log *zap.Logger, requestPayload dto.NewApptmnt) (dto.NewApptmntResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateApptmnt", log, requestPayload)
	ret0, _ := ret[0].(dto.NewApptmntResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateApptmnt indicates an expected call of CreateApptmnt.
func (mr *MockAppointmentServicerMockRecorder) CreateApptmnt(log, requestPayload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateApptmnt", reflect.TypeOf((*MockAppointmentServicer)(nil).CreateApptmnt), log, requestPayload)
}

// GetAppointmentByPatientID mocks base method.
func (m *MockAppointmentServicer) GetAppointmentByPatientID(log *zap.Logger, reqModel dto.PatientAppntment) (dto.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppointmentByPatientID", log, reqModel)
	ret0, _ := ret[0].(dto.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppointmentByPatientID indicates an expected call of GetAppointmentByPatientID.
func (mr *MockAppointmentServicerMockRecorder) GetAppointmentByPatientID(log, reqModel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppointmentByPatientID", reflect.TypeOf((*MockAppointmentServicer)(nil).GetAppointmentByPatientID), log, reqModel)
}

// GetAppointmentPreview mocks base method.
func (m *MockAppointmentServicer) GetAppointmentPreview(log *zap.Logger, organisationID, appointmentID string) (dto.AppointmentDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppointmentPreview", log, organisationID, appointmentID)
	ret0, _ := ret[0].(dto.AppointmentDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppointmentPreview indicates an expected call of GetAppointmentPreview.
func (mr *MockAppointmentServicerMockRecorder) GetAppointmentPreview(log, organisationID, appointmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppointmentPreview", reflect.TypeOf((*MockAppointmentServicer)(nil).GetAppointmentPreview), log, organisationID, appointmentID)
}

// GetAppointmentsByOrgID mocks base method.
func (m *MockAppointmentServicer) GetAppointmentsByOrgID(log *zap.Logger, reqModel dto.GetDataReq) ([]dto.AppointmentList, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppointmentsByOrgID", log, reqModel)
	ret0, _ := ret[0].([]dto.AppointmentList)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAppointmentsByOrgID indicates an expected call of GetAppointmentsByOrgID.
func (mr *MockAppointmentServicerMockRecorder) GetAppointmentsByOrgID(log, reqModel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppointmentsByOrgID", reflect.TypeOf((*MockAppointmentServicer)(nil).GetAppointmentsByOrgID), log, reqModel)
}

// GetAppointmentsGroupedByStatus mocks base method.
func (m *MockAppointmentServicer) GetAppointmentsGroupedByStatus(log *zap.Logger, organisationID string) (dto.AppointmentStatusCounts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppointmentsGroupedByStatus", log, organisationID)
	ret0, _ := ret[0].(dto.AppointmentStatusCounts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppointmentsGroupedByStatus indicates an expected call of GetAppointmentsGroupedByStatus.
func (mr *MockAppointmentServicerMockRecorder) GetAppointmentsGroupedByStatus(log, organisationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppointmentsGroupedByStatus", reflect.TypeOf((*MockAppointmentServicer)(nil).GetAppointmentsGroupedByStatus), log, organisationID)
}

// GetSlots mocks base method.
func (m *MockAppointmentServicer) GetSlots(log *zap.Logger, doctorID, organisationID, date string) (dto.SlotResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSlots", log, doctorID, organisationID, date)
	ret0, _ := ret[0].(dto.SlotResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSlots indicates an expected call of GetSlots.
func (mr *MockAppointmentServicerMockRecorder) GetSlots(log, doctorID, organisationID, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSlots", reflect.TypeOf((*MockAppointmentServicer)(nil).GetSlots), log, doctorID, organisationID, date)
}

// UpdateStatus mocks base method.
func (m *MockAppointmentServicer) UpdateStatus(log *zap.Logger, updateReq dto.UpdateStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", log, updateReq)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockAppointmentServicerMockRecorder) UpdateStatus(log, updateReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockAppointmentServicer)(nil).UpdateStatus), log, updateReq)
}
