// Code generated by MockGen. DO NOT EDIT.
// Source: hospital-backend/internal/appointments (interfaces: AppointmentRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/appointments/mocks/mock_appointment_repository.go -package=mocks hospital-backend/internal/appointments AppointmentRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	appointments "hospital-backend/internal/appointments"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	zap "go.uber.org/zap"
	gorm "gorm.io/gorm"
)

// MockAppointmentRepository is a mock of AppointmentRepository interface.
type MockAppointmentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAppointmentRepositoryMockRecorder
	isgomock struct{}
}

// MockAppointmentRepositoryMockRecorder is the mock recorder for MockAppointmentRepository.
type MockAppointmentRepositoryMockRecorder struct {
	mock *MockAppointmentRepository
}

// NewMockAppointmentRepository creates a new mock instance.
func NewMockAppointmentRepository(ctrl *gomock.Controller) *MockAppointmentRepository {
	mock := &MockAppointmentRepository{ctrl: ctrl}
	mock.recorder = &MockAppointmentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppointmentRepository) EXPECT() *MockAppointmentRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAppointmentRepository) Create(log *zap.Logger, appointment *appointments.Appointment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", log, appointment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAppointmentRepositoryMockRecorder) Create(log, appointment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAppointmentRepository)(nil).Create), log, appointment)
}

// FindManyByOrganisationID mocks base method.
func (m *MockAppointmentRepository) FindManyByOrganisationID(log *zap.Logger, query string, cond ...any) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	varargs := []any{log, query}
	for _, a := range cond {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindManyByOrganisationID", varargs...)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindManyByOrganisationID indicates an expected call of FindManyByOrganisationID.
func (mr *MockAppointmentRepositoryMockRecorder) FindManyByOrganisationID(log, query any, cond ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{log, query}, cond...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindManyByOrganisationID", reflect.TypeOf((*MockAppointmentRepository)(nil).FindManyByOrganisationID), varargs...)
}

// GetAppointmentByID mocks base method.
func (m *MockAppointmentRepository) GetAppointmentByID(log *zap.Logger, appointmentID string) (appointments.Appointment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppointmentByID", log, appointmentID)
	ret0, _ := ret[0].(appointments.Appointment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppointmentByID indicates an expected call of GetAppointmentByID.
func (mr *MockAppointmentRepositoryMockRecorder) GetAppointmentByID(log, appointmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppointmentByID", reflect.TypeOf((*MockAppointmentRepository)(nil).GetAppointmentByID), log, appointmentID)
}

// GetAppointmentByPatientID mocks base method.
func (m *MockAppointmentRepository) GetAppointmentByPatientID(log *zap.Logger, query string, cond ...any) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	varargs := []any{log, query}
	for _, a := range cond {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAppointmentByPatientID", varargs...)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppointmentByPatientID indicates an expected call of GetAppointmentByPatientID.
func (mr *MockAppointmentRepositoryMockRecorder) GetAppointmentByPatientID(log, query any, cond ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{log, query}, cond...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppointmentByPatientID", reflect.TypeOf((*MockAppointmentRepository)(nil).GetAppointmentByPatientID), varargs...)
}

// GetAppointmentByPatientIDCount mocks base method.
func (m *MockAppointmentRepository) GetAppointmentByPatientIDCount(log *zap.Logger, cond ...any) (int64, error) {
	m.ctrl.T.Helper()
	varargs := []any{log}
	for _, a := range cond {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAppointmentByPatientIDCount", varargs...)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppointmentByPatientIDCount indicates an expected call of GetAppointmentByPatientIDCount.
func (mr *MockAppointmentRepositoryMockRecorder) GetAppointmentByPatientIDCount(log any, cond ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{log}, cond...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppointmentByPatientIDCount", reflect.TypeOf((*MockAppointmentRepository)(nil).GetAppointmentByPatientIDCount), varargs...)
}

// GetAppointmentCount mocks base method.
func (m *MockAppointmentRepository) GetAppointmentCount(log *zap.Logger, query string, cond ...any) (int64, error) {
	m.ctrl.T.Helper()
	varargs := []any{log, query}
	for _, a := range cond {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAppointmentCount", varargs...)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppointmentCount indicates an expected call of GetAppointmentCount.
func (mr *MockAppointmentRepositoryMockRecorder) GetAppointmentCount(log, query any, cond ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{log, query}, cond...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppointmentCount", reflect.TypeOf((*MockAppointmentRepository)(nil).GetAppointmentCount), varargs...)
}

// GetAppointmentsByIDs mocks base method.
func (m *MockAppointmentRepository) GetAppointmentsByIDs(log *zap.Logger, query string, cond ...any) ([]appointments.Appointment, error) {
	m.ctrl.T.Helper()
	varargs := []any{log, query}
	for _, a := range cond {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAppointmentsByIDs", varargs...)
	ret0, _ := ret[0].([]appointments.Appointment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppointmentsByIDs indicates an expected call of GetAppointmentsByIDs.
func (mr *MockAppointmentRepositoryMockRecorder) GetAppointmentsByIDs(log, query any, cond ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{log, query}, cond...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppointmentsByIDs", reflect.TypeOf((*MockAppointmentRepository)(nil).GetAppointmentsByIDs), varargs...)
}

// GetAppointmentsPreview mocks base method.
func (m *MockAppointmentRepository) GetAppointmentsPreview(log *zap.Logger, query string, cond ...any) (map[string]any, error) {
	m.ctrl.T.Helper()
	varargs := []any{log, query}
	for _, a := range cond {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAppointmentsPreview", varargs...)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppointmentsPreview indicates an expected call of GetAppointmentsPreview.
func (mr *MockAppointmentRepositoryMockRecorder) GetAppointmentsPreview(log, query any, cond ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{log, query}, cond...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppointmentsPreview", reflect.TypeOf((*MockAppointmentRepository)(nil).GetAppointmentsPreview), varargs...)
}

// GetNotificationsDetails mocks base method.
func (m *MockAppointmentRepository) GetNotificationsDetails(log *zap.Logger, query string, cond ...any) (map[string]any, error) {
	m.ctrl.T.Helper()
	varargs := []any{log, query}
	for _, a := range cond {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetNotificationsDetails", varargs...)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotificationsDetails indicates an expected call of GetNotificationsDetails.
func (mr *MockAppointmentRepositoryMockRecorder) GetNotificationsDetails(log, query any, cond ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{log, query}, cond...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotificationsDetails", reflect.TypeOf((*MockAppointmentRepository)(nil).GetNotificationsDetails), varargs...)
}

// GetTotalAppointmentsByOrgID mocks base method.
func (m *MockAppointmentRepository) GetTotalAppointmentsByOrgID(log *zap.Logger, query string, cond ...any) (int, error) {
	m.ctrl.T.Helper()
	varargs := []any{log, query}
	for _, a := range cond {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTotalAppointmentsByOrgID", varargs...)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalAppointmentsByOrgID indicates an expected call of GetTotalAppointmentsByOrgID.
func (mr *MockAppointmentRepositoryMockRecorder) GetTotalAppointmentsByOrgID(log, query any, cond ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{log, query}, cond...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalAppointmentsByOrgID", reflect.TypeOf((*MockAppointmentRepository)(nil).GetTotalAppointmentsByOrgID), varargs...)
}

// UpdateStatus mocks base method.
func (m *MockAppointmentRepository) UpdateStatus(log *zap.Logger, tx *gorm.DB, value any, cond ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{log, tx, value}
	for _, a := range cond {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateStatus", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockAppointmentRepositoryMockRecorder) UpdateStatus(log, tx, value any, cond ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{log, tx, value}, cond...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockAppointmentRepository)(nil).UpdateStatus), varargs...)
}
