// Code generated by MockGen. DO NOT EDIT.
// Source: hospital-backend/internal/organisation (interfaces: PermissionCatalogLookup,RoleSeeder,DepartmentSeeder,RolePermissionSeeder)
//
// Generated by this command:
//
//	mockgen -destination=internal/organisation/mocks/mock_signup_deps.go -package=mocks hospital-backend/internal/organisation PermissionCatalogLookup,RoleSeeder,DepartmentSeeder,RolePermissionSeeder
//

// Package mocks is a generated GoMock package.
package mocks

import (
	modules "hospital-backend/internal/modules"
	permissions "hospital-backend/internal/permissions"
	roles "hospital-backend/internal/roles"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockPermissionCatalogLookup is a mock of PermissionCatalogLookup interface.
type MockPermissionCatalogLookup struct {
	ctrl     *gomock.Controller
	recorder *MockPermissionCatalogLookupMockRecorder
	isgomock struct{}
}

// MockPermissionCatalogLookupMockRecorder is the mock recorder for MockPermissionCatalogLookup.
type MockPermissionCatalogLookupMockRecorder struct {
	mock *MockPermissionCatalogLookup
}

// NewMockPermissionCatalogLookup creates a new mock instance.
func NewMockPermissionCatalogLookup(ctrl *gomock.Controller) *MockPermissionCatalogLookup {
	mock := &MockPermissionCatalogLookup{ctrl: ctrl}
	mock.recorder = &MockPermissionCatalogLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPermissionCatalogLookup) EXPECT() *MockPermissionCatalogLookupMockRecorder {
	return m.recorder
}

// FindMany mocks base method.
func (m *MockPermissionCatalogLookup) FindMany() ([]modules.Modules, []permissions.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMany")
	ret0, _ := ret[0].([]modules.Modules)
	ret1, _ := ret[1].([]permissions.Permission)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindMany indicates an expected call of FindMany.
func (mr *MockPermissionCatalogLookupMockRecorder) FindMany() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMany", reflect.TypeOf((*MockPermissionCatalogLookup)(nil).FindMany))
}

// MockRoleSeeder is a mock of RoleSeeder interface.
type MockRoleSeeder struct {
	ctrl     *gomock.Controller
	recorder *MockRoleSeederMockRecorder
	isgomock struct{}
}

// MockRoleSeederMockRecorder is the mock recorder for MockRoleSeeder.
type MockRoleSeederMockRecorder struct {
	mock *MockRoleSeeder
}

// NewMockRoleSeeder creates a new mock instance.
func NewMockRoleSeeder(ctrl *gomock.Controller) *MockRoleSeeder {
	mock := &MockRoleSeeder{ctrl: ctrl}
	mock.recorder = &MockRoleSeederMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleSeeder) EXPECT() *MockRoleSeederMockRecorder {
	return m.recorder
}

// InsertMany mocks base method.
func (m *MockRoleSeeder) InsertMany(tx *gorm.DB, organisationID string) ([]roles.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertMany", tx, organisationID)
	ret0, _ := ret[0].([]roles.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertMany indicates an expected call of InsertMany.
func (mr *MockRoleSeederMockRecorder) InsertMany(tx, organisationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertMany", reflect.TypeOf((*MockRoleSeeder)(nil).InsertMany), tx, organisationID)
}

// MockDepartmentSeeder is a mock of DepartmentSeeder interface.
type MockDepartmentSeeder struct {
	ctrl     *gomock.Controller
	recorder *MockDepartmentSeederMockRecorder
	isgomock struct{}
}

// MockDepartmentSeederMockRecorder is the mock recorder for MockDepartmentSeeder.
type MockDepartmentSeederMockRecorder struct {
	mock *MockDepartmentSeeder
}

// NewMockDepartmentSeeder creates a new mock instance.
func NewMockDepartmentSeeder(ctrl *gomock.Controller) *MockDepartmentSeeder {
	mock := &MockDepartmentSeeder{ctrl: ctrl}
	mock.recorder = &MockDepartmentSeederMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDepartmentSeeder) EXPECT() *MockDepartmentSeederMockRecorder {
	return m.recorder
}

// InsertMany mocks base method.
func (m *MockDepartmentSeeder) InsertMany(tx *gorm.DB, organisationID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertMany", tx, organisationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertMany indicates an expected call of InsertMany.
func (mr *MockDepartmentSeederMockRecorder) InsertMany(tx, organisationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertMany", reflect.TypeOf((*MockDepartmentSeeder)(nil).InsertMany), tx, organisationID)
}

// MockRolePermissionSeeder is a mock of RolePermissionSeeder interface.
type MockRolePermissionSeeder struct {
	ctrl     *gomock.Controller
	recorder *MockRolePermissionSeederMockRecorder
	isgomock struct{}
}

// MockRolePermissionSeederMockRecorder is the mock recorder for MockRolePermissionSeeder.
type MockRolePermissionSeederMockRecorder struct {
	mock *MockRolePermissionSeeder
}

// NewMockRolePermissionSeeder creates a new mock instance.
func NewMockRolePermissionSeeder(ctrl *gomock.Controller) *MockRolePermissionSeeder {
	mock := &MockRolePermissionSeeder{ctrl: ctrl}
	mock.recorder = &MockRolePermissionSeederMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRolePermissionSeeder) EXPECT() *MockRolePermissionSeederMockRecorder {
	return m.recorder
}

// InsertMany mocks base method.
func (m *MockRolePermissionSeeder) InsertMany(tx *gorm.DB, roleArr []roles.Role, permissionsArr []permissions.Permission, modulesArr []modules.Modules, organisationID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertMany", tx, roleArr, permissionsArr, modulesArr, organisationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertMany indicates an expected call of InsertMany.
func (mr *MockRolePermissionSeederMockRecorder) InsertMany(tx, roleArr, permissionsArr, modulesArr, organisationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertMany", reflect.TypeOf((*MockRolePermissionSeeder)(nil).InsertMany), tx, roleArr, permissionsArr, modulesArr, organisationID)
}
