// Code generated by MockGen. DO NOT EDIT.
// Source: hospital-backend/internal/organisation (interfaces: OrganisationRepo)
//
// Generated by this command:
//
//	mockgen -destination=internal/organisation/mocks/mock_organisation_repository.go -package=mocks hospital-backend/internal/organisation OrganisationRepo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	organisation "hospital-backend/internal/organisation"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	zap "go.uber.org/zap"
	gorm "gorm.io/gorm"
)

// MockOrganisationRepo is a mock of OrganisationRepo interface.
type MockOrganisationRepo struct {
	ctrl     *gomock.Controller
	recorder *MockOrganisationRepoMockRecorder
	isgomock struct{}
}

// MockOrganisationRepoMockRecorder is the mock recorder for MockOrganisationRepo.
type MockOrganisationRepoMockRecorder struct {
	mock *MockOrganisationRepo
}

// NewMockOrganisationRepo creates a new mock instance.
func NewMockOrganisationRepo(ctrl *gomock.Controller) *MockOrganisationRepo {
	mock := &MockOrganisationRepo{ctrl: ctrl}
	mock.recorder = &MockOrganisationRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrganisationRepo) EXPECT() *MockOrganisationRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOrganisationRepo) Create(log *zap.Logger, tx *gorm.DB, arg2 organisation.Organisation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", log, tx, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOrganisationRepoMockRecorder) Create(log, tx, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrganisationRepo)(nil).Create), log, tx, arg2)
}

// GetOrganisationByID mocks base method.
func (m *MockOrganisationRepo) GetOrganisationByID(log *zap.Logger, organisationID string) (organisation.Organisation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrganisationByID", log, organisationID)
	ret0, _ := ret[0].(organisation.Organisation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganisationByID indicates an expected call of GetOrganisationByID.
func (mr *MockOrganisationRepoMockRecorder) GetOrganisationByID(log, organisationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganisationByID", reflect.TypeOf((*MockOrganisationRepo)(nil).GetOrganisationByID), log, organisationID)
}

// Update mocks base method.
func (m *MockOrganisationRepo) Update(log *zap.Logger, organisationID string, update map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", log, organisationID, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockOrganisationRepoMockRecorder) Update(log, organisationID, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockOrganisationRepo)(nil).Update), log, organisationID, update)
}

// UpdateLocationByID mocks base method.
func (m *MockOrganisationRepo) UpdateLocationByID(log *zap.Logger, arg1 *organisation.Organisation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLocationByID", log, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLocationByID indicates an expected call of UpdateLocationByID.
func (mr *MockOrganisationRepoMockRecorder) UpdateLocationByID(log, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLocationByID", reflect.TypeOf((*MockOrganisationRepo)(nil).UpdateLocationByID), log, arg1)
}
