// Code generated by MockGen. DO NOT EDIT.
// Source: hospital-backend/internal/organisation (interfaces: OrganisationServicer)
//
// Generated by this command:
//
//	mockgen -destination=internal/organisation/mocks/mock_organisation_servicer.go -package=mocks hospital-backend/internal/organisation OrganisationServicer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	organisation "hospital-backend/internal/organisation"
	dto "hospital-backend/internal/organisation/DTO"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	zap "go.uber.org/zap"
)

// MockOrganisationServicer is a mock of OrganisationServicer interface.
type MockOrganisationServicer struct {
	ctrl     *gomock.Controller
	recorder *MockOrganisationServicerMockRecorder
	isgomock struct{}
}

// MockOrganisationServicerMockRecorder is the mock recorder for MockOrganisationServicer.
type MockOrganisationServicerMockRecorder struct {
	mock *MockOrganisationServicer
}

// NewMockOrganisationServicer creates a new mock instance.
func NewMockOrganisationServicer(ctrl *gomock.Controller) *MockOrganisationServicer {
	mock := &MockOrganisationServicer{ctrl: ctrl}
	mock.recorder = &MockOrganisationServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrganisationServicer) EXPECT() *MockOrganisationServicerMockRecorder {
	return m.recorder
}

// CreateOrganisation mocks base method.
func (m *MockOrganisationServicer) CreateOrganisation(log *zap.Logger, payloadRequest dto.OrganisationPayload) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrganisation", log, payloadRequest)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrganisation indicates an expected call of CreateOrganisation.
func (mr *MockOrganisationServicerMockRecorder) CreateOrganisation(log, payloadRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrganisation", reflect.TypeOf((*MockOrganisationServicer)(nil).CreateOrganisation), log, payloadRequest)
}

// GetOrgByID mocks base method.
func (m *MockOrganisationServicer) GetOrgByID(log *zap.Logger, organisationID string) (organisation.Organisation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrgByID", log, organisationID)
	ret0, _ := ret[0].(organisation.Organisation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrgByID indicates an expected call of GetOrgByID.
func (mr *MockOrganisationServicerMockRecorder) GetOrgByID(log, organisationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrgByID", reflect.TypeOf((*MockOrganisationServicer)(nil).GetOrgByID), log, organisationID)
}

// Update mocks base method.
func (m *MockOrganisationServicer) Update(log *zap.Logger, organisationID string, payload dto.OrganisationPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", log, organisationID, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockOrganisationServicerMockRecorder) Update(log, organisationID, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockOrganisationServicer)(nil).Update), log, organisationID, payload)
}

// UpdateOrganisationLoc mocks base method.
func (m *MockOrganisationServicer) UpdateOrganisationLoc(log *zap.Logger, payloadReques dto.OrganisationPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrganisationLoc", log, payloadReques)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrganisationLoc indicates an expected call of UpdateOrganisationLoc.
func (mr *MockOrganisationServicerMockRecorder) UpdateOrganisationLoc(log, payloadReques any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrganisationLoc", reflect.TypeOf((*MockOrganisationServicer)(nil).UpdateOrganisationLoc), log, payloadReques)
}
