// Code generated by MockGen. DO NOT EDIT.
// Source: hospital-backend/internal/license (interfaces: LicenseServicer)
//
// Generated by this command:
//
//	mockgen -destination=internal/license/mocks/mock_license_servicer.go -package=mocks hospital-backend/internal/license LicenseServicer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	zap "go.uber.org/zap"
)

// MockLicenseServicer is a mock of LicenseServicer interface.
type MockLicenseServicer struct {
	ctrl     *gomock.Controller
	recorder *MockLicenseServicerMockRecorder
	isgomock struct{}
}

// MockLicenseServicerMockRecorder is the mock recorder for MockLicenseServicer.
type MockLicenseServicerMockRecorder struct {
	mock *MockLicenseServicer
}

// NewMockLicenseServicer creates a new mock instance.
func NewMockLicenseServicer(ctrl *gomock.Controller) *MockLicenseServicer {
	mock := &MockLicenseServicer{ctrl: ctrl}
	mock.recorder = &MockLicenseServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLicenseServicer) EXPECT() *MockLicenseServicerMockRecorder {
	return m.recorder
}

// VerifyLicense mocks base method.
func (m *MockLicenseServicer) VerifyLicense(log *zap.Logger, organisationID, licensekey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyLicense", log, organisationID, licensekey)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyLicense indicates an expected call of VerifyLicense.
func (mr *MockLicenseServicerMockRecorder) VerifyLicense(log, organisationID, licensekey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyLicense", reflect.TypeOf((*MockLicenseServicer)(nil).VerifyLicense), log, organisationID, licensekey)
}
