// Code generated by MockGen. DO NOT EDIT.
// Source: hospital-backend/internal/license (interfaces: LicenseRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/license/mocks/mock_license_repository.go -package=mocks hospital-backend/internal/license LicenseRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	license "hospital-backend/internal/license"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	zap "go.uber.org/zap"
	gorm "gorm.io/gorm"
)

// MockLicenseRepository is a mock of LicenseRepository interface.
type MockLicenseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLicenseRepositoryMockRecorder
	isgomock struct{}
}

// MockLicenseRepositoryMockRecorder is the mock recorder for MockLicenseRepository.
type MockLicenseRepositoryMockRecorder struct {
	mock *MockLicenseRepository
}

// NewMockLicenseRepository creates a new mock instance.
func NewMockLicenseRepository(ctrl *gomock.Controller) *MockLicenseRepository {
	mock := &MockLicenseRepository{ctrl: ctrl}
	mock.recorder = &MockLicenseRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLicenseRepository) EXPECT() *MockLicenseRepositoryMockRecorder {
	return m.recorder
}

// CreateLicense mocks base method.
func (m *MockLicenseRepository) CreateLicense(log *zap.Logger, tx *gorm.DB, lic *license.License) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLicense", log, tx, lic)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateLicense indicates an expected call of CreateLicense.
func (mr *MockLicenseRepositoryMockRecorder) CreateLicense(log, tx, lic any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLicense", reflect.TypeOf((*MockLicenseRepository)(nil).CreateLicense), log, tx, lic)
}

// GetLicense mocks base method.
func (m *MockLicenseRepository) GetLicense(log *zap.Logger, organisationID, licensekey string) (*license.License, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLicense", log, organisationID, licensekey)
	ret0, _ := ret[0].(*license.License)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLicense indicates an expected call of GetLicense.
func (mr *MockLicenseRepositoryMockRecorder) GetLicense(log, organisationID, licensekey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLicense", reflect.TypeOf((*MockLicenseRepository)(nil).GetLicense), log, organisationID, licensekey)
}
