// Code generated by MockGen. DO NOT EDIT.
// Source: hospital-backend/internal/admins (interfaces: OrganisationScheduleRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/admins/mocks/mock_organisation_schedule_repository.go -package=mocks hospital-backend/internal/admins OrganisationScheduleRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	admins "hospital-backend/internal/admins"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	zap "go.uber.org/zap"
)

// MockOrganisationScheduleRepository is a mock of OrganisationScheduleRepository interface.
type MockOrganisationScheduleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrganisationScheduleRepositoryMockRecorder
	isgomock struct{}
}

// MockOrganisationScheduleRepositoryMockRecorder is the mock recorder for MockOrganisationScheduleRepository.
type MockOrganisationScheduleRepositoryMockRecorder struct {
	mock *MockOrganisationScheduleRepository
}

// NewMockOrganisationScheduleRepository creates a new mock instance.
func NewMockOrganisationScheduleRepository(ctrl *gomock.Controller) *MockOrganisationScheduleRepository {
	mock := &MockOrganisationScheduleRepository{ctrl: ctrl}
	mock.recorder = &MockOrganisationScheduleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrganisationScheduleRepository) EXPECT() *MockOrganisationScheduleRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOrganisationScheduleRepository) Create(log *zap.Logger, schedule *admins.OrganisationSchedule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", log, schedule)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOrganisationScheduleRepositoryMockRecorder) Create(log, schedule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrganisationScheduleRepository)(nil).Create), log, schedule)
}

// GetByOrganisationID mocks base method.
func (m *MockOrganisationScheduleRepository) GetByOrganisationID(log *zap.Logger, query string, cond ...any) (admins.OrganisationSchedule, error) {
	m.ctrl.T.Helper()
	varargs := []any{log, query}
	for _, a := range cond {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetByOrganisationID", varargs...)
	ret0, _ := ret[0].(admins.OrganisationSchedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOrganisationID indicates an expected call of GetByOrganisationID.
func (mr *MockOrganisationScheduleRepositoryMockRecorder) GetByOrganisationID(log, query any, cond ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{log, query}, cond...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOrganisationID", reflect.TypeOf((*MockOrganisationScheduleRepository)(nil).GetByOrganisationID), varargs...)
}
