// Code generated by MockGen. DO NOT EDIT.
// Source: hospital-backend/internal/admins (interfaces: OrganisationScheduleServicer)
//
// Generated by this command:
//
//	mockgen -destination=internal/admins/mocks/mock_organisation_schedule_servicer.go -package=mocks hospital-backend/internal/admins OrganisationScheduleServicer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	dto "hospital-backend/internal/admins/dto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	zap "go.uber.org/zap"
)

// MockOrganisationScheduleServicer is a mock of OrganisationScheduleServicer interface.
type MockOrganisationScheduleServicer struct {
	ctrl     *gomock.Controller
	recorder *MockOrganisationScheduleServicerMockRecorder
	isgomock struct{}
}

// MockOrganisationScheduleServicerMockRecorder is the mock recorder for MockOrganisationScheduleServicer.
type MockOrganisationScheduleServicerMockRecorder struct {
	mock *MockOrganisationScheduleServicer
}

// NewMockOrganisationScheduleServicer creates a new mock instance.
func NewMockOrganisationScheduleServicer(ctrl *gomock.Controller) *MockOrganisationScheduleServicer {
	mock := &MockOrganisationScheduleServicer{ctrl: ctrl}
	mock.recorder = &MockOrganisationScheduleServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrganisationScheduleServicer) EXPECT() *MockOrganisationScheduleServicerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOrganisationScheduleServicer) Create(log *zap.Logger, reqModel dto.OrgScheduleReq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", log, reqModel)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOrganisationScheduleServicerMockRecorder) Create(log, reqModel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrganisationScheduleServicer)(nil).Create), log, reqModel)
}

// GetScheduleByOrganisationID mocks base method.
func (m *MockOrganisationScheduleServicer) GetScheduleByOrganisationID(log *zap.Logger, organisationID string) (dto.GetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScheduleByOrganisationID", log, organisationID)
	ret0, _ := ret[0].(dto.GetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScheduleByOrganisationID indicates an expected call of GetScheduleByOrganisationID.
func (mr *MockOrganisationScheduleServicerMockRecorder) GetScheduleByOrganisationID(log, organisationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScheduleByOrganisationID", reflect.TypeOf((*MockOrganisationScheduleServicer)(nil).GetScheduleByOrganisationID), log, organisationID)
}
