// Code generated by MockGen. DO NOT EDIT.
// Source: hospital-backend/internal/notifications/repository (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=internal/notifications/mocks/mock_notification_repository.go -package=mocks hospital-backend/internal/notifications/repository Repository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	notifications "hospital-backend/internal/notifications"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, n *notifications.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, n)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, n)
}

// CreateAttempt mocks base method.
func (m *MockRepository) CreateAttempt(ctx context.Context, attempt *notifications.NotificationAttempts) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAttempt", ctx, attempt)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAttempt indicates an expected call of CreateAttempt.
func (mr *MockRepositoryMockRecorder) CreateAttempt(ctx, attempt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAttempt", reflect.TypeOf((*MockRepository)(nil).CreateAttempt), ctx, attempt)
}

// GetPending mocks base method.
func (m *MockRepository) GetPending(ctx context.Context, limit int) ([]notifications.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPending", ctx, limit)
	ret0, _ := ret[0].([]notifications.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPending indicates an expected call of GetPending.
func (mr *MockRepositoryMockRecorder) GetPending(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPending", reflect.TypeOf((*MockRepository)(nil).GetPending), ctx, limit)
}

// MarkFailed mocks base method.
func (m *MockRepository) MarkFailed(ctx context.Context, id string, nextRetryAt time.Time, err error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFailed", ctx, id, nextRetryAt, err)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkFailed indicates an expected call of MarkFailed.
func (mr *MockRepositoryMockRecorder) MarkFailed(ctx, id, nextRetryAt, err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFailed", reflect.TypeOf((*MockRepository)(nil).MarkFailed), ctx, id, nextRetryAt, err)
}

// MarkProcessing mocks base method.
func (m *MockRepository) MarkProcessing(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkProcessing", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkProcessing indicates an expected call of MarkProcessing.
func (mr *MockRepositoryMockRecorder) MarkProcessing(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkProcessing", reflect.TypeOf((*MockRepository)(nil).MarkProcessing), ctx, id)
}

// MarkSent mocks base method.
func (m *MockRepository) MarkSent(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkSent", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkSent indicates an expected call of MarkSent.
func (mr *MockRepositoryMockRecorder) MarkSent(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkSent", reflect.TypeOf((*MockRepository)(nil).MarkSent), ctx, id)
}
