// Code generated by MockGen. DO NOT EDIT.
// Source: hospital-backend/internal/payments/providers (interfaces: Provider,IPaymentFactory)
//
// Generated by this command:
//
//	mockgen -destination=internal/payments/providers/mocks/mock_provider.go -package=mocks hospital-backend/internal/payments/providers Provider,IPaymentFactory
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	dto "hospital-backend/internal/payments/dto"
	providers "hospital-backend/internal/payments/providers"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// CreatePayment mocks base method.
func (m *MockProvider) CreatePayment(ctx context.Context, req dto.CreatePaymentCommand) (dto.CreatePaymentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePayment", ctx, req)
	ret0, _ := ret[0].(dto.CreatePaymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePayment indicates an expected call of CreatePayment.
func (mr *MockProviderMockRecorder) CreatePayment(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePayment", reflect.TypeOf((*MockProvider)(nil).CreatePayment), ctx, req)
}

// Name mocks base method.
func (m *MockProvider) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockProviderMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockProvider)(nil).Name))
}

// ParseWebhookEvent mocks base method.
func (m *MockProvider) ParseWebhookEvent(payload []byte) (dto.ParsedWebhookEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseWebhookEvent", payload)
	ret0, _ := ret[0].(dto.ParsedWebhookEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseWebhookEvent indicates an expected call of ParseWebhookEvent.
func (mr *MockProviderMockRecorder) ParseWebhookEvent(payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseWebhookEvent", reflect.TypeOf((*MockProvider)(nil).ParseWebhookEvent), payload)
}

// VerifySignature mocks base method.
func (m *MockProvider) VerifySignature(payload []byte, signature string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifySignature", payload, signature)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifySignature indicates an expected call of VerifySignature.
func (mr *MockProviderMockRecorder) VerifySignature(payload, signature any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifySignature", reflect.TypeOf((*MockProvider)(nil).VerifySignature), payload, signature)
}

// MockIPaymentFactory is a mock of IPaymentFactory interface.
type MockIPaymentFactory struct {
	ctrl     *gomock.Controller
	recorder *MockIPaymentFactoryMockRecorder
	isgomock struct{}
}

// MockIPaymentFactoryMockRecorder is the mock recorder for MockIPaymentFactory.
type MockIPaymentFactoryMockRecorder struct {
	mock *MockIPaymentFactory
}

// NewMockIPaymentFactory creates a new mock instance.
func NewMockIPaymentFactory(ctrl *gomock.Controller) *MockIPaymentFactory {
	mock := &MockIPaymentFactory{ctrl: ctrl}
	mock.recorder = &MockIPaymentFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPaymentFactory) EXPECT() *MockIPaymentFactoryMockRecorder {
	return m.recorder
}

// GetProvider mocks base method.
func (m *MockIPaymentFactory) GetProvider(provider string) (providers.Provider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProvider", provider)
	ret0, _ := ret[0].(providers.Provider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProvider indicates an expected call of GetProvider.
func (mr *MockIPaymentFactoryMockRecorder) GetProvider(provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProvider", reflect.TypeOf((*MockIPaymentFactory)(nil).GetProvider), provider)
}
