// Code generated by MockGen. DO NOT EDIT.
// Source: hospital-backend/internal/prescription (interfaces: PrescriptionRepositoryInterface,PrescItemsRepo)
//
// Generated by this command:
//
//	mockgen -destination=internal/prescription/mocks/mock_prescription_repository.go -package=mocks hospital-backend/internal/prescription PrescriptionRepositoryInterface,PrescItemsRepo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	prescription "hospital-backend/internal/prescription"
	dto "hospital-backend/internal/prescription/dto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	zap "go.uber.org/zap"
	gorm "gorm.io/gorm"
)

// MockPrescriptionRepositoryInterface is a mock of PrescriptionRepositoryInterface interface.
type MockPrescriptionRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPrescriptionRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockPrescriptionRepositoryInterfaceMockRecorder is the mock recorder for MockPrescriptionRepositoryInterface.
type MockPrescriptionRepositoryInterfaceMockRecorder struct {
	mock *MockPrescriptionRepositoryInterface
}

// NewMockPrescriptionRepositoryInterface creates a new mock instance.
func NewMockPrescriptionRepositoryInterface(ctrl *gomock.Controller) *MockPrescriptionRepositoryInterface {
	mock := &MockPrescriptionRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockPrescriptionRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrescriptionRepositoryInterface) EXPECT() *MockPrescriptionRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockPrescriptionRepositoryInterface) Count(log *zap.Logger, query string, args ...any) (int64, error) {
	m.ctrl.T.Helper()
	varargs := []any{log, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Count", varargs...)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockPrescriptionRepositoryInterfaceMockRecorder) Count(log, query any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{log, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockPrescriptionRepositoryInterface)(nil).Count), varargs...)
}

// CountByStatus mocks base method.
func (m *MockPrescriptionRepositoryInterface) CountByStatus(log *zap.Logger, organisationID, status string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByStatus", log, organisationID, status)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByStatus indicates an expected call of CountByStatus.
func (mr *MockPrescriptionRepositoryInterfaceMockRecorder) CountByStatus(log, organisationID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByStatus", reflect.TypeOf((*MockPrescriptionRepositoryInterface)(nil).CountByStatus), log, organisationID, status)
}

// CreatePrescription mocks base method.
func (m *MockPrescriptionRepositoryInterface) CreatePrescription(log *zap.Logger, db *gorm.DB, arg2 prescription.Prescription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePrescription", log, db, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePrescription indicates an expected call of CreatePrescription.
func (mr *MockPrescriptionRepositoryInterfaceMockRecorder) CreatePrescription(log, db, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePrescription", reflect.TypeOf((*MockPrescriptionRepositoryInterface)(nil).CreatePrescription), log, db, arg2)
}

// DeletePrescription mocks base method.
func (m *MockPrescriptionRepositoryInterface) DeletePrescription(log *zap.Logger, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePrescription", log, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePrescription indicates an expected call of DeletePrescription.
func (mr *MockPrescriptionRepositoryInterfaceMockRecorder) DeletePrescription(log, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePrescription", reflect.TypeOf((*MockPrescriptionRepositoryInterface)(nil).DeletePrescription), log, id)
}

// FindByStatus mocks base method.
func (m *MockPrescriptionRepositoryInterface) FindByStatus(log *zap.Logger, organisationID, status string, limit, offset int) ([]dto.PrescriptionListItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByStatus", log, organisationID, status, limit, offset)
	ret0, _ := ret[0].([]dto.PrescriptionListItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByStatus indicates an expected call of FindByStatus.
func (mr *MockPrescriptionRepositoryInterfaceMockRecorder) FindByStatus(log, organisationID, status, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByStatus", reflect.TypeOf((*MockPrescriptionRepositoryInterface)(nil).FindByStatus), log, organisationID, status, limit, offset)
}

// FindMany mocks base method.
func (m *MockPrescriptionRepositoryInterface) FindMany(log *zap.Logger, query string, args ...any) ([]dto.PrescriptionListItem, error) {
	m.ctrl.T.Helper()
	varargs := []any{log, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindMany", varargs...)
	ret0, _ := ret[0].([]dto.PrescriptionListItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMany indicates an expected call of FindMany.
func (mr *MockPrescriptionRepositoryInterfaceMockRecorder) FindMany(log, query any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{log, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMany", reflect.TypeOf((*MockPrescriptionRepositoryInterface)(nil).FindMany), varargs...)
}

// FindPrescriptionByID mocks base method.
func (m *MockPrescriptionRepositoryInterface) FindPrescriptionByID(log *zap.Logger, query, id string) (prescription.Prescription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPrescriptionByID", log, query, id)
	ret0, _ := ret[0].(prescription.Prescription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPrescriptionByID indicates an expected call of FindPrescriptionByID.
func (mr *MockPrescriptionRepositoryInterfaceMockRecorder) FindPrescriptionByID(log, query, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPrescriptionByID", reflect.TypeOf((*MockPrescriptionRepositoryInterface)(nil).FindPrescriptionByID), log, query, id)
}

// GetNotificationDetails mocks base method.
func (m *MockPrescriptionRepositoryInterface) GetNotificationDetails(log *zap.Logger, query, prescriptionID string) (prescription.PrescriptionNotificationData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotificationDetails", log, query, prescriptionID)
	ret0, _ := ret[0].(prescription.PrescriptionNotificationData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotificationDetails indicates an expected call of GetNotificationDetails.
func (mr *MockPrescriptionRepositoryInterfaceMockRecorder) GetNotificationDetails(log, query, prescriptionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotificationDetails", reflect.TypeOf((*MockPrescriptionRepositoryInterface)(nil).GetNotificationDetails), log, query, prescriptionID)
}

// GetPrescriptionByAppointmentIDCount mocks base method.
func (m *MockPrescriptionRepositoryInterface) GetPrescriptionByAppointmentIDCount(log *zap.Logger, cond ...any) (int64, error) {
	m.ctrl.T.Helper()
	varargs := []any{log}
	for _, a := range cond {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPrescriptionByAppointmentIDCount", varargs...)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrescriptionByAppointmentIDCount indicates an expected call of GetPrescriptionByAppointmentIDCount.
func (mr *MockPrescriptionRepositoryInterfaceMockRecorder) GetPrescriptionByAppointmentIDCount(log any, cond ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{log}, cond...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrescriptionByAppointmentIDCount", reflect.TypeOf((*MockPrescriptionRepositoryInterface)(nil).GetPrescriptionByAppointmentIDCount), varargs...)
}

// GetPrescriptionByID mocks base method.
func (m *MockPrescriptionRepositoryInterface) GetPrescriptionByID(log *zap.Logger, id string) (*prescription.Prescription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrescriptionByID", log, id)
	ret0, _ := ret[0].(*prescription.Prescription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrescriptionByID indicates an expected call of GetPrescriptionByID.
func (mr *MockPrescriptionRepositoryInterfaceMockRecorder) GetPrescriptionByID(log, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrescriptionByID", reflect.TypeOf((*MockPrescriptionRepositoryInterface)(nil).GetPrescriptionByID), log, id)
}

// GetPrescriptionByPatientIDCount mocks base method.
func (m *MockPrescriptionRepositoryInterface) GetPrescriptionByPatientIDCount(log *zap.Logger, patientID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrescriptionByPatientIDCount", log, patientID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrescriptionByPatientIDCount indicates an expected call of GetPrescriptionByPatientIDCount.
func (mr *MockPrescriptionRepositoryInterfaceMockRecorder) GetPrescriptionByPatientIDCount(log, patientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrescriptionByPatientIDCount", reflect.TypeOf((*MockPrescriptionRepositoryInterface)(nil).GetPrescriptionByPatientIDCount), log, patientID)
}

// GetPrescriptionsByAppointmentID mocks base method.
func (m *MockPrescriptionRepositoryInterface) GetPrescriptionsByAppointmentID(log *zap.Logger, query string, cond ...any) ([]prescription.PrescriptionAppointmentData, error) {
	m.ctrl.T.Helper()
	varargs := []any{log, query}
	for _, a := range cond {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPrescriptionsByAppointmentID", varargs...)
	ret0, _ := ret[0].([]prescription.PrescriptionAppointmentData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrescriptionsByAppointmentID indicates an expected call of GetPrescriptionsByAppointmentID.
func (mr *MockPrescriptionRepositoryInterfaceMockRecorder) GetPrescriptionsByAppointmentID(log, query any, cond ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{log, query}, cond...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrescriptionsByAppointmentID", reflect.TypeOf((*MockPrescriptionRepositoryInterface)(nil).GetPrescriptionsByAppointmentID), varargs...)
}

// GetPrescriptionsByDoctorID mocks base method.
func (m *MockPrescriptionRepositoryInterface) GetPrescriptionsByDoctorID(log *zap.Logger, doctorID string) ([]prescription.Prescription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrescriptionsByDoctorID", log, doctorID)
	ret0, _ := ret[0].([]prescription.Prescription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrescriptionsByDoctorID indicates an expected call of GetPrescriptionsByDoctorID.
func (mr *MockPrescriptionRepositoryInterfaceMockRecorder) GetPrescriptionsByDoctorID(log, doctorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrescriptionsByDoctorID", reflect.TypeOf((*MockPrescriptionRepositoryInterface)(nil).GetPrescriptionsByDoctorID), log, doctorID)
}

// GetPrescriptionsByPatientID mocks base method.
func (m *MockPrescriptionRepositoryInterface) GetPrescriptionsByPatientID(log *zap.Logger, query string, args ...any) ([]dto.PrescriptionListItem, error) {
	m.ctrl.T.Helper()
	varargs := []any{log, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPrescriptionsByPatientID", varargs...)
	ret0, _ := ret[0].([]dto.PrescriptionListItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrescriptionsByPatientID indicates an expected call of GetPrescriptionsByPatientID.
func (mr *MockPrescriptionRepositoryInterfaceMockRecorder) GetPrescriptionsByPatientID(log, query any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{log, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrescriptionsByPatientID", reflect.TypeOf((*MockPrescriptionRepositoryInterface)(nil).GetPrescriptionsByPatientID), varargs...)
}

// UpdateStatus mocks base method.
func (m *MockPrescriptionRepositoryInterface) UpdateStatus(log *zap.Logger, tx *gorm.DB, status, prescriptionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", log, tx, status, prescriptionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockPrescriptionRepositoryInterfaceMockRecorder) UpdateStatus(log, tx, status, prescriptionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockPrescriptionRepositoryInterface)(nil).UpdateStatus), log, tx, status, prescriptionID)
}

// MockPrescItemsRepo is a mock of PrescItemsRepo interface.
type MockPrescItemsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPrescItemsRepoMockRecorder
	isgomock struct{}
}

// MockPrescItemsRepoMockRecorder is the mock recorder for MockPrescItemsRepo.
type MockPrescItemsRepoMockRecorder struct {
	mock *MockPrescItemsRepo
}

// NewMockPrescItemsRepo creates a new mock instance.
func NewMockPrescItemsRepo(ctrl *gomock.Controller) *MockPrescItemsRepo {
	mock := &MockPrescItemsRepo{ctrl: ctrl}
	mock.recorder = &MockPrescItemsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrescItemsRepo) EXPECT() *MockPrescItemsRepoMockRecorder {
	return m.recorder
}

// AddItems mocks base method.
func (m *MockPrescItemsRepo) AddItems(log *zap.Logger, db *gorm.DB, medicine []prescription.PrescriptionItems) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddItems", log, db, medicine)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddItems indicates an expected call of AddItems.
func (mr *MockPrescItemsRepoMockRecorder) AddItems(log, db, medicine any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddItems", reflect.TypeOf((*MockPrescItemsRepo)(nil).AddItems), log, db, medicine)
}

// FindMedicineInfoByPID mocks base method.
func (m *MockPrescItemsRepo) FindMedicineInfoByPID(log *zap.Logger, ctx context.Context, query string, args ...any) ([]prescription.MedicineDetInfo, error) {
	m.ctrl.T.Helper()
	varargs := []any{log, ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindMedicineInfoByPID", varargs...)
	ret0, _ := ret[0].([]prescription.MedicineDetInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMedicineInfoByPID indicates an expected call of FindMedicineInfoByPID.
func (mr *MockPrescItemsRepoMockRecorder) FindMedicineInfoByPID(log, ctx, query any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{log, ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMedicineInfoByPID", reflect.TypeOf((*MockPrescItemsRepo)(nil).FindMedicineInfoByPID), varargs...)
}

// GetItemStatusesByPrescriptionID mocks base method.
func (m *MockPrescItemsRepo) GetItemStatusesByPrescriptionID(log *zap.Logger, tx *gorm.DB, prescriptionID string) ([]prescription.PrescriptionItems, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemStatusesByPrescriptionID", log, tx, prescriptionID)
	ret0, _ := ret[0].([]prescription.PrescriptionItems)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItemStatusesByPrescriptionID indicates an expected call of GetItemStatusesByPrescriptionID.
func (mr *MockPrescItemsRepoMockRecorder) GetItemStatusesByPrescriptionID(log, tx, prescriptionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemStatusesByPrescriptionID", reflect.TypeOf((*MockPrescItemsRepo)(nil).GetItemStatusesByPrescriptionID), log, tx, prescriptionID)
}

// GetItemsByPrescriptionID mocks base method.
func (m *MockPrescItemsRepo) GetItemsByPrescriptionID(log *zap.Logger, query string, cond ...any) ([]prescription.MixedPrescriptionItem, error) {
	m.ctrl.T.Helper()
	varargs := []any{log, query}
	for _, a := range cond {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetItemsByPrescriptionID", varargs...)
	ret0, _ := ret[0].([]prescription.MixedPrescriptionItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItemsByPrescriptionID indicates an expected call of GetItemsByPrescriptionID.
func (mr *MockPrescItemsRepoMockRecorder) GetItemsByPrescriptionID(log, query any, cond ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{log, query}, cond...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemsByPrescriptionID", reflect.TypeOf((*MockPrescItemsRepo)(nil).GetItemsByPrescriptionID), varargs...)
}

// GetMedicineIDsByPrescriptionID mocks base method.
func (m *MockPrescItemsRepo) GetMedicineIDsByPrescriptionID(log *zap.Logger, db *gorm.DB, prescriptionID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMedicineIDsByPrescriptionID", log, db, prescriptionID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMedicineIDsByPrescriptionID indicates an expected call of GetMedicineIDsByPrescriptionID.
func (mr *MockPrescItemsRepoMockRecorder) GetMedicineIDsByPrescriptionID(log, db, prescriptionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMedicineIDsByPrescriptionID", reflect.TypeOf((*MockPrescItemsRepo)(nil).GetMedicineIDsByPrescriptionID), log, db, prescriptionID)
}

// GetPrescriptionItemByID mocks base method.
func (m *MockPrescItemsRepo) GetPrescriptionItemByID(log *zap.Logger, id string) (prescription.PrescriptionItems, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrescriptionItemByID", log, id)
	ret0, _ := ret[0].(prescription.PrescriptionItems)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrescriptionItemByID indicates an expected call of GetPrescriptionItemByID.
func (mr *MockPrescItemsRepoMockRecorder) GetPrescriptionItemByID(log, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrescriptionItemByID", reflect.TypeOf((*MockPrescItemsRepo)(nil).GetPrescriptionItemByID), log, id)
}

// GetQtyInfoByMed mocks base method.
func (m *MockPrescItemsRepo) GetQtyInfoByMed(log *zap.Logger, prescriptionID string) ([]prescription.PrescriptionItems, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQtyInfoByMed", log, prescriptionID)
	ret0, _ := ret[0].([]prescription.PrescriptionItems)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQtyInfoByMed indicates an expected call of GetQtyInfoByMed.
func (mr *MockPrescItemsRepoMockRecorder) GetQtyInfoByMed(log, prescriptionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQtyInfoByMed", reflect.TypeOf((*MockPrescItemsRepo)(nil).GetQtyInfoByMed), log, prescriptionID)
}

// GetTotalCountByPrescID mocks base method.
func (m *MockPrescItemsRepo) GetTotalCountByPrescID(log *zap.Logger, prescriptionID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalCountByPrescID", log, prescriptionID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalCountByPrescID indicates an expected call of GetTotalCountByPrescID.
func (mr *MockPrescItemsRepoMockRecorder) GetTotalCountByPrescID(log, prescriptionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalCountByPrescID", reflect.TypeOf((*MockPrescItemsRepo)(nil).GetTotalCountByPrescID), log, prescriptionID)
}

// UpdateDispenseItemQty mocks base method.
func (m *MockPrescItemsRepo) UpdateDispenseItemQty(log *zap.Logger, tx *gorm.DB, query, prescriptionItemID string, dispensedQty int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDispenseItemQty", log, tx, query, prescriptionItemID, dispensedQty)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDispenseItemQty indicates an expected call of UpdateDispenseItemQty.
func (mr *MockPrescItemsRepoMockRecorder) UpdateDispenseItemQty(log, tx, query, prescriptionItemID, dispensedQty any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDispenseItemQty", reflect.TypeOf((*MockPrescItemsRepo)(nil).UpdateDispenseItemQty), log, tx, query, prescriptionItemID, dispensedQty)
}

// UpdatePrescriptionItem mocks base method.
func (m *MockPrescItemsRepo) UpdatePrescriptionItem(log *zap.Logger, item prescription.PrescriptionItems) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePrescriptionItem", log, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePrescriptionItem indicates an expected call of UpdatePrescriptionItem.
func (mr *MockPrescItemsRepoMockRecorder) UpdatePrescriptionItem(log, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePrescriptionItem", reflect.TypeOf((*MockPrescItemsRepo)(nil).UpdatePrescriptionItem), log, item)
}

// UpdatePrescriptionItemStatus mocks base method.
func (m *MockPrescItemsRepo) UpdatePrescriptionItemStatus(log *zap.Logger, tx *gorm.DB, prescriptionItemID, status string, outOfStock bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePrescriptionItemStatus", log, tx, prescriptionItemID, status, outOfStock)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePrescriptionItemStatus indicates an expected call of UpdatePrescriptionItemStatus.
func (mr *MockPrescItemsRepoMockRecorder) UpdatePrescriptionItemStatus(log, tx, prescriptionItemID, status, outOfStock any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePrescriptionItemStatus", reflect.TypeOf((*MockPrescItemsRepo)(nil).UpdatePrescriptionItemStatus), log, tx, prescriptionItemID, status, outOfStock)
}
