// Code generated by MockGen. DO NOT EDIT.
// Source: hospital-backend/internal/prescription (interfaces: PrescriptionServicer,PrescriptionItemServicer)
//
// Generated by this command:
//
//	mockgen -destination=internal/prescription/mocks/mock_prescription_servicer.go -package=mocks hospital-backend/internal/prescription PrescriptionServicer,PrescriptionItemServicer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	prescription "hospital-backend/internal/prescription"
	dto "hospital-backend/internal/prescription/dto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	zap "go.uber.org/zap"
)

// MockPrescriptionServicer is a mock of PrescriptionServicer interface.
type MockPrescriptionServicer struct {
	ctrl     *gomock.Controller
	recorder *MockPrescriptionServicerMockRecorder
	isgomock struct{}
}

// MockPrescriptionServicerMockRecorder is the mock recorder for MockPrescriptionServicer.
type MockPrescriptionServicerMockRecorder struct {
	mock *MockPrescriptionServicer
}

// NewMockPrescriptionServicer creates a new mock instance.
func NewMockPrescriptionServicer(ctrl *gomock.Controller) *MockPrescriptionServicer {
	mock := &MockPrescriptionServicer{ctrl: ctrl}
	mock.recorder = &MockPrescriptionServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrescriptionServicer) EXPECT() *MockPrescriptionServicerMockRecorder {
	return m.recorder
}

// AddPrescriptionItems mocks base method.
func (m *MockPrescriptionServicer) AddPrescriptionItems(log *zap.Logger, payload dto.UpdateRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPrescriptionItems", log, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddPrescriptionItems indicates an expected call of AddPrescriptionItems.
func (mr *MockPrescriptionServicerMockRecorder) AddPrescriptionItems(log, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPrescriptionItems", reflect.TypeOf((*MockPrescriptionServicer)(nil).AddPrescriptionItems), log, payload)
}

// CreatePrescription mocks base method.
func (m *MockPrescriptionServicer) CreatePrescription(log *zap.Logger, requestdto dto.CreatePrescriptionRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePrescription", log, requestdto)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePrescription indicates an expected call of CreatePrescription.
func (mr *MockPrescriptionServicerMockRecorder) CreatePrescription(log, requestdto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePrescription", reflect.TypeOf((*MockPrescriptionServicer)(nil).CreatePrescription), log, requestdto)
}

// FindByStatus mocks base method.
func (m *MockPrescriptionServicer) FindByStatus(log *zap.Logger, limit, offset int, organisationID, status string) ([]dto.PrescriptionListItem, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByStatus", log, limit, offset, organisationID, status)
	ret0, _ := ret[0].([]dto.PrescriptionListItem)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindByStatus indicates an expected call of FindByStatus.
func (mr *MockPrescriptionServicerMockRecorder) FindByStatus(log, limit, offset, organisationID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByStatus", reflect.TypeOf((*MockPrescriptionServicer)(nil).FindByStatus), log, limit, offset, organisationID, status)
}

// FindMany mocks base method.
func (m *MockPrescriptionServicer) FindMany(log *zap.Logger, req dto.FindManyRequest) ([]dto.PrescriptionListItem, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMany", log, req)
	ret0, _ := ret[0].([]dto.PrescriptionListItem)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindMany indicates an expected call of FindMany.
func (mr *MockPrescriptionServicerMockRecorder) FindMany(log, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMany", reflect.TypeOf((*MockPrescriptionServicer)(nil).FindMany), log, req)
}

// GetPrescriptionByAppointmentID mocks base method.
func (m *MockPrescriptionServicer) GetPrescriptionByAppointmentID(log *zap.Logger, reqmodel dto.PresPatients) (dto.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrescriptionByAppointmentID", log, reqmodel)
	ret0, _ := ret[0].(dto.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrescriptionByAppointmentID indicates an expected call of GetPrescriptionByAppointmentID.
func (mr *MockPrescriptionServicerMockRecorder) GetPrescriptionByAppointmentID(log, reqmodel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrescriptionByAppointmentID", reflect.TypeOf((*MockPrescriptionServicer)(nil).GetPrescriptionByAppointmentID), log, reqmodel)
}

// GetPrescriptionsByPatientID mocks base method.
func (m *MockPrescriptionServicer) GetPrescriptionsByPatientID(log *zap.Logger, reqmodel dto.PatientPrescriptionsRequest) (dto.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrescriptionsByPatientID", log, reqmodel)
	ret0, _ := ret[0].(dto.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrescriptionsByPatientID indicates an expected call of GetPrescriptionsByPatientID.
func (mr *MockPrescriptionServicerMockRecorder) GetPrescriptionsByPatientID(log, reqmodel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrescriptionsByPatientID", reflect.TypeOf((*MockPrescriptionServicer)(nil).GetPrescriptionsByPatientID), log, reqmodel)
}

// UpdateManualStatus mocks base method.
func (m *MockPrescriptionServicer) UpdateManualStatus(log *zap.Logger, prescriptionID, appointmentID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateManualStatus", log, prescriptionID, appointmentID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateManualStatus indicates an expected call of UpdateManualStatus.
func (mr *MockPrescriptionServicerMockRecorder) UpdateManualStatus(log, prescriptionID, appointmentID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateManualStatus", reflect.TypeOf((*MockPrescriptionServicer)(nil).UpdateManualStatus), log, prescriptionID, appointmentID, status)
}

// MockPrescriptionItemServicer is a mock of PrescriptionItemServicer interface.
type MockPrescriptionItemServicer struct {
	ctrl     *gomock.Controller
	recorder *MockPrescriptionItemServicerMockRecorder
	isgomock struct{}
}

// MockPrescriptionItemServicerMockRecorder is the mock recorder for MockPrescriptionItemServicer.
type MockPrescriptionItemServicerMockRecorder struct {
	mock *MockPrescriptionItemServicer
}

// NewMockPrescriptionItemServicer creates a new mock instance.
func NewMockPrescriptionItemServicer(ctrl *gomock.Controller) *MockPrescriptionItemServicer {
	mock := &MockPrescriptionItemServicer{ctrl: ctrl}
	mock.recorder = &MockPrescriptionItemServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrescriptionItemServicer) EXPECT() *MockPrescriptionItemServicerMockRecorder {
	return m.recorder
}

// GetMedicineInfo mocks base method.
func (m *MockPrescriptionItemServicer) GetMedicineInfo(log *zap.Logger, prescriptionID string) (prescription.MedicineInfoResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMedicineInfo", log, prescriptionID)
	ret0, _ := ret[0].(prescription.MedicineInfoResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMedicineInfo indicates an expected call of GetMedicineInfo.
func (mr *MockPrescriptionItemServicerMockRecorder) GetMedicineInfo(log, prescriptionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMedicineInfo", reflect.TypeOf((*MockPrescriptionItemServicer)(nil).GetMedicineInfo), log, prescriptionID)
}

// GetPrescriptionsByPIDWithLimit mocks base method.
func (m *MockPrescriptionItemServicer) GetPrescriptionsByPIDWithLimit(log *zap.Logger, pID string, limit, pageno float64) ([]prescription.MixedPrescriptionItem, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrescriptionsByPIDWithLimit", log, pID, limit, pageno)
	ret0, _ := ret[0].([]prescription.MixedPrescriptionItem)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPrescriptionsByPIDWithLimit indicates an expected call of GetPrescriptionsByPIDWithLimit.
func (mr *MockPrescriptionItemServicerMockRecorder) GetPrescriptionsByPIDWithLimit(log, pID, limit, pageno any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrescriptionsByPIDWithLimit", reflect.TypeOf((*MockPrescriptionItemServicer)(nil).GetPrescriptionsByPIDWithLimit), log, pID, limit, pageno)
}

// GetqtyByMedicine mocks base method.
func (m *MockPrescriptionItemServicer) GetqtyByMedicine(log *zap.Logger, prescriptionID string) (map[string]dto.PrescriptionQtyInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetqtyByMedicine", log, prescriptionID)
	ret0, _ := ret[0].(map[string]dto.PrescriptionQtyInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetqtyByMedicine indicates an expected call of GetqtyByMedicine.
func (mr *MockPrescriptionItemServicerMockRecorder) GetqtyByMedicine(log, prescriptionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetqtyByMedicine", reflect.TypeOf((*MockPrescriptionItemServicer)(nil).GetqtyByMedicine), log, prescriptionID)
}

// UpdatePrescriptionItemByID mocks base method.
func (m *MockPrescriptionItemServicer) UpdatePrescriptionItemByID(log *zap.Logger, req dto.UpdatePrescriptionItemRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePrescriptionItemByID", log, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePrescriptionItemByID indicates an expected call of UpdatePrescriptionItemByID.
func (mr *MockPrescriptionItemServicerMockRecorder) UpdatePrescriptionItemByID(log, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePrescriptionItemByID", reflect.TypeOf((*MockPrescriptionItemServicer)(nil).UpdatePrescriptionItemByID), log, req)
}
