// Code generated by MockGen. DO NOT EDIT.
// Source: hospital-backend/internal/prescription (interfaces: NotificationEnqueuer,AppointmentLookup,AppointmentStatusUpdater,PrescriptionItemAdder)
//
// Generated by this command:
//
//	mockgen -destination=internal/prescription/mocks/mock_prescription_deps.go -package=mocks hospital-backend/internal/prescription NotificationEnqueuer,AppointmentLookup,AppointmentStatusUpdater,PrescriptionItemAdder
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	appointments "hospital-backend/internal/appointments"
	dto "hospital-backend/internal/notifications/dto"
	dto0 "hospital-backend/internal/prescription/dto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	zap "go.uber.org/zap"
	gorm "gorm.io/gorm"
)

// MockNotificationEnqueuer is a mock of NotificationEnqueuer interface.
type MockNotificationEnqueuer struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationEnqueuerMockRecorder
	isgomock struct{}
}

// MockNotificationEnqueuerMockRecorder is the mock recorder for MockNotificationEnqueuer.
type MockNotificationEnqueuerMockRecorder struct {
	mock *MockNotificationEnqueuer
}

// NewMockNotificationEnqueuer creates a new mock instance.
func NewMockNotificationEnqueuer(ctrl *gomock.Controller) *MockNotificationEnqueuer {
	mock := &MockNotificationEnqueuer{ctrl: ctrl}
	mock.recorder = &MockNotificationEnqueuerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationEnqueuer) EXPECT() *MockNotificationEnqueuerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockNotificationEnqueuer) Create(ctx context.Context, data dto.CreateRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockNotificationEnqueuerMockRecorder) Create(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNotificationEnqueuer)(nil).Create), ctx, data)
}

// MockAppointmentLookup is a mock of AppointmentLookup interface.
type MockAppointmentLookup struct {
	ctrl     *gomock.Controller
	recorder *MockAppointmentLookupMockRecorder
	isgomock struct{}
}

// MockAppointmentLookupMockRecorder is the mock recorder for MockAppointmentLookup.
type MockAppointmentLookupMockRecorder struct {
	mock *MockAppointmentLookup
}

// NewMockAppointmentLookup creates a new mock instance.
func NewMockAppointmentLookup(ctrl *gomock.Controller) *MockAppointmentLookup {
	mock := &MockAppointmentLookup{ctrl: ctrl}
	mock.recorder = &MockAppointmentLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppointmentLookup) EXPECT() *MockAppointmentLookupMockRecorder {
	return m.recorder
}

// GetAppntmentByID mocks base method.
func (m *MockAppointmentLookup) GetAppntmentByID(log *zap.Logger, id string) (appointments.Appointment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppntmentByID", log, id)
	ret0, _ := ret[0].(appointments.Appointment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppntmentByID indicates an expected call of GetAppntmentByID.
func (mr *MockAppointmentLookupMockRecorder) GetAppntmentByID(log, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppntmentByID", reflect.TypeOf((*MockAppointmentLookup)(nil).GetAppntmentByID), log, id)
}

// MockAppointmentStatusUpdater is a mock of AppointmentStatusUpdater interface.
type MockAppointmentStatusUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockAppointmentStatusUpdaterMockRecorder
	isgomock struct{}
}

// MockAppointmentStatusUpdaterMockRecorder is the mock recorder for MockAppointmentStatusUpdater.
type MockAppointmentStatusUpdaterMockRecorder struct {
	mock *MockAppointmentStatusUpdater
}

// NewMockAppointmentStatusUpdater creates a new mock instance.
func NewMockAppointmentStatusUpdater(ctrl *gomock.Controller) *MockAppointmentStatusUpdater {
	mock := &MockAppointmentStatusUpdater{ctrl: ctrl}
	mock.recorder = &MockAppointmentStatusUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppointmentStatusUpdater) EXPECT() *MockAppointmentStatusUpdaterMockRecorder {
	return m.recorder
}

// UpdateStatusInTx mocks base method.
func (m *MockAppointmentStatusUpdater) UpdateStatusInTx(log *zap.Logger, tx *gorm.DB, status, appointmentID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatusInTx", log, tx, status, appointmentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatusInTx indicates an expected call of UpdateStatusInTx.
func (mr *MockAppointmentStatusUpdaterMockRecorder) UpdateStatusInTx(log, tx, status, appointmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatusInTx", reflect.TypeOf((*MockAppointmentStatusUpdater)(nil).UpdateStatusInTx), log, tx, status, appointmentID)
}

// MockPrescriptionItemAdder is a mock of PrescriptionItemAdder interface.
type MockPrescriptionItemAdder struct {
	ctrl     *gomock.Controller
	recorder *MockPrescriptionItemAdderMockRecorder
	isgomock struct{}
}

// MockPrescriptionItemAdderMockRecorder is the mock recorder for MockPrescriptionItemAdder.
type MockPrescriptionItemAdderMockRecorder struct {
	mock *MockPrescriptionItemAdder
}

// NewMockPrescriptionItemAdder creates a new mock instance.
func NewMockPrescriptionItemAdder(ctrl *gomock.Controller) *MockPrescriptionItemAdder {
	mock := &MockPrescriptionItemAdder{ctrl: ctrl}
	mock.recorder = &MockPrescriptionItemAdderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrescriptionItemAdder) EXPECT() *MockPrescriptionItemAdderMockRecorder {
	return m.recorder
}

// AddItems mocks base method.
func (m *MockPrescriptionItemAdder) AddItems(log *zap.Logger, db *gorm.DB, medicine []dto0.MedicineArray, prescriptionID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddItems", log, db, medicine, prescriptionID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddItems indicates an expected call of AddItems.
func (mr *MockPrescriptionItemAdderMockRecorder) AddItems(log, db, medicine, prescriptionID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddItems", reflect.TypeOf((*MockPrescriptionItemAdder)(nil).AddItems), log, db, medicine, prescriptionID, userID)
}
