// Code generated by MockGen. DO NOT EDIT.
// Source: hospital-backend/internal/permissions (interfaces: PermissionServicer)
//
// Generated by this command:
//
//	mockgen -destination=internal/permissions/mocks/mock_permission_servicer.go -package=mocks hospital-backend/internal/permissions PermissionServicer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	modules "hospital-backend/internal/modules"
	permissions "hospital-backend/internal/permissions"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPermissionServicer is a mock of PermissionServicer interface.
type MockPermissionServicer struct {
	ctrl     *gomock.Controller
	recorder *MockPermissionServicerMockRecorder
	isgomock struct{}
}

// MockPermissionServicerMockRecorder is the mock recorder for MockPermissionServicer.
type MockPermissionServicerMockRecorder struct {
	mock *MockPermissionServicer
}

// NewMockPermissionServicer creates a new mock instance.
func NewMockPermissionServicer(ctrl *gomock.Controller) *MockPermissionServicer {
	mock := &MockPermissionServicer{ctrl: ctrl}
	mock.recorder = &MockPermissionServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPermissionServicer) EXPECT() *MockPermissionServicerMockRecorder {
	return m.recorder
}

// FindMany mocks base method.
func (m *MockPermissionServicer) FindMany() ([]modules.Modules, []permissions.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMany")
	ret0, _ := ret[0].([]modules.Modules)
	ret1, _ := ret[1].([]permissions.Permission)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindMany indicates an expected call of FindMany.
func (mr *MockPermissionServicerMockRecorder) FindMany() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMany", reflect.TypeOf((*MockPermissionServicer)(nil).FindMany))
}
