// Code generated by MockGen. DO NOT EDIT.
// Source: hospital-backend/internal/permissions (interfaces: PermissionRepo)
//
// Generated by this command:
//
//	mockgen -destination=internal/permissions/mocks/mock_permission_repository.go -package=mocks hospital-backend/internal/permissions PermissionRepo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	permissions "hospital-backend/internal/permissions"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	zap "go.uber.org/zap"
)

// MockPermissionRepo is a mock of PermissionRepo interface.
type MockPermissionRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPermissionRepoMockRecorder
	isgomock struct{}
}

// MockPermissionRepoMockRecorder is the mock recorder for MockPermissionRepo.
type MockPermissionRepoMockRecorder struct {
	mock *MockPermissionRepo
}

// NewMockPermissionRepo creates a new mock instance.
func NewMockPermissionRepo(ctrl *gomock.Controller) *MockPermissionRepo {
	mock := &MockPermissionRepo{ctrl: ctrl}
	mock.recorder = &MockPermissionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPermissionRepo) EXPECT() *MockPermissionRepoMockRecorder {
	return m.recorder
}

// BatchInsert mocks base method.
func (m *MockPermissionRepo) BatchInsert(log *zap.Logger, arg1 []permissions.Permission, size int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchInsert", log, arg1, size)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchInsert indicates an expected call of BatchInsert.
func (mr *MockPermissionRepoMockRecorder) BatchInsert(log, arg1, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchInsert", reflect.TypeOf((*MockPermissionRepo)(nil).BatchInsert), log, arg1, size)
}

// FindMany mocks base method.
func (m *MockPermissionRepo) FindMany(log *zap.Logger) ([]permissions.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMany", log)
	ret0, _ := ret[0].([]permissions.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMany indicates an expected call of FindMany.
func (mr *MockPermissionRepoMockRecorder) FindMany(log any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMany", reflect.TypeOf((*MockPermissionRepo)(nil).FindMany), log)
}

// GetPermissionByName mocks base method.
func (m *MockPermissionRepo) GetPermissionByName(log *zap.Logger) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPermissionByName", log)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPermissionByName indicates an expected call of GetPermissionByName.
func (mr *MockPermissionRepoMockRecorder) GetPermissionByName(log any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermissionByName", reflect.TypeOf((*MockPermissionRepo)(nil).GetPermissionByName), log)
}
